### ISSUE TITLE
com.coronalabs bit plugin not found

### ISSUE THREAD

**Issue by SashaVanzuriak** [coronalabs/corona#101]
Hello, just download latest Linux release version and [canon demo project](https://github.com/coronalabs-samples/CoronaCannon/)
My error is:

```
/__w/corona/corona/platform/resources/init.lua:931: module 'plugin.bit' not found:
	no field package.preload['plugin.bit']

```

**Comment by Shchvova** [comment]
I plan to merge it in, but try http://solar2dtux.com
