### ISSUE TITLE
Boot Crash on iOS 11.4.1 device with Corona 3583 and XCode 11.5

### ISSUE THREAD

**Issue by vegasfun** [coronalabs/corona#103]
Hi,
Just built with Corona 3583 and XCode 11.5.
Crashed on Device running iOS 11.4.1 just after showing splash screen.
No problems when testing on a couple of other devices running newer iOS versions.

Crash report attached...

[Vegas Fun Slots-2020-06-29-121039.ips.txt](https://github.com/coronalabs/corona/files/4849399/Vegas.Fun.Slots-2020-06-29-121039.ips.txt)

**Comment by vegasfun** [comment]
Tried building with 3582 and XCode 11.4.1 and got the same result:
NOTE: Splash screen shows then it exits abruptly with no message


[Vegas Fun Slots-2020-06-29-221609.txt](https://github.com/coronalabs/corona/files/4849583/Vegas.Fun.Slots-2020-06-29-221609.txt)

**Comment by Shchvova** [comment]
Fix should be deployed now. Please test.

**Comment by vegasfun** [comment]
It works! Thank you very much for the quick response & action!
