### ISSUE TITLE
Solar2D Produces Black Flash on Transition to Foreground

### ISSUE THREAD

**Issue by dgoldman** [coronalabs/corona#105]
Please see details in the Solar2D forum at 

[https://forums.solar2d.com/t/black-flash-on-transition-to-foreground/351623](url)

Please see the slow motion video of the behavior in the Xcode simulator. From what I can see Solar2D generates and displays a black mask on launch or transition to foreground before transitioning to the app. 

The notes in the forum are for iOS, but I noticed that on Android when starting up an app the black "flash" is also produced. To summarize:
On Android - the black flash is displayed on initial startup before the splash screen only. When transitioning to the foreground this does not happen.
On iOS - the black flash is not produced on initial startup, only when transitioning to the foreground from the background.

**Comment by super-toki** [comment]
Please solve this problem.

**Comment by super-toki** [comment]
After a brief conversation and testing with vlad, I found out that the underlying performance issue on iOS is Metal-related. Building with Metal solves that problem.
