### ISSUE TITLE
Size of iOS build .ipa doubled after fix for Corona 3583

### ISSUE THREAD

**Issue by vegasfun** [coronalabs/corona#106]
Hello,

Thanks for the quick fix of a crash on iOS 11.4.1 building with Corona 3583. However, it looks like something is not quite right with the update as the resulting .ipa I just built has roughly doubled in size from about 80MB to 153MB

**Comment by Shchvova** [comment]
Big part of IPA size after the packaging is swift support libraries. They won’t be counted against app size on the store.
This happened because Facebook decided to use Swift in their SDK core #facebook/facebook-ios-sdk/1390
