### ISSUE TITLE
Native Builds: CoronaBuilder still downloading from marketplace.coronalabs.com (and failing)

### ISSUE THREAD

**Issue by chkuendig** [coronalabs/corona#107]
I would like to migrate my CoronaSDK project which is built with XCode (so i can nicely integrate it into a standard CI solution - Azure AppCenter in my case) to Solar2D, but I currently fail at the first step of the build:

```
> xcodebuild -project "App.xcodeproj" -scheme "Download Plugins" 


PhaseScriptExecution Download\ Plugins /Users/christian/Library/Developer/Xcode/DerivedData/App-gqgvwrzahdyfdrgexupenwdowlof/Build/Intermediates.noindex/App.build/Debug-iphoneos/Download\ Plugins.build/Script-F597AC721ED8CA480085F5E5.sh (in target 'Download Plugins' from project 'App')
    cd /Applications/Corona-3601/Native/Project\ Template/App/ios
    /bin/sh -c /Users/christian/Library/Developer/Xcode/DerivedData/App-gqgvwrzahdyfdrgexupenwdowlof/Build/Intermediates.noindex/App.build/Debug-iphoneos/Download\\\ Plugins.build/Script-F597AC721ED8CA480085F5E5.sh

ERROR: plugin could not be validated: plugin.OneSignal (com.onesignal)
ERROR: Activate plugin at: https://marketplace.coronalabs.com/plugin/com.onesignal/plugin.OneSignal
ERROR: exiting due to plugins above not being activated.
Exiting due to errors (above)
Command PhaseScriptExecution failed with a nonzero exit code
```

Adding just one of these to the default sample project also allows me to easily demonstrate the effect: 

```
> `/Applications/Corona-3601/Native/Corona/mac/bin/CoronaBuilder.app/Contents/MacOS/CoronaBuilder plugins download ios "/Applications/Corona-3601/Native/Project Template/App/Corona/build.settings"

ERROR: plugin could not be validated: plugin.OneSignal (com.onesignal)
ERROR: Activate plugin at: https://marketplace.coronalabs.com/plugin/com.onesignal/plugin.OneSignal
ERROR: exiting due to plugins above not being activated.
```

Is there an alternative workaround using the simulator via CLI to download the plugins instead of the CoronaBuilder-based Xcode target?

**Edit:**  Manually adding the URL seems to work as a workaround.

**Comment by V4NDER** [comment]
I am with the same problem. Any solution?

ERROR: plugin could not be validated: plugin.notifications.v2 (com.coronalabs)
ERROR: Activate plugin at: https://marketplace.coronalabs.com/plugin/com.coronalabs/plugin.notifications.v2
ERROR: plugin could not be validated: plugin.iTunes (com.coronalabs)
ERROR: Activate plugin at: https://marketplace.coronalabs.com/plugin/com.coronalabs/plugin.iTunes
ERROR: exiting due to plugins above not being activated.

**Comment by schizoid2k** [comment]
Same issue here...

```
ERROR: plugin could not be validated: plugin.gpgs.v2 (com.coronalabs)
ERROR: Activate plugin at: https://marketplace.coronalabs.com/plugin/com.coronalabs/plugin.gpgs.v2
ERROR: plugin could not be validated: plugin.google.iap.v3 (com.coronalabs)
ERROR: Activate plugin at: https://marketplace.coronalabs.com/plugin/com.coronalabs/plugin.google.iap.v3
ERROR: plugin could not be validated: plugin.GBCDataCabinet (com.gamesbycandlelight)
ERROR: Activate plugin at: https://marketplace.coronalabs.com/plugin/com.gamesbycandlelight/plugin.GBCDataCabinet
ERROR: plugin could not be validated: plugin.flurry.analytics (com.coronalabs)
ERROR: Activate plugin at: https://marketplace.coronalabs.com/plugin/com.coronalabs/plugin.flurry.analytics
ERROR: plugin could not be validated: plugin.iap_badger (uk.co.happymongoose)
ERROR: Activate plugin at: https://marketplace.coronalabs.com/plugin/uk.co.happymongoose/plugin.iap_badger
ERROR: plugin could not be validated: plugin.admob (com.coronalabs)
ERROR: Activate plugin at: https://marketplace.coronalabs.com/plugin/com.coronalabs/plugin.admob
ERROR: exiting due to plugins above not being activated.
```

**Comment by chkuendig** [comment]
As I mentioned in the initial comment, you can work around this bug by adding the URL directly in ```build.settings```, e.g.

```lua
["plugin.openssl"] =
                          {
                          publisherId = "com.coronalabs",
                          supportedPlatforms = {
                          iphone = { url="https://github.com/coronalabs/com.coronalabs-plugin.openssl/releases/download/v1/2016.2883-iphone.tgz" },
				}
                          },
```

**Comment by ricaragao** [comment]
You know how can I get url of onesignal plugin ?

> As I mentioned in the initial comment, you can work around this bug by adding the URL directly in `build.settings`, e.g.
> 
> ```lua
> ["plugin.openssl"] =
>                           {
>                           publisherId = "com.coronalabs",
>                           supportedPlatforms = {
>                           iphone = { url="https://github.com/coronalabs/com.coronalabs-plugin.openssl/releases/download/v1/2016.2883-iphone.tgz" },
> 				}
>                           },
> ```
> 
> you'll have to look for these tgz files in the coronalabs accounts on Github or from the new plugin marketplace

**Comment by Shchvova** [comment]
Don **not** use urls for plugins available through https://plugins.Solar2D.com
Using without custom url is much more efficient.

**Comment by ricaragao** [comment]
I'm using, but I got this error:

ERROR: plugin could not be validated: plugin.OneSignal (com.onesignal)
ERROR: Activate plugin at: https://marketplace.coronalabs.com/plugin/com.onesignal/plugin.OneSignal
ERROR: exiting due to plugins above not being activated.

How can I change source to plugins.solar2d  ?

> Don **not** use urls for plugins available through https://plugins.Solar2D.com
> Using without custom url is much more efficient.

**Comment by Shchvova** [comment]
You probably want to download the latest version of Solar2D.

**Comment by ricaragao** [comment]
Yeah, I'm using 3617.

**Comment by Shchvova** [comment]
ah. Sorry. You're using native. All plugins are available on GitHub, either on http://github.com/coronalabs/ (`com.coronalabs` plugins) or on http://github.com/solar2d/ (everything else on https://plugins.solar2d.com)

**Comment by scottrules44** [comment]
iOS (since v3686) and Android both support getting plugins from the Collector and support getting plugins from plugins.solar2d.com and solar2dmarketplace.com
