### ISSUE TITLE
New Google Play billing states are not supported

### ISSUE THREAD

**Issue by timwickey** [coronalabs/corona#109]
> On November 1, 2020, account hold and subscription restore will become mandatory. Subscription pause and resubscribe will also be enabled for all apps.

> Resubscribe is not currently available for your users because your app does not use Billing Library 2.0 in all active APKs.

The new billing states of Grace period, on Hold, Paused for subscriptions need to be supported. Billing Library 2.0 is required.

[https://developer.android.com/google/play/billing/subs](url)

**Comment by ycandrewkao** [comment]
+1 from us.

**Comment by solares** [comment]
+1 also as we do too

**Comment by ycandrewkao** [comment]
@Shchvova I just want to make sure this is still on the list to be done prior to Google's deadline - with enough time for us to make the corresponding changes.

**Comment by Shchvova** [comment]
Hey. Do you still have this warning in your apps? May I ask to screenshot where is it and post it here if you do. Thanks

**Comment by ycandrewkao** [comment]
We are not having warnings since these features aren't turned on yet. But our questions/concerns are as follows: 

1) Our key concern is that to support this state, we need to be using Billing Library 2.0 or above. Is that already done on the Solar2D side already? We are currently using plugin.google.iap.v3. 

2) It looks like there are a few new states that our code needs to be able to handle. Are these states being returned by the plugin? If so, what are the transaction.state values that we should be looking for? 
- Account hold
- Pause
- Resubscribe
- Restore 

Here is a bit more information from Google:
https://android-developers.googleblog.com/2020/06/new-features-to-acquire-and-retain-subscribers.html

Many thanks!

**Comment by ycandrewkao** [comment]
@Shchvova Looking at that Google link I sent, it actually looks like we need to be on Billing Library 3?

**Comment by ycandrewkao** [comment]
@Shchvova I just want to follow up to see if you can point me to the `queryPurchases()` call. That may just resolve this entire issue?

**Comment by usmanat77sparx** [comment]
@Shchvova I can see warning under resubscribe, to remove that I think Billing Library 3 is required. Here is a 
<img width="1051" alt="resubscribe" src="https://user-images.githubusercontent.com/43152419/95708748-7693bd00-0c76-11eb-844d-eb445805f5fe.png">
screenshot.

**Comment by Shchvova** [comment]
@usmanat77sparx  this is so weird, because we're using billing APIv3. You can't select resubscribe at all? What are options in the dropdown? Also, what the link says?

**Comment by usmanat77sparx** [comment]
@Shchvova Here are all options.
<img width="307" alt="All options" src="https://user-images.githubusercontent.com/43152419/95714595-e491b180-0c81-11eb-9803-50a442337e55.png">

**Comment by Shchvova** [comment]
And where does link follows?

**Comment by usmanat77sparx** [comment]
This is to "Learn more" link:
https://developer.android.com/google/play/billing/integrate

**Comment by timwickey** [comment]
Any updates on this?

**Comment by Shchvova** [comment]
Hello! I made a new plugin, which suppose to be a drop-in replacement for google.iap.v3. Testing it right now with some developers.

**Comment by Shchvova** [comment]
I need some testing, if possible. I made a new plugin which is designed to be a drop-in replacement for Google IAPv3, Google Billing. I need help testing it.
To test it, please, change `v3` in your build.settings to `billing`. That's it. That are all changes required.
(you should get something like `["plugin.google.iap.billing"] = {  publisherId = "com.coronalabs", },`)

This plugin have minor differences, like you must make sure to call finishTransaction and some new states. Here are docs https://docs.coronalabs.com/plugin/google-iap-billing/

**Comment by agramonte** [comment]
I’ll run some test today and let you know if I find anything.

**Comment by ycandrewkao** [comment]
We'll give it a try on Monday..

**Comment by timwickey** [comment]
Did it work? @ycandrewkao @agramonte

**Comment by Shchvova** [comment]
I got several reports that it’s working out well. Closing the issue. I’ll update docs (guides) later this week.

**Comment by agramonte** [comment]
Sorry Vlad forgot to reply. NO issues for me.
