### ISSUE TITLE
GPGSv2 plugin does not download on 3601, but will on 3599

### ISSUE THREAD

**Issue by BigEndahs** [coronalabs/corona#110]
Install 3601, clear out the roaming folder of old downloaded plugins.  Include GPGSv2 plugin in project and include it.  Plugin will not download and will throw an exception.

3599, however, does download the plugin and code works as expected.

Other plugins were NOT affected, including social, zip, and more.

**Comment by Shchvova** [comment]
That’s crazy! What kind of error are you getting, and enable debugBuildProcess

https://gist.github.com/Shchvova/62200d4835354d6cb15c010b8600f6fb#file-gistfile1-txt

**Comment by V4NDER** [comment]
I have the same problem to download notifications.v2.
Apparently version 3061 does not authenticate the user to download the plugins

**Comment by Shchvova** [comment]
Is this still an issue with 3603?

**Comment by scottrules44** [comment]
This has been fixed in newer builds :)
