### ISSUE TITLE
Firebase Cloud messaging

### ISSUE THREAD

**Issue by imsimeonaronk** [coronalabs/corona#111]
2020.3601. notifications.registerForPushNotifications({useFCM=true}) 
it does not trigger the confirmation message to authorise the sending notifications. 
And didn’t receive Firebase Message.
The same works fine in Android. Thanks

**Comment by imsimeonaronk** [comment]
@Shchvova any update?

**Comment by nettrer** [comment]
I am experiencing the same phenomenon.
The test environment is iPhone Pro 11.
Just in "config.lua"
"elseif (display.pixelHeight / display.pixelWidth> 1.72) then"
When this code enters
"notifications.registerForPushNotifications({useFCM=true})" in the "main.lua" file did not work.

My full code "config.lua"

`
``if ( string.sub( system.getInfo("model"), 1, 4 ) == "iPad" ) then
application =
	{
		content =
		{
			width = 360,
			height = 480,
			scale = "letterBox",
			xAlign = "center",
			yAlign = "center",
			fps = 60,
			imageSuffix =
				{
					["@2x"] = 1.5,
					["@4x"] = 3.0,
				},
		},
		notification =  
		{
			google =
			{
				-- This Project Number (also known as a Sender ID) tells Corona to register this application
				-- for push notifications with the Google Cloud Messaging service on startup.
				-- This number can be obtained from the Firebase Console https://console.firebase.google.com/
				-- Select your project -> (Gear Icon) -> Project Settings -> Cloud Messaging -> Sender ID field
				projectNumber = "997670102122",
			},
			iphone =
			{
				types =
				{
					"badge",
					"sound",
					"alert"
				},
			},
		},	  
	}

elseif ( string.sub( system.getInfo("model"), 1, 2 ) == "iP" and display.pixelHeight > 960 ) then
application =
	{
		content =
		{
			width = 320,
			height = 568,
			scale = "letterBox",
			xAlign = "center",
			yAlign = "center",
			fps = 60,
			imageSuffix =
			{
				["@2x"] = 1.5,
				["@4x"] = 3.0,
			},
			notification =  
			{
				google =
				{
					projectNumber = "997670102122",
				},
				iphone =
				{
					types =
					{
						"badge",
						"sound",
						"alert"
					},
				},
			},		
		},
	}
elseif ( string.sub( system.getInfo("model"), 1, 2 ) == "iP" ) then
application =
	{
		content =
		{
			width = 320,
			height = 480,
			scale = "letterBox",
			xAlign = "center",
			yAlign = "center",
			fps = 60,
			imageSuffix =
			{
				["@2x"] = 1.5,
				["@4x"] = 3.0,
			},
		},
		notification =  
		{
			google =
			{
				projectNumber = "997670102122",
			},
			iphone =
			{
				types =
				{
					"badge", "sound", "alert"
				},
			},
		},				
	}
elseif ( display.pixelHeight / display.pixelWidth > 1.72 ) then
application =
	{
		content =
		{
			width = 320,
			height = 570,
			scale = "letterBox",
			xAlign = "center",
			yAlign = "center",
			fps = 60,
			imageSuffix =
			{
				["@2x"] = 1.5,
				["@4x"] = 3.0,
			},
		},
		
		notification =  
		{
			google =
			{
				projectNumber = "997670102122",
			},
			iphone =
			{
				types =
				{
					"badge",
					"sound",
					"alert"
				},
			},
		},				
	}
else
	application =
	{
		content =
		{
			width = 320,
			height = 512,
			fps = 60,
			scale = "letterBox",
			xAlign = "center",
			yAlign = "center",
			imageSuffix =
			{
				["@2x"] = 1.5,
				["@4x"] = 3.0,
			},
		},
		
		notification =  
		{
			google =
			{
				projectNumber = "997670102122",
			},
			iphone =
			{
				types =
				{
					"badge",
					"sound",
					"alert"
				},
			},
		},				
	}
end   
`

**Comment by imsimeonaronk** [comment]
@Shchvova

**Comment by scottrules44** [comment]
This is old but I was able to register my device on my iPhone 11 and get notifications with the newest Firebase Notification v2 plugin
