### ISSUE TITLE
iOS build fails if splashScreen image is not in root directory

### ISSUE THREAD

**Issue by mdsandell** [coronalabs/corona#123]
I didn't see this documented anywhere, so I don't know if it's a "feature" or a bug, but I found that using a custom splash screen image crashes the iOS build if the image you use is not in your project's root directory. From build.settings:

**Bad:**
```
    splashScreen = 
    {
        enable = true,
        image = "images/splash.jpg"
    },
```
**Good:**
```
    splashScreen = 
    {
        enable = true,
        image = "splash.jpg"
    },
```

The build fails with a nondescript error:
```
Aug 04 15:41:42.357 BUILD ERROR: Build script failed
Aug 04 15:41:42.357 
Aug 04 15:41:42.385 iOS build failed (1) after 6 seconds
Aug 04 15:41:42.749 ERROR: Build Failed: Build script failed
```

**Comment by sekodev** [comment]
This should be resolved with #174 and probably will be included in next release.
