### ISSUE TITLE
Struggling to install latest version of Solar2d

### ISSUE THREAD

**Issue by FrankPujo** [coronalabs/corona#131]
The installer of Solar2d 2020.3611 goes actually all good, the problem comes when i try to run the Corona Simulator and it says that a file is missing, so i run the installer again to Repair Corona. I tried this process multiple times, but it won't go. Anyone can tell me why and how to fix it? Thank you!

**Comment by Shchvova** [comment]
Which file is missing?

**Comment by FrankPujo** [comment]
> Which file is missing?

mfc140u.dll

**Comment by Shchvova** [comment]
Did you resolve the issue?

**Comment by FrankPujo** [comment]
> Did you resolve the issue?

Yes, it wasn't nothing about the installer, just a problem on my pc... Found the way to make it and working now
