### ISSUE TITLE
Google review API

### ISSUE THREAD

**Issue by mark-sgs** [coronalabs/corona#133]
Can this be added please?

[https://android-developers.googleblog.com/2020/08/in-app-review-api.html](https://android-developers.googleblog.com/2020/08/in-app-review-api.html)

**Comment by sekodev** [comment]
Scott says that he's looking into it - https://forums.solar2d.com/t/google-in-app-review-api-in-solar2d/352175/5?u=bgmadclown

**Comment by sekodev** [comment]
This is now available as a plugin through Solar2D Marketplace - https://solar2dmarketplace.com/plugins?ReviewPopUp_tech-scotth
