### ISSUE TITLE
Android: display.getSafeAreaInsets does not work for android devices.

### ISSUE THREAD

**Issue by agramonte** [coronalabs/corona#145]
Somebody had a similar problem in the forums here:
https://forums.solar2d.com/t/display-safeareainsets-does-not-detect-android-system-ui-bottom-navigation-bar/149933

Create an app and launch on a device that has unavailable areas at the top or bottom. The display.getSafeAreaInsets always returns 0. Searched in the source code and I couldn't find the implementation of this call on Android (I did find It on iOS).

**Comment by XeduR** [comment]
This issue has already been raised in #127 and has been confirmed to be addressed relatively soon (likely after upcoming the ad plugin updates).

**Comment by agramonte** [comment]
Thank you
