### ISSUE TITLE
Lua plugin resources are not bundled

### ISSUE THREAD

**Issue by Shchvova** [coronalabs/corona#148]
Self help steps before reporting the issue:
[x] Check [Solar2D forums](https://forums.solar2d.com/) for a solution
[x] If Android: make sure Java8 is installed and reported when running `java -version` and `javac -version` if not, download and install [Java 8](https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html)

**Before reporting**
resources bundled in Lua plugins are ignored

**Platforms involved**
Building on: macOS 10-15-16/Windows 7-8-10/
Building for: iOS/Android

**repro**
Build https://schroederapps.github.io/progress_ring_sample.zip, note that resulting apps does not contain plugin resources.

**Comment by mark-sgs** [comment]
Could java 8 be included in the msi?

**Comment by Shchvova** [comment]
@mark-sgs thats a great ideal. I looked around and it seems that we totally can bundle it together, for both mac and windows, same versions Android Studio uses. It'll increase distribution size by about 100mb, but totally worth it, I think.
