### ISSUE TITLE
Feature request: bundle Java

### ISSUE THREAD

**Issue by Shchvova** [coronalabs/corona#149]
Bundle same JRE/JDK AndroidStudio uses to streamline android builds.

**Comment by sekodev** [comment]
Is this working as of [2020.3629](https://github.com/coronalabs/corona/releases/tag/3629) (or [2020.3631](https://github.com/coronalabs/corona/releases/tag/3631))?

**Comment by Shchvova** [comment]
Indeed. This is implemented in latest builds.
