### ISSUE TITLE
Ways to generate CoronaCards.aar from source

### ISSUE THREAD

**Issue by zoubarry** [coronalabs/corona#153]
Wondering if there is a way to build the android **CoronaCards.aar** file from source? Or is there a script file or ./gradlew task already doing that?

**Comment by Shchvova** [comment]
Here  how it gets generated https://github.com/coronalabs/corona/blob/6c27cfbd2fcfeddd3e9e279cb654f0afec45ac49/.github/workflows/build.yml#L226-L230

**Comment by ahetawal-p** [comment]
Thanks @Shchvova
How do I get access to Native/CoronaNative.tar.gz
I am trying build this from current master branch ?

**Comment by Shchvova** [comment]
It’s used only to extract `Corona.aar`. You can take it from Native in installation, or build yourself with `gradlew assembleRelease`
