### ISSUE TITLE
Solar2D Free Plugins not linking with Big Sur and Xcode 12

### ISSUE THREAD

**Issue by zampar** [coronalabs/corona#155]
**Platforms involved**
Building on: macOS Big Sur 11.0 Beta (20A5374g)
Building for: iOS 14 Beta

**Attach your build.settings**
       ["plugin.notifications.v2"] =
        {
            publisherId = "com.coronalabs",
        },
        ["CoronaProvider.gameNetwork.apple"] =
        { 
            publisherId = "com.coronalabs",
        }, 
        ["CoronaProvider.native.popup.social"] = {
            publisherId = "com.coronalabs",
        },
        ["CoronaProvider.native.popup.activity"] =
        {
            publisherId = "com.coronalabs"
        },
        ["plugin.collisionFilters"] =
        {
            publisherId = "com.coronalabs"
        },

**Full build log**
Building: Unpacking build with plugins
Building: Adding plugins
Analyzing plugins...
Found native plugin: /Users/armandozjr/Desktop/pizzagash.app/.build/plugin.reviewPopUp
Found native plugin: /Users/armandozjr/Desktop/pizzagash.app/.build/CoronaProvider.native.popup.social
Found native plugin: /Users/armandozjr/Desktop/pizzagash.app/.build/plugin.appodeal.AppLovin
Found native plugin: /Users/armandozjr/Desktop/pizzagash.app/.build/plugin.appodeal.Flurry
Found native plugin: /Users/armandozjr/Desktop/pizzagash.app/.build/plugin.notifications.v2
Found native plugin: /Users/armandozjr/Desktop/pizzagash.app/.build/CoronaProvider.gameNetwork.apple
Found native plugin: /Users/armandozjr/Desktop/pizzagash.app/.build/CoronaProvider.native.popup.activity
Found native plugin: /Users/armandozjr/Desktop/pizzagash.app/.build/plugin.appodeal.base
Found Swift usage in a plugin: 	/Users/armandozjr/Desktop/pizzagash.app/.build/plugin.appodeal.base
	Done.

Analyzing Lua plugins...
Examining plugin: plugin.reviewPopUp
Examining plugin: CoronaProvider.native.popup.social
Examining plugin: plugin.appodeal.AppLovin
Examining plugin: plugin.appodeal.Flurry
Examining plugin: plugin.notifications.v2
Examining plugin: CoronaProvider.gameNetwork.apple
Examining plugin: CoronaProvider.native.popup.activity
Examining plugin: plugin.collisionFilters
Found Lua plugin: plugin.collisionFilters
Examining plugin: plugin.appodeal.base
	<execute>mkdir -p "/Users/armandozjr/Desktop/pizzagash.app/corona-plugins"</execute>
	<result></result>
	<execute>cp -R "/Users/armandozjr/Desktop/pizzagash.app/.build/plugin.collisionFilters/lua_51/"/* "/Users/armandozjr/Desktop/pizzagash.app/corona-plugins"</execute>
	<result></result>
	<execute>find "/Users/armandozjr/Desktop/pizzagash.app/corona-plugins" \( -name '*.lu' -o  -name '*.lua' \) -delete</execute>
	<result></result>
	<execute>COPYPNG=$(xcrun -f copypng); find "/Users/armandozjr/Desktop/pizzagash.app/corona-plugins" -name '*.png' -exec "$COPYPNG" -compress {} {}.copypng \; -exec mv {}.copypng {} \;</execute>
	<result></result>
	Done.

Compiling Slices...
	Compiling architecture:	armv7
	<execute>cd "/var/folders/_r/83_6664x4b7520gc7zj__0580000gn/T/CLtmpd8XVBr/armv7";unset LIBRARY_PATH; export IPHONEOS_DEPLOYMENT_TARGET=8; export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin";"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++" -stdlib=libstdc++ -arch armv7 -isysroot "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk" -ObjC -all_load -fobjc-link-runtime -miphoneos-version-min=8 -std=c++11 -stdlib=libc++ -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -L"/Users/armandozjr/Desktop/pizzagash.app/.build/libtemplate" -L"/Users/armandozjr/Desktop/pizzagash.app/.build/plugin.reviewPopUp" -L"/Users/armandozjr/Desktop/pizzagash.app/.build/CoronaProvider.native.popup.social" -L"/Users/armandozjr/Desktop/pizzagash.app/.build/plugin.appodeal.AppLovin" -L"/Users/armandozjr/Desktop/pizzagash.app/.build/plugin.appodeal.Flurry" -L"/Users/armandozjr/Desktop/pizzagash.app/.build/plugin.notifications.v2" -L"/Users/armandozjr/Desktop/pizzagash.app/.build/CoronaProvider.gameNetwork.apple" -L"/Users/armandozjr/Desktop/pizzagash.app/.build/CoronaProvider.native.popup.activity" -L"/Users/armandozjr/Desktop/pizzagash.app/.build/plugin.appodeal.base" -L"/usr/lib/swift" -L"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos" -F"/Users/armandozjr/Desktop/pizzagash.app/Frameworks" -F"/Users/armandozjr/Desktop/pizzagash.app/.build/libtemplate" -F"/Users/armandozjr/Desktop/pizzagash.app/.build/plugin.reviewPopUp" -F"/Users/armandozjr/Desktop/pizzagash.app/.build/CoronaProvider.native.popup.social" -F"/Users/armandozjr/Desktop/pizzagash.app/.build/plugin.appodeal.AppLovin" -F"/Users/armandozjr/Desktop/pizzagash.app/.build/plugin.appodeal.Flurry" -F"/Users/armandozjr/Desktop/pizzagash.app/.build/plugin.notifications.v2" -F"/Users/armandozjr/Desktop/pizzagash.app/.build/CoronaProvider.gameNetwork.apple" -F"/Users/armandozjr/Desktop/pizzagash.app/.build/CoronaProvider.native.popup.activity" -F"/Users/armandozjr/Desktop/pizzagash.app/.build/plugin.appodeal.base" -F"/usr/lib/swift" -F"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos" -framework AudioToolbox -framework AVFoundation -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreMedia -framework CoreMotion -framework CoreVideo -framework CoreText -framework GameKit -framework GLKit -framework ImageIO -framework MapKit -framework MediaPlayer -framework MessageUI -framework MobileCoreServices -framework OpenAL -framework QuartzCore -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -framework AppLovinSDK -framework GoogleUtilities -framework protobuf -framework FBLPromises -framework FirebaseInstanceID -framework FirebaseMessaging -framework FirebaseInstallations -framework FirebaseCore -framework CoreTelephony -framework JavaScriptCore -framework CoreBluetooth -framework WebKit -framework Appodeal -weak_framework GameController -weak_framework AssetsLibrary -weak_framework Photos -weak_framework Foundation -weak_framework Twitter -weak_framework social -weak_framework UserNotifications -weak_framework UserNotificationsUI -weak_framework SafariServices -weak_framework AdSupport -lobjc -lsqlite3 -ltemplate -lplugin_reviewPopUp -lnative-popup-social -lAPDAppLovinAdapter -lNotificationsV2Plugin -lgameNetwork-apple -lnative-popup-activity -lplugin_appodeal_base -lxml2 -lz -lAPDAppodealAdExchangeAdapter -o "/var/folders/_r/83_6664x4b7520gc7zj__0580000gn/T/CLtmpd8XVBr/armv7/pizzagash"</execute>
	<result>ld: framework not found social
clang: error: linker command failed with exit code 1 (use -v to see invocation)</result>
ERROR: Builder failed: ld: framework not found social
clang: error: linker command failed with exit code 1 (use -v to see invocation)
BUILD ERROR: There was a problem linking the app.

Check the console for more information.

**Comment by Shchvova** [comment]
Big Sur is not supported yet. This is to do later

**Comment by zampar** [comment]
Thank you!

Em sex., 18 de set. de 2020 às 10:59, Vlad Svoka <notifications@github.com>
escreveu:

**Comment by StephenTJeffs** [comment]
> Big Sur is not supported yet. This is to do later

Any update on whether Big Sur's supported? I'm running macOS 11.0.1, Xcode 12.3, Solar 2020.3635, but get the following error when attempting to build for iOS SDK 14.3.

Tried relaxing disc access for Corona Simulator, but no effect, so I'm a bit stumped by this one. I can't even navigate to the location specified. Any advice gratefully received:

ERROR: Runtime error
                    /Users/runner/work/corona/corona/platform/resources/iPhonePackageApp.lua:424: unable to generate a unique filename
                    stack traceback:
                    [C]: in function 'tmpname'
                    /Users/runner/work/corona/corona/platform/resources/iPhonePackageApp.lua:424: in function 'runScript'
                    /Users/runner/work/corona/corona/platform/resources/iPhonePackageApp.lua:1215: in function </Users/runner/work/corona/corona/platform/resources/iPhonePackageApp.lua:1135>

**Comment by Shchvova** [comment]
Hello!
So, I’m running Big Sur for a while now, since betas and it is the recommended way of using Solar2D. I don’t think that is version is an issue here, so let’s figure out what is going on. Try enabling verbose debugging with
`defaults write com.coronalabs.Corona_Simulator debugBuildProcess  -int 5` And posting the whole build log. Please use pastebin or something. It seems like there’s some file system issues.
From what you posted it seems that lua built in function `os.tmpname()` fails. I’m hot sure how it can happen...

**Comment by StephenTJeffs** [comment]
Thanks Vlad,

You can see the verbose build log here:

[https://outlook-1.cdn.office.net/assets/mail/file-icon/png/txt_16x16.png]Error in function 'tmpname'.txt<https://ueanorwich-my.sharepoint.com/:t:/g/personal/uct16ebu_uea_ac_uk/ERN1DfWFOGdKsvRHfer_ecgBFmLgnkf0IGq8HUBxDOvmHQ?e=O3F7BN>

Much appreciated,

Stephen.
________________________________

**Comment by scottrules44** [comment]
Closing due to Big Sur and Xcode 12 no longer being relevant (min is Xcode 13)
