### ISSUE TITLE
Appodeal Plugin linker error

### ISSUE THREAD

**Issue by ripps7** [coronalabs/corona#156]
I have Mac Catalina OS, just loaded newest Xcode and am using Solar2D 3617 …
I added only this line to build settings :
[“plugin.appodeal.beta.StartApp”] = {publisherId = “com.coronalabs”}, to my build settings/plugins block

just to test for any errors

and then this is the linking error I get:
was built for newer iOS version (9.0) than being linked (8.0)

in the ‘build for iOS’ panel that pops up when choosing to build app in the simulator I have this 2 settings:
iOS sdk 14.0 beta
iPhone se (2nd generation) / iOS 14.0

**Comment by scottrules44** [comment]
plugin.appodeal.beta is no longer supported so going to go ahead and close this issue
