### ISSUE TITLE
How do I implement the phone keyboard in an App?

### ISSUE THREAD

**Issue by FrankPujo** [coronalabs/corona#159]
In the documentation I couldn't find it so I'm asking here. Do Lua and Solar2d support Apps using a standard phone keyboard? I wanted to create an app with the user typing a number and receiving a specific answer from the app. It's a very simple code so that's not an issue but I don't wether to start creating it or there is no way to have the keyboard. Thank you in advance for your help.

**Comment by FrankPujo** [comment]
I'm sorry, I'm reading this now and I see how unclear I have been. I was looking for both the phone keyboard popping up on the screen, so that the user can actually type a number, and creating a local out of the number he types. So I can do mathematical operations wit that number and print an answer on the screen.

**Comment by mark-sgs** [comment]
This is for issues.  For how to use questions use the forums.

**Comment by Shchvova** [comment]
Indeed. It is better to use [forums](http://forums.solar2d.com/) for such questions. You may want to look into [text field](https://docs.coronalabs.com/api/library/native/newTextField.html).

**Comment by sekodev** [comment]
Have you looked into the forums for the reply?

https://forums.solar2d.com/t/how-to-show-phone-keyboard/352373

**Comment by FrankPujo** [comment]
I see, thank you for the help. I didn't know abou the forums. A friend got me recently into Solar2d. I will look for it, sorry for posting this in the wrong place.
