### ISSUE TITLE
Latest release for Linux is not supported in recent Ubuntu / Pop Revisions

### ISSUE THREAD

**Issue by epistax** [coronalabs/corona#160]
The latest linux release (2020.3618, September 21, 2020) requires libwebkitgtk-3.0.so.0:

/home/brian/CoronaSimulator/CoronaSimulator: error while loading shared libraries: libwebkitgtk-3.0.so.0: cannot open shared object file: No such file or directory

This version of libwebkit has been removed from newer distributions and it is not practical to install. There are dependencies to build this library which are also deprecated, such as "icu-config". The version presently shipping is libwebkit2gtk-4.0-37.

(I tried just creating a link to trick the tool into thinking one version was another, and it seems apparent that they are not API or ABI compatible).

Additional non-detail:
sudo apt install "libwebkitgtk-3.0-0"
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libwebkitgtk-3.0-0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libwebkitgtk-3.0-0' has no installation candidate

**Comment by sekodev** [comment]
I'd suggest using and supporting the actively developed Linux fork, [Solar2DTux](https://github.com/DannyGlover/Solar2DTux).
