### ISSUE TITLE
Build error on iOS when splash screen is inside a folder

### ISSUE THREAD

**Issue by yousaf-shah** [coronalabs/corona#161]
Getting:
```
BUILD ERROR: Build script failed
iOS build failed (1) after 4 seconds
```
If the splash screen file referenced is inside a folder and not in the main project folder alongside build.settings
I've tested with the same file in two places.

This one builds:
```
splashScreen = 
    {
        enable = true,
        image = "driver_splash.png"
    },

```
... and this one does not
```
splashScreen = 
    {
        enable = true,
        image = "logos/driver_splash.png"
    },
```
The same splash screen png is in both places, i'm reporting as the documentation here:
https://docs.coronalabs.com/plugin/CoronaSplashControl/index.html
says that the image can be anywhere in the project.

**Comment by sekodev** [comment]
I guess that's the same issue with #123 . @Shchvova is it something that you can solve easily or should we update the documentation and say "it only works when placed in root folder"?

**Comment by yousaf-shah** [comment]
> I guess that's the same issue with #123 . @Shchvova is it something that you can solve easily or should we update the documentation and say "it only works when placed in root folder"?

Yes I have seen #123 now also - happy either way, fix or documentation depending on how easy it is. FWIW it took me a while to realise what was stopping the build - I tried to fix a dozen other things first before moving the splash screen so if it does not work some kind of error check to warn people this is not going to build would be useful. I am sure the world has bigger problems though ....

**Comment by sekodev** [comment]
Well, it can save time and frustration if fixed in code to match the documentation or, if we place a warning to indicate that you need it to be in the root folder. Either way, this could use a fix.
