### ISSUE TITLE
Timer pause/resume doesn't work on callback

### ISSUE THREAD

**Issue by lifestreamer** [coronalabs/corona#162]
**Describe the bug**
If we pause/resume the timers in timer callbacks (dispatched from enterFrame loop), those timers might already be removed from the runlist in timers enterFrame loop. Because of that they don't get paused/resumed.

**To Reproduce**
```
my_timer = timer.performWithDelay(0, function()
	print("Pausing timer")
	timer.pause(my_timer)
end, -1)
```
It should only print once, but it prints in loop.

**Comment by Shchvova** [comment]
May I ask to take a look, @XeduR?

**Comment by XeduR** [comment]
Of course, @Shchvova .

What version of Solar2D are you using @lifestreamer ?

**Comment by mark-sgs** [comment]
FYI, `pauseAll()` also doesn't work in the same scenario.

**Comment by lifestreamer** [comment]
The changes to timers were done in 2020.3010 and 2020.3011 where pause and resume were changed to support pause/resume all and by tag.

Before that it paused/resumed the timer that was passed in as parameter. Since those changes timer.pause and timer.resume now check the runlist to find the timer.

So the bug exists from version 2020.3011 and till the latest version 2020.3019.

**Comment by XeduR** [comment]
Yeah, this seems to be pretty straightforward. When the enterFrame function gets called, it removes the timer which just triggered from the runlist. The same timer's listener then gets called around 10 lines later, which means that if the listener contains calls to pause the timer, it won't be able to find it from the runlist anymore.

I think I've already found and applied the fix, but I'll test it some more before making a commit. I should be done by tomorrow evening.

**Comment by Shchvova** [comment]
Just a quick hint. To test timer right in simulator, add
```lua
package.preload['timer'] = nil
package.loaded['timer'] = nil
timer = require 'timer'
```
to beginning of your `main.lua`
