### ISSUE TITLE
Live Build on iOS 14 / iPadOS 14 doesn't work

### ISSUE THREAD

**Issue by bogomazon** [coronalabs/corona#163]
The app was built with 2020.3618 14.0 Metal BETA, Live Build doesn't work on iOS 14 (but it's working fine on iOS 12.4.8 and android).

**Comment by Shchvova** [comment]
I wonder if it's because of new privacy stuff... May I ask you to try to add followin entries to build.settings and try again?
```lua
{
 settings = {
	iphone = 
	{
		plist = {
			NSBonjourServices = {"_corona_live._tcp.", },
			NSLocalNetworkUsageDescription = "Solar2D Live Builds are using local network to synchronize the project.",
	},
}
```

**Comment by bogomazon** [comment]
Thank you, it's working with these keys!

**Comment by sekodev** [comment]
@Shchvova should we add this information to [live server docs](https://docs.coronalabs.com/guide/distribution/liveBuild/index.html)?

**Comment by Shchvova** [comment]
@sekodev, no, I'll make it automatic.

**Comment by Shchvova** [comment]
Thanks for reporting & testing, @bogomazon. Next build will have this fixed.
