### ISSUE TITLE
macOS - team id is invalid in the signature

### ISSUE THREAD

**Issue by firemaplegames** [coronalabs/corona#171]
Apple reported these two bugs when submitting the app:

ITMS-90344: Invalid team id in signature - The code signature in bundle 'com.coronalabs.osx.CoronaCards' at 'Akkadia.app/Contents/Frameworks/CoronaCards.framework' has a team identifier value that is different from your team identifier.

ITMS-90344: Invalid team id in signature - The code signature in bundle 'net.playcontrol.ALmixer' at 'Akkadia.app/Contents/Frameworks/CoronaCards.framework/Versions/A/Frameworks/ALmixer.framework' has a team identifier value that is different from your team identifier.

**Comment by Shchvova** [comment]
Is this still happening? May be there's a problem with your certificate? I just tried signing and delivering the app it all works.

**Comment by Shchvova** [comment]
If this still an issue for you, please:

1. Download and Run Corona Simulator, for example [3622](https://github.com/coronalabs/corona/releases/download/3622/Solar2D-macOS-2020.3622.dmg)
2. Make sure to Open corona simulator before running next step
3. Run terminal command 
```sh
zip -v -d /Applications/Corona-3622/Corona\ Simulator.app/Contents/Resources/OSXAppTemplate.zip \*_CodeSignature\*
```
4. Build and upload your project.

**Comment by firemaplegames** [comment]
Hey Vlad!

It certainly could have been an incorrect signature on my end. Not Sure.
But I just what you instructed and it went through successfully. My game is now Waiting for Review.
Thanks!

Joe
