### ISSUE TITLE
Corona binary Solar2D 2020.3620 and Solar2D 2020.3621 does not start

### ISSUE THREAD

**Issue by ysharoiko** [coronalabs/corona#173]
After reinstalling from Corona-2018.3326.msi to corona Solar2D 2020.3620
Running corona Solar2D 2020.3620 in windows 7 64 bit 
gives an error

Ошибка создания контекста архивации для "C:\solar2d\Corona\Corona Simulator.exe". Ошибка в файле манифеста или политики "" в строке . Версия компонента, требуемая для приложения, конфликтует с другой, уже активной версией. Конфликтующие компоненты: Компонент 1: C:\Windows\WinSxS\manifests\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.24483_none_2b200f664577e14b.manifest. Компонент 2: C:\Windows\WinSxS\manifests\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.24483_none_e372d88f30fbb845.manifest.

**Comment by ysharoiko** [comment]
Corona-2020.3582.msi runs normally but cannot sign in with login and password :(

**Comment by sekodev** [comment]
I'm sorry can you share a screenshot of what happens? There should not be a login requirement anymore.

**Comment by sekodev** [comment]
Corona builds are obsolete now. Servers will be taken down in approximately 7 days and it's heavily advised to switch to Solar2D builds.

**Comment by Shchvova** [comment]
Uninstall all Corona/Solar2D you have, reboot computer, try installing latest Solar2D again.

**Comment by ysharoiko** [comment]
Had to reinstall windows. nothing else helped. But now it works.
