### ISSUE TITLE
[macOS]: version numbers of newest release broken

### ISSUE THREAD

**Issue by core-code** [coronalabs/corona#181]
this is a regression. no previous versions had broken version numbers. 

the `CFBundleVersion`  is set to `1.0` and the `CFBundleShortVersionString` is missing completely.

<img width="803" alt="Screenshot 2020-10-22 at 21 59 05" src="https://user-images.githubusercontent.com/1261954/96923751-037a1a00-14b2-11eb-8193-ea35d9a9eb93.png">

**Comment by Shchvova** [comment]
Do you know which version had version strings set?

**Comment by core-code** [comment]
it seems all versions that were released up to april 2020 had version numbers:

2013.2076
2015.2646
2015.2689
2015.2731
2016.2818
2016.2830
2017.3068
2017.3100
2017.3135
2017.3184
2018.3326
2019.3474
2019.3490
2019.3508
2019.3531
2019.3565
2020.3574
2020.3582

**Comment by Shchvova** [comment]
We moved to completely different build system with Solar2D, this seems to fall off. Should be fixed in next build.

**Comment by core-code** [comment]
> Should be fixed in next build.

thanks! i'll verify it once the next build is out

**Comment by core-code** [comment]
i can confirm this is resolved thanks
