### ISSUE TITLE
[Windows Simulator]: runtime bug downloading plug-ins

### ISSUE THREAD

**Issue by rosimosi** [coronalabs/corona#185]
**Describe the bug**
After switching from google v3 billing to the new billing plug-in the simulator will crash with 

15:09:18.905  ERROR: Runtime error
15:09:18.905  D:\a\corona\corona\subrepos\composer\composer.lua:1457: D:\a\corona\corona\platform\resources\init.lua:931: module 'plugin_google_iap_billing' not found:
15:09:18.905  	no field package.preload['plugin_google_iap_billing']

**Target platform and where build was made:**
 - Device: Windows 10
 - Solar Build: 3622 and 3621

**Additional context**
I cleared ~\AppData\Roaming\Corona Labs\Corona Simulator\Plugins and  ~\AppData\Roaming\Solar2DPlugins\Caches

I have also uninstalled/reinstall Solar

After doing this, now NO in-app plugins will download.  Apple, Amazon, etc will give the same error

**Comment by Shchvova** [comment]
This is weird. Can you attach your build.settings?

**Comment by rosimosi** [comment]
build settings attached.  I have also tried to revert to an old build settings we've used for years and it gives similar errors.

[build.zip](https://github.com/coronalabs/corona/files/5445071/build.zip)

**Comment by Shchvova** [comment]
So the issue is `supportedPlatforms`. You can omit that or wait for a fix, where simulator forces plugins to download, regardless of the supportedPlatforms value. Probably coming in today.
