### ISSUE TITLE
Adcolony Bug

### ISSUE THREAD

**Issue by dogan18** [coronalabs/corona#189]
Hi,
I want to integrate adcolony ads into my application, but when I test it on Android, I get the following error:
"You are using an outdated SDK version". Can you help me :)
Best regards

**Comment by Shchvova** [comment]
Yes. I can.

**Comment by Shchvova** [comment]
Hello! I updated AdColony to latest for both iOS and Android (4.4.1/4.3.0). It has minor changes in API, but backwards compatible

**Comment by dogan18** [comment]
Thanks a lot

**Comment by Shchvova** [comment]
Forgot to mention, there're some changes to the privacy/regulations, and news setup for iOS. Everything is in the docs.

**Comment by dogan18** [comment]
Thanks again, the problem seems to be fixed. 
But now I am getting a warning as follows. I wonder how can I fix this situation:
Your app does not meet our GDPR requirements.
