### ISSUE TITLE
Black Screen crash

### ISSUE THREAD

**Issue by ijonesGuy** [coronalabs/corona#190]
Recompiled with the latest version of the SDK  and app launches with just a black screen and following IOS sim error. 
assertion failed: 19H2 18A8394: libxpc.dylib + 51172 [5B766255-3DAE-3096-A090-3974BE256194]: 0x7d. 

Any help would be appreciated.

**Comment by Shchvova** [comment]
Hello. Please provide more information, for example attach build.setting

**Comment by scottrules44** [comment]
Going to go ahead and close this due to a lack of information, usually a black screen with your Solar2D app usually because of a plugin conflict
