### ISSUE TITLE
Cannot receive the registration letter

### ISSUE THREAD

**Issue by DoogSiAnoroc** [coronalabs/corona#191]
https://forums.solar2d.com/
Cannot receive the registration letter

**Comment by Shchvova** [comment]
What domain is your email on?

**Comment by DoogSiAnoroc** [comment]
hi
I don't quite understand the meaning of this sentence
How do I know domain is my email on?

thank you

Vlad Svoka <notifications@github.com> 於 2020年11月6日 週五 下午2:03寫道：

**Comment by Shchvova** [comment]
Domain is the part of email after the `@`

**Comment by DoogSiAnoroc** [comment]
hi
@gmail.com
thank you

Vlad Svoka <notifications@github.com> 於 2020年11月6日 週五 下午3:20寫道：

**Comment by Shchvova** [comment]
Hello. Please, try again. I changed email provider, it should work now.

**Comment by Shchvova** [comment]
If it still doesn't work, please, provide your email (I already know it's on gmail), I'll check if it got to ban list somehow.

**Comment by DoogSiAnoroc** [comment]
hi
it's ok now
very thank you

Vlad Svoka <notifications@github.com> 於 2020年11月10日 週二 上午2:53寫道：
