### ISSUE TITLE
"usesExpansionFile = true" doesn't work on CoronaBuilder

### ISSUE THREAD

**Issue by ChaseTargaryen** [coronalabs/corona#195]
"usesExpansionFile = true" doesn't work on CoronaBuilder.
Simulator build works.

**Comment by ChaseTargaryen** [comment]
As I understand it, CoronaBuillder and Native builds ignore **build.settings**, therefore there's no place that we can request usesExpansionFile = true. Would it be possible to add this as an option to the CoronaBuilder params.lua configuration file? 
@Shchvova

**Comment by Shchvova** [comment]
Corona builder does use `build.settings` to the full extend. There's a bug somewhere. Also, you can use `build.settings` in native as well to set up plugins with gradle targets in Corona group.

**Comment by ChaseTargaryen** [comment]
@Shchvova Thanks for you reply. Another thing is that "neverStripDebugInfo = true" doesn't work on CoronaBuilder either.
I wonder if there is more options in build.settings that don't work on CoronaBuilder.

**Comment by solares** [comment]
@Shchvova 

We're now using CoronaBuilder to automate builds from the command line, and these two issues are blockers for us. Is there any way we can help fix this?

**Comment by solares** [comment]
Thanks @Shchvova, we'll test from our end.
