### ISSUE TITLE
Reconsider more opensource licenses like MIT, otherwise pointless?

### ISSUE THREAD

**Issue by nanjizal** [coronalabs/corona#2]
When facebook released React it released it with all sorts of provisions on the license eventually it realized that opensource expectations are of permisive licenses, and GPL is yesterdays expecations now days Permisive ( perhaps with GPL compatibility ), I think the general expectations are for MIT or similar. MIT is very simple and compatible to use and contribute.

Facebooks 'React' license

https://github.com/facebook/react/blob/master/LICENSE

Modern Game Engines for 2D and 3D, notice there is an expectation among modern game developers use Unity OR something with permisive license:

https://github.com/Kode/Kha/blob/master/license.txt
https://github.com/armory3d/armory/blob/master/LICENSE.md
https://github.com/HeapsIO/heaps/blob/master/LICENSE
https://github.com/openfl/openfl/blob/master/LICENSE.md
https://github.com/HaxeFlixel/flixel/blob/dev/LICENSE.md
https://github.com/openfl/away3d/blob/master/LICENSE.md

Really no point in releasing another 2D engine if it's old school opensource only, there are plenty of good tools that are MIT.

Please note as a Haxe user I have no specific interest in Corona, seems there are already very good solutions that are better licensed - Heaps, NME, OpenFL, Kha to name but a few. But since Haxe compiles to Lua it might be interesting to take a look.  My point is that I think it's a shame to go to effort of cleaning up code for opensourcing and then going halfway, better to release most of it and then charge for components, but it's your choice if you want to attract developers.

**Comment by Shchvova** [comment]
Primary way of using Corona for last 10 years was through Corona Simulator, which is a binary distribution, and absolutely nothing changed to terms of using it. You can still go to [coronalabs.com](https://coronalabs.com/), download a build and use it for making games, building them and distributing in any way you want to.

GPL license is only applied to source code distribution of Corona, which does not affect game developers in any way, but provides a way for people interested in developing a game engine to get involved and contribute to real world game engine.

Dramatic difference between Corona and other products you mentioned is that they do not work same way Corona does: to use React, you link with source code of react, which must be then distributed with non-viral license. To build with Corona you link with commercially licensed free binaries using Corona build system.

**Comment by Exagone313** [comment]
To give another example, if I'm not mistaking, you can get access to Unreal Engine source code for no charge, after signing an agreement, and it uses a proprietary license (you can't share it). I'm rather happy that Corona chose the GPL way.

**Comment by Shchvova** [comment]
Unreal engine does not have a free license. Unreal Engine is proprietary as state of now. You can view source code but using it would require paying royalties to Epic (if you make profit).
With Corona you potentially can use it as GPL licensed or negotiate a proprietary license for the source code.

**However**, primarily Corona engine is not built with source code, this is not a recommended way to use it. For over 9 years Corona Simulator was a way to use Corona, and for a while now it is freely available to make royalty free games. Download it from [coronalabs.com](https://coronalabs.com/). Those binaries are distributed as proprietary software (it is 100% synced both ways with this repo).
And games built with it are proprietary licensed to you.

Enjoy making games!

**Comment by Shchvova** [comment]
Just an update, we reliced this engine under MIT. Not it is fully open source, as well as all first party plugins. Build system is open source too.
Cheers.

**Comment by Destiny-2048** [comment]
> Not it is fully open source, as well as all first party plugins.
Vlad, correct "not" to "now" 😉
