### ISSUE TITLE
add method to get audio position

### ISSUE THREAD

**Issue by KCFindstr** [coronalabs/corona#20]
Hi,

It'll be great if there's an API to get precise playing position from audio. Currently I'm using timers, but I'm afraid they are not precise enough regarding the music being played.

**Comment by super-toki** [comment]
This is an unofficial API, but you can use it.

```
local handle = audio.loadSound(filename)
local ch, src = audio.play( handle, { channel=lowest_ch, loops=loops } )
local position = al.GetSource(src, al.SEC_OFFSET)

```

p.s: Use the forums to find suggestions or solutions. (This is a space for reporting "bugs".)
