### ISSUE TITLE
Android: AdMob rewarded video, Unity Ads mediation issues

### ISSUE THREAD

**Issue by appfamily** [coronalabs/corona#202]
- [x ] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

There are various lingering issues with AdMob that are starting to pile up. 

**Describe the bug**
1. AdMob rewarded video ads on Android lack UI controls, as frequently discussed in Discord and also in [Google-AdMob-Ads-SDK group](https://groups.google.com/g/google-admob-ads-sdk/c/xRHTXuF2RmA/m/npkZLYAoAwAJ). Does not seem to affect other game engines

~~2. AdMob test ads not loading. Using [test ad units](https://developers.google.com/admob/android/test-ads) results in phase failed, isError false when loading the ads. E.g. ad unit id  ca-app-pub-3940256099942544/5224354917 for a rewarded video, despite setting testMode = true in admob.init. Note that this used to work a year or two ago.~~ (resolved, I was setting Google sample ad units **AND** using testMode = true)

3. Unity Ads not working with AdMob mediation. Requests are successful, but no impressions are shown. I've talked to both Unity Ads and AdMob support, they see no errors on their sides (configuration-wise). I've triple-checked ad unit mappings, etc. Note that AppLovin through AdMob mediation works fine, and using the Unity Ads plugin (rather than mediation) for the same ad units works fine.

**To Reproduce**
3. ..

**Target platform and where build was made:**
 - Device: Android Pixel 2
 - OS: Android 11

**Additional context**
I'm open to help in any way with regards to troubleshooting, testing etc.

**whole test project or build.settings**
Please contact me and I can provide full source for apps displaying the issues.

**Comment by Shchvova** [comment]
Hello!
This is super weird. I didn't test moderation, but other users did, with facebook and applovin, this is why I wrote this part in [tutorial](http://docs.coronalabs.com/plugin/admob/index.html#google-admob-mediation-setup). It is tested and works in production right now.
About UI now working, they asked me to submit data from actual working apps where it happens. This is where I couldn't do it, because I don't have any apps. If you could help me out with support that would be wonderful. basically AdMob requested.
They requested Charles log, and ad units. If you send those to me I'll forward them.

About test ads - that is bizzare. I don't have any issues with test ad units. In my build.settings I have:
https://github.com/coronalabs/com.coronalabs-plugin.admob/blob/a932e2d16731821815ed4fe8888aa9f1c40dffd6/src/Corona/build.settings#L20-L29
```lua
	android =
	{
		minSdkVersion = 16,
                applicationChildElements =
                {
                   [[
                       <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID"
                           android:value="ca-app-pub-7897780601981890~1957125968"/>
                   ]],
                },
```

**Comment by appfamily** [comment]
Thanks for quick reply.

Debugging the controls: I would prefer to send you a full production project that you can build, with mediation and everything setup. I believe it would avoid some work on my end as well as back-and-forth if AdMob ask for tweaks etc. Would that be ok?

Mediation issues: Applovin and Facebook work but Alberto_edujoy told me that he too has same issue with Unity Ads. I've [asked in Discord ](https://discord.com/channels/721785436195782677/721785737258860544/783969327099150337) if anyone has successfully used Unity Ads in mediation but got no replies, so I don't know if that means other are successful or just not using mediation through AdMob.

Test ads: I did some digging since it works for you. The problem was that I was using [Google's sample ad units](https://developers.google.com/admob/android/test-ads) **AND** setting testMode = true in admob.init(). If I remove the usage of sample ad units and just set testMode = true then it works for me.

**Comment by appfamily** [comment]
**UI Controls**: Looks like [Solar2d AdMob plugin](https://github.com/coronalabs/com.coronalabs-plugin.admob/blob/master/src/android/plugin/src/main/java/plugin/admob/LuaLoader.java) is using the legacy API for rewarded ads:
- New API: https://developers.google.com/admob/android/rewarded-ads (seems to have been introduced in October 2019)
- Legacy API: https://developers.google.com/admob/android/rewarded-video

I suppose it shouldn't matter but perhaps upgrading is one step to eliminate potential issues

**Comment by appfamily** [comment]
Good news: Rewarded video actually works in a minimal app!

**main.lua**
```
local admob = require( "plugin.admob" )
local adType = "rewardedVideo" -- interstitial / rewardedVideo
local adUnitIds = {}
adUnitIds["interstitial"] = "ca-app-pub-9069033588526716/1925142589"
adUnitIds["rewardedVideo"] = "ca-app-pub-9069033588526716/1575749900"

-- AdMob listener function
local function adListener( event )
    print(event.phase)
    if ( event.phase == "init" or event.phase == "closed" ) then  -- Init ok or ad closed -> load an ad
        admob.load( adType, { adUnitId = adUnitIds[adType] } )
    elseif ( event.phase == "loaded" ) then -- Ad loaded -> show it
        if admob.isLoaded(adType) then
            admob.show(adType)
        end
    end
end

-- Initialize the AdMob plugin
admob.init( adListener, { appId="ca-app-pub-9069033588526716~9448409383", testMode = true } )
```
**config.lua:**
```
application =
{
    content =
    {
        -- Parameters
    }
}
```
**build.settings:**
```
settings = {
     
    orientation = {
        default = "landscapeRight",
        supported = { "landscapeRight", "landscapeLeft" }
    },

    android =
    {
        minSdkVersion = "17",
        usesPermissions =
        {
            "android.permission.INTERNET",
            "com.android.vending.BILLING",
            "android.permission.WRITE_EXTERNAL_STORAGE",
        },
        applicationChildElements =
        {
            [[
                <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID"
                    android:value="ca-app-pub-9069033588526716~9448409383"/> 
            ]],
        },
    },


    plugins =
    {
        ["plugin.admob"] =
        {
            publisherId = "com.coronalabs",
        },

    },
}
```

But how to figure out what causes it to fail in a real project is beyond me :(

**Comment by Shchvova** [comment]
Good catch. At this point I'm willing to try anything. I'll implement RewardedAd

**Comment by appfamily** [comment]
I've spent the whole day trying to minimize the issue - what makes my production app break when the minimal app works? I've looked at composer, immersive mode, status bar etc. 

What I finally find might not make much sense, but if I add a runtime listener and call audio.pause() on applicationSuspend then the minimal project breaks. I.e., add the following to main.lua above:

```
local function onSystemEvent(event)
    if (event.type == "applicationSuspend") then
       audio.pause()
    end
end
Runtime:addEventListener("system", onSystemEvent)
```

That will consistently break the UI. Comment out the audio.pause() and restart the app to make it consistently work again. I noted that sometimes live build restarts did not feel like they properly reflected the changes, so I restarted the app by discarding it in task manager.

Unfortunately, simply commenting out that line in my production code did not resolve the issue. But I hope it can provide a clue for further investigation.

**Comment by appfamily** [comment]
Both of the issues appear to be resolved, thank you Vlad for quick assistance! 

AFAIU Vlad has:
1. Updated the AdMob plugin to use the latest API for rewarded ads (https://developers.google.com/admob/android/rewarded-ads). This bumped AdMob plugin to V9 and resolved missing UI controls as far as I can tell. https://github.com/coronalabs/com.coronalabs-plugin.admob/commit/424ba63951650d0f5d23e4bfce9f1a09ee1151cb

2. Changed how to initialize the AdMob ad units. This bumped AdMob plugin to V10 and resolved Unity Ads mediation. Note that build.settings requires minSdkVersion = 19 for Unity Ads mediation. I've been running an app in production for a few days and can confirm that Unity Ads mediation works.
https://github.com/coronalabs/com.coronalabs-plugin.admob/commit/e5987c3b3b70e4a2ba3de3bff30a9ef65c4079da

To apply these changes, just rebuild your app.
