### ISSUE TITLE
[Framework] pausing/resuming timer causes error

### ISSUE THREAD

**Issue by bugsbycarlin** [coronalabs/corona#207]
- [Yes ] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**Describe the bug**
Calling timer.pauseAll() followed later by timer.resumeAll() causes a nil value error in timer.lua.
Calling timer.pauseAll(), then waiting, then calling timer.resumeAll() causes the following error:
timer.lua:176: attempt to perform arithmetic on field '_pauseTime' (a nil value)

This happens in Corona-3628, but not in Corona 3619. I think it might be related to https://github.com/coronalabs/framework-timer/commit/e7cba674bd5f1f61bf2b4a4c891e7da3f2a72ed3

**To Reproduce**
1. Start some timers
2. Through a keyboard event, call timer.pauseAll()
3. Through another keyboard event, call timer.resumeAll()

**Target platform and where build was made:**
 - Device: [e.g. iPhone6] simulator
 - OS: [e.g. iOS8.1] simulator iOS 14.0

<img width="725" alt="Screen Shot 2020-12-09 at 5 48 27 PM" src="https://user-images.githubusercontent.com/1264898/101704068-8bf45000-3a49-11eb-83ba-c0c5cec92e19.png">

**Comment by bugsbycarlin** [comment]
Thanks much for your time and effort, by the way!

**Comment by Shchvova** [comment]
May I ask for a code snippet to help us reproduce the bug if you have it handy?

**Comment by Shchvova** [comment]
@XeduR may I ask to take a look at it?

**Comment by XeduR** [comment]
@Shchvova Sure.

I already tried, but I couldn't reproduce any issues.

Here's the code that I used. I'd appreciate it if @bugsbycarlin could provide me with a sample project/code that can reliably reproduce this issue, because otherwise I can't really do much.

```lua
local iterations = 100
local t = {}

for i = 1, iterations do
    timer.performWithDelay( math.random(1000,2000), function() print(i) end )
end

local function onKeyEvent( event )
    if event.phase == "down" then
        if event.keyName == "space" then
            timer.pauseAll()
        else
            timer.resumeAll()
        end
    end
    return false
end

Runtime:addEventListener( "key", onKeyEvent )
```

**Comment by daveyang** [comment]
Perhaps changing line 176 in timer.lua to this might get rid of the error?

if (isTag and whatToResume == v._tag and not v._expired and v._pauseTime) or (whatToResume == v and v._pauseTime) then

**Comment by bugsbycarlin** [comment]
It only triggers with a small value for the delay, perhaps just under the frame rate threshold. Here's code for a scene which triggers the bug if run at 30 fps:


local composer = require("composer")
local scene = composer.newScene()

function scene:show(event)

    display.setDefault("background", 1, 1, 1)
 
    if (event.phase == "did") then

      self.paused = false

      Runtime:addEventListener("key", function(event)
        if event.phase == "up" then
          if self.paused == false then
            print("pause")
            self.paused = true
            timer.pauseAll()
          else
            print("resume")
            self.paused = false
            timer.resumeAll()
          end
        end
      end)

      -- the bug only happens if this value is small
      timer.performWithDelay(33, function() 
        print(system.getTimer())
      end, 0)

    end    
end
 
scene:addEventListener("show", scene)
 
return scene
[timer_test.zip](https://github.com/coronalabs/corona/files/5684257/timer_test.zip)

**Comment by daveyang** [comment]
Confirmed that the change I mentioned above fixed this bug. Here's how to test for now:

Copy timer.lua to your code folder and name it myTimer.lua.

Change line 176 to:
if (isTag and whatToResume == v._tag and not v._expired and v._pauseTime) or (whatToResume == v and v._pauseTime) then

Add this line to your timer_test.lua:
local timer = require "myTimer"

Now run it, pause and resume. The error doesn't show up anymore.

**Comment by Shchvova** [comment]
May I ask to create pull request with some sample code to reproduce the issue?

**Comment by daveyang** [comment]
> May I ask to create pull request with some sample code to reproduce the issue?

You can download timer_test.zip above to reproduce the issue.

**Comment by bugsbycarlin** [comment]
Thank you!
