### ISSUE TITLE
[Android]: safe area bug

### ISSUE THREAD

**Issue by Earnes-Tg** [coronalabs/corona#216]
- [ v] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**Describe the bug**
Safe area in Android devices returns 0 as bottom inset.
Unlike in iphone where it takes into consideration that navigation gestures bar
in Android it returns abolute 0 regardless if software navigation keys are shown or navigation gestures bar
in both those cases I expect >0 value

**Target platform and where build was made:**
 - Device: Samsung A12

**whole test project or build.settings**

    local sceneGroup = self.view
    local CENTER = { x = display.contentWidth/2, y = display.contentHeight/2 }
    local H = display.contentHeight
    local W = display.contentWidth

    local greenBG = display.newRect(sceneGroup,CENTER.x,CENTER.y,W,H)
    greenBG:setFillColor(0,0.4,0)

    local topInset, leftInset, bottomInset, rightInset = display.getSafeAreaInsets()

    local blueSafeArea = display.newRect(sceneGroup,CENTER.x,CENTER.y,W,H-topInset-bottomInset)
    blueSafeArea:setFillColor(0,0,0,0)
    blueSafeArea:setStrokeColor(0,0,1)
    blueSafeArea.strokeWidth=8

    local info = display.newText{
        parent = sceneGroup,
        x = CENTER.x,
        y = CENTER.y,
        fontSize=60,
        text="topInset = ".. math.floor(topInset).."\nbottomInset = "..math.floor(bottomInset),
    }

**To Reproduce**
![Untitled](https://user-images.githubusercontent.com/4797458/105829932-981e7780-5fcd-11eb-8216-0823e7c0bf72.png)

**Comment by Earnes-Tg** [comment]
In the example above:
topInset is correctly 50 because there is a notch
At bottom there is no notch so bottom inset is presumably zero
But round corners and the presence of software navigation keys should be taken into account.

As a work around , an additional API to get navbar height might help avoid those situations.

**Comment by Earnes-Tg** [comment]
Per this documentation page 

https://docs.coronalabs.com/api/library/display/safeActualContentHeight.html

The "safe area" is the rectangular region where it's safe to place important UI elements, ensuring that they are not obscured by status bars, device aspects like a sensor bar or rounded corners, **_software buttons_**.

**Comment by sekodev** [comment]
I believe this was listed earlier in #46 . @Shchvova is this hard to fix?

**Comment by Earnes-Tg** [comment]
> I believe this was listed earlier in #46 . @Shchvova is this hard to fix?

Thanks, I added what I've found there.

**Comment by Shchvova** [comment]
Closed as a duplicate.

**Comment by Earnes-Tg** [comment]
> Closed as a duplicate.

Thanks Vlad, let's continue the conversation at #46 , I added a comment about a possible solution.
