### ISSUE TITLE
Is this still an issue after release [2020.3619](https://github.com/coronalabs/corona/releases/tag/3619)?

### ISSUE THREAD

**Issue by Storeynathaniel** [coronalabs/corona#217]
Is this still an issue after release [2020.3619](https://github.com/coronalabs/corona/releases/tag/3619)?

_Originally posted by @sekodev in https://github.com/coronalabs/corona/issues/46#issuecomment-704160803_

**Comment by Storeynathaniel** [comment]
- [mmm #46

**Comment by Shchvova** [comment]
Please stop opening issues. If you want to discuss something, write a comment in existing issue or use our discord to ask questions https://discord.gg/WMtCemc

If you're trying to ask if safeAreaApis are still broken on android - yes. They are.
