### ISSUE TITLE
Make on Linux (Branch Gradle!)

### ISSUE THREAD

**Issue by Larpoux** [coronalabs/corona#22]
The command line 👍 
```sh
cd corona/platform/linux
make
```

give the following error 👍 
----------Building project:[ linux_rtt - Debug ]----------
gcc -c  "../../external/tremor/Tremor/dsp.c" -g3 -O0 -Wall -DRtt_LUA_COMPILER -DLUA_DL_DLOPEN -DwxUSE_MEDIACTRL=1 -DwxUSE_WEBVIEW=1 -D__WXGTK__ -DHAVE_SSIZE_T -DwxUSE_XTEST -DwxHAS_INOTIFY -DwxUSE_SELECT_DISPATCHER -DwxUSE_LIBMSPACK -DWXWIN_COMPATIBILITY_3_0 -DwxUSE_TASKBARBUTTON -DwxUSE_DBGHELP -DwxUSE_WINRT -DwxUSE_PRIVATE_FONTS -DwxUSE_ACTIVITYINDICATOR -DwxUSE_ADDREMOVECTRL -DwxUSE_UNSAFE_WXSTRING_CONV -DwxUSE_STD_CONTAINERS_COMPATIBLY -DwxUSE_SECRETSTORE -DwxUSE_GLCANVAS -D_DEBUG -DRtt_LINUX_ENV -DRtt_EXPORT= -DFT2_BUILD_LIBRARY -DALMIXER_COMPILE_WITHOUT_SDL -DSOUND_SUPPORTS_WAV -DSOUND_SUPPORTS_MPG123 -DSOUND_SUPPORTS_OGG -DLINUX_LIB -DOPT_GENERIC -DHAVE_STRERROR -DNO_REAL -DENABLE_ALMIXER_THREADS  -o ./Debug/up_up_external_tremor_Tremor_dsp.c.o -I. -I. -I../../external/lua-5.1.3/src -I../../librtt -I../ -I../../external/rsa -I../../plugins/shared -I../../librtt/Corona -I../../external/Box2D -I../../external/ALmixer -I../../external/ALmixer/Isolated -I../../external/openal-soft-1.12.854/include/AL -I../../external/LuaHashMap -I../../external/b2Separator-cpp -I../../external/luafilesystem\src -I../../external/opengl -I../shared -I../../external/smoothpolygon -I../../external/freetype-2.9/include -I../../external/ALmixer -I../../external/ALmixer/Isolated -I../../external/mpg123-1.13.1/src/libmpg123 -I../../external/luafilesystem/src -I../../external/tremor/Tremor -I../../modules/simulator -I../../librtt/Core -I./curl-7.61.0/include -I./wx/include -I../android -I../../external/hmac 
In file included from ../../external/tremor/Tremor/dsp.c:20:
In file included from ../../external/tremor/Tremor/mdct.h:22:
../../external/tremor/Tremor/misc.h:25:11: fatal error: 'endian.h' file not found
#       include <endian.h>
                ^~~~~~~~~~
1 error generated.
make[1]: *** [Debug/up_up_external_tremor_Tremor_dsp.c.o] Error 1
make: *** [All] Error 2

**Comment by Shchvova** [comment]
Try `./build_template.sh` on linux, as per it's readme. Also, you have to run it on macOS with Docker installed.
If you want to build it on Linux natively, use `./build_native_linux.sh`.
You may want to comment out files referring to raspbian, in build_temlate_linux.sh though.
See coronalabs/submodule-platform-linux#1
