### ISSUE TITLE
Thanks Vlad,

### ISSUE THREAD

**Issue by Storeynathaniel** [coronalabs/corona#222]
Thanks Vlad,
True `getInsets(Type.navigationBars ())`is from API 30,
from API 20 to 30 it's `getSystemWindowInsetBottom()`

Also regarding "touch one everything crumbles", that's why I suggested maybe adding a new API that merely returns the value of `getSystemWindowInsetBottom()` , those who want to take the bottom software bars into account call it.

_Originally posted by @Earnes-Tg in https://github.com/coronalabs/corona/issues/46#issuecomment-773028567_

**Comment by Shchvova** [comment]
Please use comments to the issue on the GitHub web page.
