### ISSUE TITLE
[ANDROID]: ADMOB Simple Banners doesn't show when the application open a second time

### ISSUE THREAD

**Issue by llugato** [coronalabs/corona#226]
- [X] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**Describe the bug**
The first time that I open the application, the admob banner are showed as expected, but in the second time, the event.phase == “init” doesn’t is called in the listener and the .isLoaded give me a error : “ERROR: admob.isLoaded(adType [, options]), You must wait for the ‘init’ event before calling other API functions”

When I force the application to quit, the app can show the banner. Maybe there’s a cache, but I can’t check if the cache exist and If I try to force the admob.init() I has errors inform me that I can’t use admob.init()

**To Reproduce**
1. Open the application
2. See if the banner are showed 
3. Exit the a application
4. Open the application again an the banner doesn't show anymore until you kill the application from memory of the android

**Target platform and where build was made:**
 - Device: [Any Android device]
 - OS: [Android 8, 9]

**Additional context**

**whole test project or build.settings**
I created a topic in the forum to explain the error and put a zip with a code to debug the problem.
https://forums.solar2d.com/t/admob-show-banner-doesnt-work-after-exit-and-restart-app/352935/11

**Comment by appfamily** [comment]
Sounds like similar observations that I had in #202

**Comment by llugato** [comment]
@Shchvova can you close the issue please:

**To solve the problem :**
I'm passing a erroneous AD_UNT_ID when using admob.load( "banner", tableParameters):

**NOTE:**
When I tried to use ADMOB with iOS, you got error and the banner doesn't show if you pass the testMode parameter 
**Android :**
tableParameters = {adUnitId=AD_UNT_ID, testMode=true, childSafe=true, designedForFamilies=true, hasUserConsent=false}
admob.load( "banner", tableParameters)

**iOS :**
tableParameters = {adUnitId=AD_UNT_ID, childSafe=true, designedForFamilies=true, hasUserConsent=false}
admob.load( "banner", tableParameters)
