### ISSUE TITLE
Audio not playing on some iphones using built-in speakers

### ISSUE THREAD

**Issue by deadpandodo** [coronalabs/corona#227]
As stated in this thread of the forums : 
https://forums.solar2d.com/t/sound-only-in-headphones-some-iphones/352015/4

**Describe the bug**
For some reasons, audio does not play at all on some iphones using the built-in speakers
It does work perfectly with headphones or over bluetooth.
I do own one of those devices (iphone 11 pro), on which the sound works perfectly with other apps.
I ran the audio sample app, and absolutely no sound comes out.
It does work perfectly on the simulator as well.

**To Reproduce**
1. build the audio sample app for ios
2. install on device
3. try to play a sound

**Target platform and where build was made:**
 - Device: iphone 11 pro
 - OS: 14.3 (Idem on 14.4)
 - Solar : Version 2021.3637 (2021.2.3)

**Additional context**
It seems like it does not happen on all iphone devices (or i believe someone would have noticed already).
I am the lucky owner of a device that does not work as it should, so don't hesitate to ping me if you need information/test.

**whole test project or build.settings**
Just the audio sample app is enough to test.

**Comment by Shchvova** [comment]
Just to make sure, did you try mute and volume controls?
Solar2D won't play sounds if device mute switch is on.

**Comment by deadpandodo** [comment]
Hello Vlad,
Thanks for your help !
Ok, my bad, my phone is always on silent, and that is definitely the reason, it works perfectly now...
But so it means that it is impossible to play sounds if the phone is on silent mode ? I checked other apps that don't seem to have any problem to do so (Spotify, Chess Tactics, Radio France, etc.). It this a limitation of Solar2d ?
Is there any way to check if the user is on silent mode ? (so at least we could inform the user about the fact that he needs to switch sound mode).
Maybe it would make sense to add a Gotcha to the audio.play() API page about this, so others don't run into the same issue.

**Comment by Shchvova** [comment]
This is a long standing debate on how sound should behave. According to Apple, if device is on mute, only explicit sound playbacks should work, like when user asks to play a song in Spotify. If you notice, even videos in Safari would start muted if you have your device on mute.
You can try experimenting with this code:
```lua
audio.setSessionProperty(audio.MixMode, audio.PlayAndRecordMixMode)
```

Other Modes are:
* `AmbientMixMode`
* `SoloAmbientMixMode`
* `MediaPlaybackMixMode`
* `RecordAudioMixMode`
* `PlayAndRecordMixMode`
* `AudioProcessingMixMode`

and other properties are:
* `ActiveMode`
* `MixMode`
* `OverrideMixWithOthers`
* `OtherAudioIsPlaying`
* `OtherMixableAudioShouldDuck`
