### ISSUE TITLE
build.sh on MacOS

### ISSUE THREAD

**Issue by Larpoux** [coronalabs/corona#23]
The following command lines on MacOS 👍 
```sh
cd corona/subrepos/enterprise
./build.sh
```

gives the following error 👎 

> CLEANING java files...
+ ant clean
Buildfile: /Users/larpoux/projmac/corona/platform/android/sdk/build.xml

BUILD FAILED
/Users/larpoux/projmac/corona/platform/android/sdk/build.xml:49: sdk.dir is missing. Make sure to generate local.properties using 'android update project' or to inject it through an env var

**Comment by Shchvova** [comment]
You have to have android SDK installed and set up to do that, and variables set to point to them:
```sh
export ANDROID_SDK=~/Android/android-sdk-mac_86
export ANDROID_NDK=~/Android/android-ndk-r10d
```
should help.

 Also, this is more of internal script to create CI builds. Doing something like

**Comment by Larpoux** [comment]
Of course I have those environment variables setup !
```sh
$echo $ANDROID_SDK
/Users/larpoux/android-sdk-macosx
$echo $ANDROID_NDK
/Users/larpoux/android-ndk-r19c
$

**Comment by Larpoux** [comment]
OK this is an internal script.
But I ask you seriously how can I build the Corona software from sources:

- on MacOS
- on Linux
- on Windows

**Comment by Shchvova** [comment]
Look, our build servers run on macOS. It really doesn't worth the effort to make them portable. It depends which platform code you're trying to build.
* Windows builds only on Windows
* Linux, on macOS (with docker) and Linux
* iOS, tvOS, macOS - on macOS only
* Android on Windows and macOS. I just merged `gradle` branch into master, so check out master, open platform/android with Android Studio or IDEA, import gradle project and you're all set. Alternatively, use command line `./gradlew assemble` to build corona app which is in `platform/test/assets2`.
