### ISSUE TITLE
PLUGIN: google.iap.billing.* Deadline date to update to use the latest version 3, alert from Google Play

### ISSUE THREAD

**Issue by jajern** [coronalabs/corona#235]
I updated an app today on the Google Play store and received a waring that the billing version was not the latest required one.

There is a deadline date of November 1, 2021.

Pasting warning below, note I am using plugin: google.iap.billing.*

Warning
We've detected that this app is using an old version of Google Play Billing. By November 1, 2021, all app updates must use Billing Library version 3 or newer. Update to Billing Library 3 before this date. Learn More about Billing Library 3.
https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html

**Comment by Shchvova** [comment]
Hello!
Please verify that you're using this plugin in the `build.settings`: https://docs.coronalabs.com/plugin/google-iap-billing/
It uses the latest version of Google IAP billing client. It should not give the warning

**Comment by elpida-v** [comment]
We are now using [plugin.google.iap.v3] with IAP Badger. Do we just need to replace with [plugin.google.iap.billing] and everything will work?

**Comment by Shchvova** [comment]
You replace it in build settings. Should continue working.

**Comment by jajern** [comment]
Thank you! I believe this may have been my error.
