### ISSUE TITLE
[iOS]: Game Center plugin allows to change orientation of a landscape-only-app to portrait

### ISSUE THREAD

**Issue by OutlineDev** [coronalabs/corona#239]
A landscape-only-app can be turned to portrait orientation while the Game Center View is visible. If you close the GC-view in portrait the underlaying app is cropped.

1. Open GC in landscape-only app
2. Turn device to portrait
3. Close GC-view

 - Device: iPhone SE 2nd generation
 - OS: iOS 14.4.2

Doesn't happen the other way around, portrait-only-app is locked to portrait while in GC.

**Comment by OutlineDev** [comment]
Also happens in iOS 15.

**Comment by scottrules44** [comment]
Closing issue, fixed with both plugins with 3655+
