### ISSUE TITLE
corona/platform/mac/build.sh

### ISSUE THREAD

**Issue by Larpoux** [coronalabs/corona#24]
```sh
cd corona/platform/mac
./build.sh
```
gives the following error (but perhaps this is again an internal script who must not be used ?):

Build system information
warning: ignoring duplicated output file: '/Users/larpoux/projmac/corona/platform/mac/build/Release/Corona Simulator.app/Contents/Resources/AppSettings.lua' in shell script build phase 'Run script (write AppSettings: customBuildID, buildBucket, etc if defined)'. This warning represents an extremely serious project misconfiguration and will likely cause some shell scripts in your project to be skipped entirely, leading to other build failures or missing files in the build directory. This will be a hard error in the future. (in target 'rttplayer')

**Comment by Shchvova** [comment]
Please, use `ratatouille.xcodeproj` project for macOS builds, `rttplayer` target, as readme suggests.
