### ISSUE TITLE
[Mac Simulator]: captureScreen exits simulator on Mac

### ISSUE THREAD

**Issue by agilala** [coronalabs/corona#240]
Calling display.captureScreen() exits simulator on Mac. It works fine on Windows.

At times display.captureScreen() works as expected at other times it fails, so it may take to call it several times for simulator to exit.

**Comment by scottrules44** [comment]
Been running this demo for an hour (also tried setting param to true to save to library ) and could not get a crash on Mac. Assuming this has been patched if you can attach a demo project of this happening will reopen. I am using the latest version(3666).

`-- Fill the screen with a green rectangle
local rect = display.newRect( 0, 0, display.contentWidth, display.contentHeight )
rect:setFillColor( 0, 1, 0.2 )

-- Draw a circle on the screen
local circle = display.newCircle( 155, 100, 36 )
circle:setFillColor( 1, 1, 1, 0.6 )

local function captureOnEvent()
		print( "Capture" )
    -- Capture the screen
    local screenCap = display.captureScreen( )

    -- Remove the object from the screen
    screenCap:removeSelf()

end

timer.performWithDelay( 4000, captureOnEvent, 0 )
`
