### ISSUE TITLE
Debug console does not open in Windows 10

### ISSUE THREAD

**Issue by Fitzbratchet** [coronalabs/corona#246]
I've recently picked up developing my game on a windows device after working in Corona for years on Mac. On mac, the console seemed to vanish every few days or so, but I could just reload the project and it would come back.

On Windows today I noticed the console was gone. I tried reloading the project. I tried opening the console from the view menu. I tried restarting the computer. Nothing. 

I haven't updated anything since the last time I had access to the console, so I don't know what could have happened. I'm running Corona version 3641

I did a search on the forums and found: https://forums.solar2d.com/t/solar2d-console-not-showing-on-windows-10/352233
The solution to this thread suggests installing VS code and MS build tools. I don't use visual studio or MS build. Do I need to download them to make Corona work properly? Will a future update of Corona fix this problem?

I can't continue coding without a debug console.

**Comment by Shchvova** [comment]
Try opening `C:\Program Files (x86)\Corona Labs\Corona` in Explorer and starting `Corona.Console.exe`
If it works, it should start the Console, and bring up Open File dialong. Paste `C:\Program Files (x86)\Corona Labs\Corona\Corona.Shell.exe` in it. In another open file dialog open your main.lua project.
This is a test to see which part is broken..

**Comment by Fitzbratchet** [comment]
When I try to run it, it acts like it is loading (spinning circle mouse cursor) but then nothing opens.

**Comment by Fitzbratchet** [comment]
I noticed a windows update that seemed to be incomplete and ran it again. The console is opening now. Thanks for your help.
