### ISSUE TITLE
media.playVideo listener does not fire

### ISSUE THREAD

**Issue by personalnadir** [coronalabs/corona#250]
- [ x] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**Describe the bug**
media.playerVideo's listener is not called.

**To Reproduce**
1. Invoke media.play("video file", function() print ("Done") end)

**Target platform and where build was made:**
 - Device: Corona Simulator 2021.3642, iPhone XS
 - OS: 10.15.7 

**Additional context**
I have tried both mp4 and mov files. The videos play fine, but the callback never seems to fire

**whole test project or build.settings**

[media.play.callback.zip](https://github.com/coronalabs/corona/files/6434442/media.play.callback.zip)

**Comment by sekodev** [comment]
Looking at the [syntax](https://docs.coronalabs.com/api/library/media/playVideo.html#syntax), I see `showControls` is required in the call. Is it possible that's causing the issue?

`media.playVideo( "movie.m4v", true, onComplete )`

**Comment by Shchvova** [comment]
Does it work with it? :)

**Comment by personalnadir** [comment]
@sekodev You are right! I missed that when simplifying from my original code. Reviewing the code I can see the actual issue I had was that the listener does not fire if the baseSource is set to system.ResourcesDirectory. In my case that was in there because I was thoughtlessly changing where the videos were loaded from. I guess it might still be worth investigating as it could cause issues when programmatically switching were a video is loaded from

**Comment by scottrules44** [comment]
Going to go ahead and close this issue, since the docs state that showControls is required and 

`media.playVideo("small.mp4",false, function()
	print ("Done")
	display.newCircle(10,10,1000)
end)`

or 

`media.playVideo("small.mp4",true, function()
	print ("Done")
	display.newCircle(10,10,1000)
end)`

both seem to work :)
