### ISSUE TITLE
Install failed no matching abis

### ISSUE THREAD

**Issue by Larpoux** [coronalabs/corona#26]
When trying to execute the Corona HelloWorld Demo (with a Corona Simulator build) and run on an Android Simulator we get this error message 👎 
```
Installing and running HelloWorld on Android SDK built for x86
46837 KB/s (7882444 bytes in 0.164s)
ERROR: Failure [INSTALLFAILEDNOMATCHINGABIS: Failed to extract native libraries, res=-113] Error found during installation!
```

This bug is possibly tied with a similar bug that we have when building a Native Plugin for Android : the directory /Applications/Corona/Native/Corona/android/lib/Corona/libs contains only : 
- armeabi-v7a

and does not contain the following libraries : 
- arm64-v8a
- x86
- x86-64

**Comment by Shchvova** [comment]
Currently released build system is only armv7. If you want to take use of x64 build use build 3502 or later. You can download a build, including native templates in our [forums](https://forums.coronalabs.com/topic/75790-update-build-3502-handling-bugs-with-android-x64-and-target-sdk-28/).
