### ISSUE TITLE
Android: Camera problems (tiny controls + misc)

### ISSUE THREAD

**Issue by appfamily** [coronalabs/corona#274]
When trying to capture images with the camera, the controls are tiny:
![c1](https://user-images.githubusercontent.com/9742676/131464327-f84b93e1-16e2-430c-92f0-c82db173ebbe.jpg)

Other anomalies include:
- There is some horizontal stretching while viewing the screen before taking capture. Maybe due to the tiny controls, i.e. the preview stretches to fill screen?
- With the camera test app, when you capture an image it is very zoomed in (In my own app, I do not observe the zoomed in capture.)
![c2](https://user-images.githubusercontent.com/9742676/131464864-372aa9da-c9fe-43bf-b964-5b326c411af3.png)

**To Reproduce**
Run the camera test app from #258 

**Target platform and where build was made:**
 - Solar2d version 2021.3652
 - Device: Android Pixel 2 & Pixel 4a
 - OS: 11

**Comment by appfamily** [comment]
In a much older build (2020.3582) where I access the camera I had a 'proper' camera UI, with additional controls for flash, zoom etc.

![Screenshot_20210903-092854](https://user-images.githubusercontent.com/9742676/131967624-86432dc7-d176-40e9-b9cd-1118c55298ea.png)

**Comment by scottrules44** [comment]
This has been patched with 3655+, the default camera pops up for photos

**Comment by appfamily** [comment]
**Build: 2021.3655**

App crashes as soon as the camera opens (using the minimized test app from the forum):

```
09-21 10:42:27.191 28373 28373 W CAM_ActivityUiStartup: CameraActivityController failed!
09-21 10:42:27.191 28373 28373 W CAM_ActivityUiStartup: java.lang.IllegalStateException: GCA not granted write permission to content://se.appfamily.puzzle.insects.free.files/cache/Picture1.jpg, the specified output in intent: Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.google.android.GoogleCamera/com.android.camera.activity.CaptureActivity clip={text/uri-list {...}} (has extras) }.
```

**Comment by appfamily** [comment]
Tested the sample you referred to, as suspected it also crashes out as soon as the camera opens.

**Comment by XeduR** [comment]
@scottrules44 

You can download the minimal camera sample app from here: [Camera Test.zip](https://github.com/coronalabs/corona/files/7210787/Camera.Test.zip)
 
 As you can see, Android has the following build settings:
```
	android =
	{
		usesPermissions =
		{
			"android.permission.INTERNET",
			"android.permission.CAMERA",
			"android.permission.WRITE_EXTERNAL_STORAGE",
		},
	},
```

The code should be self-explanatory. You can just build for Android and try it out.

**Comment by scottrules44** [comment]
I tried it out on my Nokia android 11 device and it's too minimal, you need to request native.showPopup( "requestAppPermission" ,

`local permissionsToRequest = nil
			local rationaleTitleMessage = "media.capturePhoto() needs permissions!"
			local rationaleMessage = nil
			if system.getInfo( "platformName" ) == "Android" then
				-- On Android, we also need the Storage permission to use media.capturePhoto().
				permissionsToRequest = { "Camera", "Storage" }
				rationaleMessage = "Camera sample needs Camera and Storage permission to use media.capturePhoto()!"
			else
				permissionsToRequest = { "Camera" }
				rationaleMessage = "Camera sample needs the Camera permission to access the camera!"
			end

			-- Make the actual request from the user.
			native.showPopup( "requestAppPermission", {
					appPermission = permissionsToRequest,
					urgency = "Normal",
					rationaleTitle = rationaleTitleMessage,
					rationaleDescription = rationaleMessage,
					listener = permissionsListener,
				} )`

As for the "GCA not granted write permission" lets shift the conversation over to #258
