### ISSUE TITLE
Build fails with empty App and GPGSv2 plugin

### ISSUE THREAD

**Issue by Earnes-Tg** [coronalabs/corona#278]
Building an empty project ( attached ) with gpgsV2 fails. 

Building on: macOS
Building for: Android

Sep 17 16:43:31.269 Excluding specified files from build: 
                       excluding: LaunchScreen.storyboardc
                       excluding: Icon.png
                       excluding: Icon-*dpi.png
                       excluding: Images.xcassets
                    
                   =>  Error: commons-logging defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]
                    
                    => Error: httpclient defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]
                    
                       Explanation for issues of type "DuplicatePlatformClasses":
                       There are a number of libraries that duplicate not just functionality of
                       the Android platform but using the exact same class names as the ones
                       provided in Android -- for example the apache http classes. This can lead
                       to unexpected crashes.
                    
                       To solve this, you need to either find a newer version of the library which
                       no longer has this problem, or to repackage the library (and all of its
                       dependencies) using something like the jarjar tool, or finally, rewriting
                       the code to use different APIs (for example, for http code, consider using
                       HttpUrlConnection or a library like okhttp).
                    
                    2 errors, 0 warnings
                    
                    FAILURE: Build failed with an exception.
                    
                    * What went wrong:
                    Execution failed for task ':App:lintVitalRelease'.
                    > Lint found fatal errors while assembling a release target.
                      
                      To proceed, either fix the issues identified by lint, or modify your build script as follows:
                      ...
                      android {
                          lintOptions {
                              checkReleaseBuilds false
                              // Or, if you prefer, you can continue to check for errors in release builds,
                              // but continue the build even when errors are found:
                              abortOnError false
                          }
                      }
                      ...
                    
                    * Try:
                    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                    

                    * Get more help at https://help.gradle.org
                    
                    BUILD FAILED in 31s
Android build failed (256) after 35 seconds
ERROR: Build Failed: Error code: 256

[testGPGS.zip](https://github.com/coronalabs/corona/files/7186294/testGPGS.zip)

Tested using 2021.3637

**Comment by scottrules44** [comment]
This should have been fixed already

**Comment by scottrules44** [comment]
I am going to close this due to fact this issue has been fixed
