### ISSUE TITLE
Google Play Services Library Error

### ISSUE THREAD

**Issue by tariqkhatib** [coronalabs/corona#281]
![Untitled](https://user-images.githubusercontent.com/9401112/134775404-df672162-7aaf-4753-9928-eb7aab0b7f9d.png)

after the recent solar2d updates (Solar2D 2021.3656) users are unable to subscribe to onesignal

please see attached image

**Comment by Shchvova** [comment]
Please check if this is fixed now. Thanks!

**Comment by tariqkhatib** [comment]
My Recent app works perfectly with one signal on Android and iOS, using build 2022.3668
