### ISSUE TITLE
[PLATFORM]: runtime bug

### ISSUE THREAD

**Issue by nobstudio** [coronalabs/corona#296]
- [ ] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.
- [ ] https://forums.solar2d.com/t/audio-oncomplete-bug-caused-crash/354132/2

**Describe the bug**
Hi, I can confirm there is a bug with audio.play onComplete, it caused crashes on some android phones. Even if the function is empty, it will crash. It only happens to 10% of the players, I use same phone model, same android 11, couldn't reproduce the bug.
My game on GooglePlay had 800+ crashes in 6 days, after I removed onComplete for all audio, 0 crash.

**To Reproduce**
use a short 0.3 second sound, and let the simulator run for a while(30 sec to 10 minutes). On windows, the simulator will force quit with this error **The stdin connection has closed.**
```
mySound = audio.loadSound("mySound.wav")
        soundTesting = function()
end
function checkSound ()
	for j = 1, 30 do
		audio.play(mySound , { onComplete=soundTesting })
	end
end	
Runtime:addEventListener( "enterFrame", checkSound )
```

**Target platform and where build was made:**
 - Device: Android, windows simulator
 - OS: android 9,10,11

**Additional context**
The error from googleplay is 
```
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR)
libcorona.so!libcorona.so (offset 0x37e000)
Rtt::ALmixerSoundCompletionEvent::~ALmixerSoundCompletionEvent()) (SourceCode: /Users/runner/work/corona/corona/librtt/Rtt_PlatformOpenALPlayer.cpp:76)
```

**Comment by alirezapoorslt** [comment]
Why you need to play a sound 30 times in each frame?

**Comment by nobstudio** [comment]
> Why you need to play a sound 30 times in each frame?

to speed up testing. 30 times each frame to stress test and reproduce this error in a short period of time.
For my game, only up to 10 audio channels are used at all times, and I can't get this error on my device or windows simulator at all. But for some players, they have this error every few minutes, not sure what's wrong with their devices.

**Comment by sekodev** [comment]
Is it possible issue #19 and this one is related?
