### ISSUE TITLE
Plugins download interval (feature request)

### ISSUE THREAD

**Issue by IlSui** [coronalabs/corona#298]
Hi,
In this moment the simulator downloads all plugins every 10 minutes, and this means almost 50 times in a working day.
I thhink that once a day or on demand would be the best solution, so can we have an option to change this interval manually? It could be addressed in the Simulator window.

**Comment by Shchvova** [comment]
It should hit cache if no plugin was updated.

**Comment by XeduR** [comment]
@Shchvova The Simulator does take a long while to process something the first time that it is started, as well as after restarting it following a certain period of time.

@IlSui, I and a few others have thought it might have something to do with the plugins as it never occurs with new projects, or projects without any plugins.

![](https://cdn.discordapp.com/attachments/808290972714401792/908319892388864020/unknown.png)

**Comment by scottrules44** [comment]
@IlSui the load time might be with my Iron Source Adapters or other plugins with URLs in build settings
I am working currently working on getting the Iron Source Adapters into the Corona Cache/Collector

**Comment by Shchvova** [comment]
I think I will change code to make updates way smarter. 
- always update if plugins table is changed
- otherwise do updates with registry setting defaulting to daily

Plugins are always updated when build is made, so fresh plugins there are guaranteed, not related to simulator plugins
