### ISSUE TITLE
print(os.date("%s")) crashes the sim

### ISSUE THREAD

**Issue by mark-sgs** [coronalabs/corona#301]
Place `print(os.date("%s")) crashes the sim` in main.lua and it crashes.  It should raise an error at the very least,

**Comment by XeduR** [comment]
This quite a strange crash indeed.

It also doesn't seem to crash a built project. For instance, you can run the same code over at https://www.solar2dplayground.com/ and it'll just print "%s".

**Comment by scottrules44** [comment]
Is this only happening on Windows? I just tried on my Mac, cannot reproduce

**Comment by XeduR** [comment]
Yeah, we're both using Solar2D Simulator on Windows.

**Comment by scottrules44** [comment]
This is fixed with 2022.3685+
