### ISSUE TITLE
[Android]: Appsflyer don't send or don't receive data

### ISSUE THREAD

**Issue by tltgamedesign** [coronalabs/corona#306]
I tried to use Appsflyer plugin.

Print data in listener return normal / expected callbacks from appsflyer.init and logEvent.
getVersion return Appsflyer SDK version 6.2.3. I suspect that problem may be in outdated version. Actual Appsflyer SDK version is 6.4.2.

I don't receive data in appsflyer console. 
SDK Integration tests in appsflyer console return nothing.
I don't know where is problem.

Seems like plugin working normally. But for some reason Appsflyer can't receive or accept data that plugin sends.

Is there a sample project or succesfull case of Appsflyer integration?
Is there a full integration guide for Appsflyer is Solar2D?

my build.settings:
[build.zip](https://github.com/coronalabs/corona/files/7569986/build.zip)

**Comment by tltgamedesign** [comment]
Plugin need to be updated to latest Appsflyer SDK version (6.5.2).
Current SDK version 6.2.3 is outdated (March 2021).
Project with the current version of the plugin does not pass the Appsflyer SDK integration test. It does not track non-organic installs.

[There was a similar issue in this thread on this forum a few years ago](https://forums.solar2d.com/t/appsflyer-plugin-has-older-sdk-of-appsflyer/149782)

**Comment by scottrules44** [comment]
it's been updated 
https://github.com/coronalabs/com.coronalabs-plugin.appsflyer/releases/tag/v7
