### ISSUE TITLE
AppLovin plugin needs to be updated so we can set the age restricted user flag

### ISSUE THREAD

**Issue by cravecreative** [coronalabs/corona#312]
The AppLovin plugin needs to be updated so we can set the age restricted user flag to ensure Google Play policy compliance. Below are links I was sent by AppLovin on implementing flag.

Android: https://dash.applovin.com/documentation/mediation/android/getting-started/privacy#children-data 2
iOS: https://dash.applovin.com/documentation/mediation/ios/getting-started/privacy#children-data

**Comment by agramonte** [comment]
Thank you for opening up a defect. Fixing it now and will check it in.

**Comment by agramonte** [comment]
Created pull request here:
https://github.com/coronalabs/com.coronalabs-plugin.applovin/pull/1

**Comment by scottrules44** [comment]
Added https://docs.coronalabs.com/plugin/applovin/setIsAgeRestrictedUser.html
