### ISSUE TITLE
[iOS] Support multiple app icons in a binary

### ISSUE THREAD

**Issue by rosimosi** [coronalabs/corona#321]
In order to take advantage of the new Product Page Optimization on the App Store we must be able to submit multiple app icons in one binary.  It is unclear if Solar can already do this and we just need documentation, or if this would be a new feature request.

https://developer.apple.com/app-store/product-page-optimization/

**Comment by Shchvova** [comment]
We already use xcassets so it should be possible using current build. I can look into this next year.

**Comment by elpida-v** [comment]
We are interested in this feature too. Thank you!

**Comment by solares** [comment]
Also interested in this! This will be a great way to get the most out of app store traffic.

**Comment by solares** [comment]
Same question here.

**Comment by Shchvova** [comment]
It seems to be relatively easy to create alternative icons for iOS Apps in current setup.
To do that:
1. Drag & Drop Images.xcassets on Xcode to open the asset catalog with Xcode. Then you can create new iOS Icon or Drag & Drop AppIcon with "option" key pressed to make a duplicate. Say you name it "AppIcon2".

2. Then in `build.settings`, alter the 'xcassets' section to the following:
```lua
		xcassets = { 
		    filename = "Images.xcassets",
		    ["alternate-app-icon"] = "AppIcon2",
		},
```

If you want to have several alternative app icons packaged, it would look something like this:
```lua
		xcassets = { 
		    filename = "Images.xcassets",
		    icon2 = { "alternate-app-icon", "AppIcon2"},
		    icon3 = { "alternate-app-icon", "AppIcon3"},
		},
```
Any version of Solar2D would support this.

**Comment by solares** [comment]
Great to hear. We will give this a shot.

**Comment by sekodev** [comment]
If this works as described, we should add the description to [Managing Xcode Assets](https://docs.coronalabs.com/guide/distribution/xcAssets/index.html) section of the documentation so more people can be aware of it.
