### ISSUE TITLE
[ios]Remove permissions

### ISSUE THREAD

**Issue by PaoUNetWork** [coronalabs/corona#323]
Hello,Because the camera, microphone, and positioning are not used in my game, I need to remove the permissions related to these.But I uploaded the application to the ios platform for review, it needs the following related descriptions.

```
NSPhotoLibraryUsageDescription
NSMicrophoneUsageDescription
NSCameraUsageDescription
NSLocationWhenInUseUsageDescription
```

I want to know whether solar is useful for these content, and whether there is a way to remove the relevant content.

**Comment by Shchvova** [comment]
Did you all got rejected? Can you provide an email of rejection with exact working please. This is not common and usually it works fine.

**Comment by PaoUNetWork** [comment]
Dear Developer,

We identified one or more issues with a recent delivery for your app, "**" 3.5.10071457 (2112281804). Please correct the following issues, then upload again.

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSPhotoLibraryUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSMicrophoneUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCameraUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

Though you are not required to fix the following issues, we wanted to make you aware of them:

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

Best regards,

The App Store Team

 
Contact Us | App Store Connect
One Apple Park Way, Cupertino, CA 95014 Privacy Policy | Terms of Service

**Comment by elpida-v** [comment]
We had the same issue with one of our apps a year ago. Although we did not use camera, location, microphone and photo library, the app got rejected with the same message PaoUNetWork mentioned. We couldn't find any solution to this, so we ended up adding the purpose strings in Info.plist although these permissions are not actually needed. There must be a reason behind this, any ideas?

**Comment by Shchvova** [comment]
Please see #324 for explanation
