### ISSUE TITLE
[iOS]: Notification event.custom not consistent between event.applicationState 

### ISSUE THREAD

**Issue by mustafamsy** [coronalabs/corona#325]
Hi Vlad,

- [Yes] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.
- I also found other developers facing the same problem.

**Description of the bug**
When I try to open a remote notification which has 'event.custom' value when 'event.applicationState = active'
I can get the result of 'event.custom' with no problem and I can return its value. 
The problem is only when I click on the remote notification when the status of 'event.applicationState = inactive' (when the application start from closed mode) -> 'event.custom' returns nil.

**Target platform and where build was made:**
 - Device: [iPhone 11]
 - OS: [iOS15.2]

**Comment by scottrules44** [comment]
This should be fixed in recent update to Notification V2
