### ISSUE TITLE
[PLATFORM]: ERROR: Runtime error module 'plugin.openssl' not found:resource (plugin.openssl.lu) does not exist in archive

### ISSUE THREAD

**Issue by digvijayu** [coronalabs/corona#332]
- [x] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**Describe the bug**
Unable to run the native mobile application because of the run time error
ERROR: Runtime error module 'plugin.openssl' not found:resource (plugin.openssl.lu) does not exist in archive

It seems the plugins are not installed automatically or I may be missing a configuration

**To Reproduce**
1. Copy the corona cross platform templates for android and ios with Corona projects
2. Add a new plugin in the `Corona/build.settings` 
3. Run the native application
4. You should see an error in logs and screen, please refer below screenshot
![image](https://user-images.githubusercontent.com/7867644/149315701-d8ab3217-77cb-49c6-884f-b3b440ae0ec4.png)

**Target platform and where build was made:**
 - Device: iPhone11 pro simulator, android Pixel 5 simulator
 - OS: IOS 14.4, Android API 30

**Additional context**
I am trying a spike withe openssl plugin. Following the guidelines I have added the plugin to the build.settings file.
The native app templates are a copy of the simulator templates.

Same thing happens if I add any other plugin

```lua
-- File: Corona/main.lua
local openssl = require "plugin.openssl"
```

Below is the screenshot of how the project structure and the settings file look.
![image](https://user-images.githubusercontent.com/7867644/149317008-09b0ca62-e6af-41d1-9d5c-e340ae6de9e6.png)

**whole test project or build.settings**
```lua
--
-- For more information on build.settings see the Corona Build Guide at:
-- http://docs.coronalabs.com/guide/distribution/buildSettings/index.html
--

settings = 
{
	--[[
	orientation =
	{
		default = "portrait",
		supported = { "portrait" }
	},
	--]]

	plugins =
    {
        ["plugin.openssl"] =
        {
            publisherId = "com.coronalabs"
        },
    }, 

	iphone =
	{
		xcassets = "Images.xcassets",
		plist =
		{
			UILaunchStoryboardName = "LaunchScreen",
		},
	},
}

```

**Comment by digvijayu** [comment]
Hi @Shchvova thanks for responding to my thread, I am actually building it on Intel processor, here's my machine config. Hope this helps.
![image](https://user-images.githubusercontent.com/7867644/149528064-31e638ed-9191-4882-8682-2fa4a5b98fee.png)

**Comment by alexey-fest** [comment]
Same problem.
i've solved this by adding plugins manually.

Here you can read how to do this
https://forums.solar2d.com/t/cant-start-app-from-android-studio-plugins-not-found/354445
