### ISSUE TITLE
[Mac Simulator]: Wrong Build # Displaying

### ISSUE THREAD

**Issue by schroederapps** [coronalabs/corona#337]
**Describe the bug**
At least as of Build 2022.3664, the wrong Simulator build number is being reported in the Mac OS version, in the welcome screen as well as the "About Corona Simulator" window. Not having the correct build # displayed could make proper reporting of issues more difficult, as incorrect build #s may show up in issues/bug reports.

**To Reproduce**
1. Open Simulator (build 2022.3664) on MacOS.
2. Witness the incorrect build number "2100.9999" in the welcome window.
3. Open the "About Corona Simulator" window.
4. Witness the same incorrect build number "2011.9999" with the incorrect build date ("2100.1.16").

**Target platform and where build was made:**
 - Device: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
 - OS: macOS Monterey (12.0.1)

**Additional context**
Admittedly this is the most minor of issues, but figured it'd be a quick fix. Save it for a rainy day when you feel like an easy "win." :) 

(See attached screenshot to illustrate)

![wrong_build_number](https://user-images.githubusercontent.com/629369/150693136-d0cf4746-dc4e-4e56-8f41-cbceff8033c3.png)

**Comment by Shchvova** [comment]
Thank you for noticing!
