### ISSUE TITLE
Android: Blocking error using Flurry Analytics plugin on Samsung store

### ISSUE THREAD

**Issue by jajern** [coronalabs/corona#340]
Flurry Analytics plugin uses the Google Play Services on Android and this causes a blocking error to occur when the app is built for Android on Samsung Store.
https://docs.coronalabs.com/plugin/flurry-analytics/index.html

Note: Flurry Analytics mentions they use the Google Play services to "check for and respect the user's ad tracking preference": https://developer.yahoo.com/flurry/docs/analytics/gettingstarted/android/

The error is an Alert that appears just after the launch screen and prevents the app from continuing to run:
"Corona: Developer Error
[App Name Here] does not target the Google Play store,
but includes Google Play Services.
This is adding unnecessary bloat to your app as
Google Play Services depends on the Google
Play store.
Please remove Google Play Services from builds
that do not target Google Play.
Exit"

I am wondering if the Flurry plugin can be updated to not use the Google Play Services when publishing for Samsung, and not show the error message and work on the Samsung store? The Flurry plugin does work on Amazon which makes me think it can work without Google Play Services.

Best regards.

**Comment by scottrules44** [comment]
Cannot you use Google Play Services on Samsung? Are you targeting China?
<img width="724" alt="Screen Shot 2022-02-04 at 11 09 27 PM" src="https://user-images.githubusercontent.com/7820808/152628196-875c2c00-c3b6-483d-b27c-4486b8da91ed.png">

**Comment by scottrules44** [comment]
I see the issue, if you want to just target "Google Play" you should be able to upload this Galaxy Store still and avoid this pop up.

Will look into this more but you should be able to use Google Play Services with Samsung App Store. 
<img width="724" alt="Screen Shot 2022-02-04 at 11 09 27 PM" src="https://user-images.githubusercontent.com/7820808/152628357-9fa913d5-587a-4316-86ca-0d342d9ee60f.png">

**Comment by agramonte** [comment]
Building for Samsung with the Flurry plugin should work as expected. Please verify and close this defect.

Tested on:
Device: SM-S102DL
Corona Version: 2022.3665

**Comment by jajern** [comment]
This is also working for me in version 3665 on Mac. Thank you guys.
