### ISSUE TITLE
Simulator on Mac: build number not correct for v3664

### ISSUE THREAD

**Issue by jajern** [coronalabs/corona#341]
Simulator on Mac does not show correct version.

I believe the version name should read: 2022.3664

what is being shown: 2100.9999, and inside the about screen: 2100.9999 (2100.1.16)
<img width="302" alt="Screen Shot 2022-02-04 at 5 02 06 PM" src="https://user-images.githubusercontent.com/18579424/152618882-728557a9-64c1-4ae1-b2af-82f673128af1.png">

**Comment by sekodev** [comment]
I think this will be addressed in the next release. See #337

**Comment by scottrules44** [comment]
^Closing
