### ISSUE TITLE
Cannot create path for resource file

### ISSUE THREAD

**Issue by MavinVo** [coronalabs/corona#342]
Copyright (C) 2009-2022  C o r o n a   L a b s   I n c .
	Version: 3.0.0
	Build: 2022.3664
WARNING: Cannot create path for resource file 'resource.car (/snap/solar2d/5/bin/Resources/resource.car)'. File does not exist.

Platform: Linux / x64 / 1.0 / AMD ARUBA (DRM 2.50.0 / 5.13.0-27-generic, LLVM 12.0.0) / 3.1 Mesa 21.0.3 / 2022.3664 / en_us | us | en_us | en
WARNING: setStatusBarMode is not supported in Linux Simulator

**Comment by Shchvova** [comment]
This warnings can be safely ignored on Linux simulator. They don't cause the crash you're seeing and we're working on the redo of Sim to fix the crash

Thanks for reporting
