### ISSUE TITLE
[iOS]: Pressure always null in touch events on iOS devices that support 3D Touch

### ISSUE THREAD

**Issue by mjholgate-roche** [coronalabs/corona#349]
- [X] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**Describe the bug**
Pressure value in touch events for iPhone are null even if the device supports Force Touch/3D Touch when building with recent iOS SDK versions.

**To Reproduce**
Implement a Corona app which prints out the pressure value from touch events. Note that it is always null even if the device supports 3D Touch (e.g. iPhone 6s)

**Target platform and where build was made:**
 - Device: iPhone 6S
 - OS: iOS 13.7
 - Xcode 13 (iOS 15 SDK)

**Additional context**
It seems like later iOS SDKs don't guarantee to call `traitCollectionDidChange`, so [setForceTouchSupport](https://github.com/coronalabs/corona/blob/22eaf0631865a7e5876dc38622bd883cf465a80e/platform/iphone/CoronaViewPrivate.mm#L1351) never gets called.

We worked-around this problem by manually calling `traitCollectionDidChange` from our implementation of `viewDidLoad`:

`        gameView.traitCollectionDidChange(gameView.traitCollection)
`

**whole test project or build.settings**
N/A

**Comment by scottrules44** [comment]
Will take a look at this, but you are aware that Apple stopped putting 3D Touch in there iPhones back in 2018? This Api and tech seems to be on its way out the door

**Comment by scottrules44** [comment]
This has been fixed with #384
