### ISSUE TITLE
[android]: google IAP duplicate request issue found on the solar2D 3665

### ISSUE THREAD

**Issue by mrgump** [coronalabs/corona#350]
- [ ] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**Describe the bug**
After build the app for android by using the latest build 3665, it could be found when do a IAP payment, there are the IAP request duplicated for the same item. 

Logs below:

"
03-01 15:50:21.102 16174 16195 I Corona  : purchase: com.test.xxx.5000
03-01 15:50:21.102 16174 16195 I Corona  : purchase: com.test.xxx.5000

03-01 15:54:28.498 16174 16195 I Corona  : purchase: com.test.xxx.1000
03-01 15:54:28.498 16174 16195 I Corona  : purchase: com.test.xxx.1000
"

which may cause the IAP response duplicated too.

**To Reproduce**
1. Go to any IAP item and buy it;
2. Check the logs on console;

**Target platform and where build was made:**
 - Device: [pixel 5]
 - OS: [android 12]

**Additional context**

**whole test project or build.settings**
Please attach project your issue can be reproduced on to speed up debugging

**Comment by Shchvova** [comment]
Make sure you’re not doing duplicate requests from event. Like touch up and down.

**Comment by mrgump** [comment]
Sorry, please ignore this issue, it's caused by the same log message output in two different functions of My App.

Actually the 'Transaction failed, type:	6'  and 'Purchase already being finished'  often appeared in the purchase case that let me mistake it as a duplicate issue.

03-01 15:54:35.113 16174 16195 I Corona  : Purchase already being finished (acknowledged) com.test.xxx. 5000. It is safe to ignore this message
03-01 15:54:35.113 16174 16195 I Corona  : Transaction failed, type:	6	Server error, please try again.
