### ISSUE TITLE
Google SSO no longer working on iOS devices

### ISSUE THREAD

**Issue by punkdog** [coronalabs/corona#351]
Corona version: 3664 / 3665, maybe others
Xcode: 13.2
Plugin: googleSignIn
Dev environment: macOS Monterey 12.1
User devices definitely seeing issue so far: iOS 15.3.1 / iOS 15.1.1 / iOS 15.1

We have multiple games that use the same process and Scott's googleSignIn plugin to get a Google ID to link player config across multiple devices.  The most recent versions that were built within the last six weeks using 3664 (and we have tested against 3665 to see if that resolves the issue, but it doesn't) and another couple that are currently in the pre-release test phase have the same problem.  The other games (all using the same mechanism and similar OO code for this) work fine.  I have also rebuilt some older versions (published December) that were originally built with (I think) 3661 or possibly earlier and are working in production but they have the problem when rebuilt which seems to rule out the Firebase / Google SSO project and our code.

I have rebuilt with some older Solar versions too, but this didn't result in things working either (although am obviously building with a more recent SDK). If you try to sign in, then the sign in callback doesn't seem to return anything.  If you try to sign out then the game crashes.  Nothing on the console gives any clue as to what has happened for either event and troubleshooting code comments show that nothing is being returned after the plugin is called.

This is in urgent need of a fix as two released games have this problem and two more will be held up without a resolution.  We also have no easy way of doing an emergency patch or reverting back to an older dev environment to see if that helps.  Google SSO is working fine on the Android devices.

**Comment by mark-sgs** [comment]
This is also an issue with the Apple SSO as reported by players as well.

**Comment by scottrules44** [comment]
Will try to mess with my demo and get it to crash, but if you could email a simple build project that would make it easier for me. scottrules44@gmail.com

**Comment by mark-sgs** [comment]
You can replicate this with any simple project.  What happens is

1. there is a silent fail on `SignIn` - nothing happens, no error occurs, no callback fires.
2. app will immediately crash on `signOnt`, no error occurs, no callback fires.

If it helps, this appears to have started in the past week or so to production code (live published builds that worked prior to release) so maybe something has changed with iOS?

**Comment by punkdog** [comment]
If you have a demo project @scottrules44 then just build it to iOS using the same versions as outlined in the original post and see if GoogleSignIn is returning anything....

**Comment by mark-sgs** [comment]
Is this project on github so I can take a look? 

It is very odd for production codes to suddenly stop working.  I've now had 20+ complaints from players now.

**Comment by scottrules44** [comment]
https://github.com/scottrules44/googleSignIn-demo
^ you of course need add you own clientId and markeplaceId

**Comment by mark-sgs** [comment]
Even your own page [(https://scotth.tech/plugin-googleSignIn)] shows this...

```local googleSignIn = require "plugin.googleSignIn"
googleSignIn.init()
local androidClientID = "android client id"
local clientID = "iOS client id" -- iOS deafult
if (system.getInfo("platform") == "android") then
    clientID = androidClientID
end
googleSignIn.signIn(clientID, nil,nil,function ( ev ) end)```

**Comment by scottrules44** [comment]
![131004BE-3CDC-46C6-8916-10766695DA3F](https://user-images.githubusercontent.com/7820808/156611995-c58a8acd-b56a-430f-a1b4-a95174b11152.jpeg)
![4DA558E7-865E-4142-B2E5-8DE4AA096B78](https://user-images.githubusercontent.com/7820808/156612009-0003542d-193f-4155-902e-0fdaa7fb9067.png)

**Comment by scottrules44** [comment]
I see your talking about that on the bottom of the page, will update that

**Comment by scottrules44** [comment]
> 

You are right and working on a notification system for plugin changes in the marketplace. But old api should still work so it’s not a breaking change

**Comment by mark-sgs** [comment]
Sorry, but when code that has worked for years suddenly breaks - because of code changes in a plugin - that is by very definition a "breaking change".  If the old API still worked there would be no purpose of us reporting to you that it doesn't work.

So we can all learn from this, do you know what was the change that iOS clearly made that has caused production code to suddenly break?

**Comment by punkdog** [comment]
Maybe in the future this could be something that is flagged as a warning during the build?

**Comment by scottrules44** [comment]
> Sorry, but when code that has worked for years suddenly breaks - because of code changes in a plugin - that is by very definition a "breaking change". If the old API still worked there would be no purpose of us reporting to you that it doesn't work.
> 
> So we can all learn from this, do you know what was the change that iOS clearly made that has caused production code to suddenly break?
> 
> Clearly, lines of communication need to be improved here. Maybe we could go back to the weekly emails that Rob used to do to let devs know about changes?
> 
> For example, when a plugin changes on Unity a push email is sent out to all subscribers alerting them to the new version and including a change log.

Yeah I am working on a more automated long term solution with emails getting sent out from my vendor dashboard. 

I am not sure why your app would all the sudden be breaking but my best guess is that maybe the users are using either and older version of your app/of the google sdk. All my plugins are static and when you build your app that’s the plugin and Sdk you get. When I update the plugin and Sdk, you have to rebuild to get that plugin and Sdk

**Comment by mark-sgs** [comment]
> I am not sure why your app would all the sudden be breaking but my best guess is that maybe the users are using either and older version of your app/of the google sdk. All my plugins are static and when you build your app that’s the plugin and Sdk you get. When I update the plugin and Sdk, you have to rebuild to get that plugin and Sdk
 
No, all are using the build made end of Jan, and as I stated this worked until a week or so ago and then started falling over.

Update: Using the updated plugin code this is now functional on iOS so at least this is problem solved.

I do have to repeat my comment about not publishing breaking code without informing devs, using the plugin, that their code will break and lets move to a better solution for this moving forward.

**Comment by punkdog** [comment]
Still having problems here @scottrules44 and am completely baffled.  The firebase project runs with your SSO demo code.  I did a build of the game that uses SSO and copied the apk across using ADB, tested with multiple devices successfully.  Pushed a build live on Play Store and it doesn't work anymore.  Removed that and put the apk back on using ADB and it works again.  Do you have any thoughts about what I might be missing and why the behaviour of the plugin or the project would be different when the game is live to how it is when we are testing?

**Comment by scottrules44** [comment]
> Still having problems here @scottrules44 and am completely baffled. The firebase project runs with your SSO demo code. I did a build of the game that uses SSO and copied the apk across using ADB, tested with multiple devices successfully. Pushed a build live on Play Store and it doesn't work anymore. Removed that and put the apk back on using ADB and it works again. Do you have any thoughts about what I might be missing and why the behaviour of the plugin or the project would be different when the game is live to how it is when we are testing?

Could be SHA1 fingerprints, they are different for each keystore (i.e Debug and production keystores)

**Comment by punkdog** [comment]
Hi @scottrules44,

Thanks for your suggestion that was really helpful.  At first we thought it couldn't be that as we use the production keystore for testing too.  However, it got us thinking that actually Google doesn't use the same cert for production so we pulled a Play Store build off a device and extracted the SHA1 fingerprint from there and found that it was different.  So essentially your documentation is incorrect for new SSO implementations as Google signs them with a different cert.  I believe that this doesn't impact older apps as @mark-sgs believes that Google at some point migrated across self-signed certs for current devs, but this isn't the case for new devs.  So for new implementations the Google SHA1 needs to be included in the project as well as the dev cert.  Please put this in your documentation to save someone else the weeks of pain trying to figure out why everything worked in test but then when it went live SSO implementation was broken again. Thanks!
