### ISSUE TITLE
[AMAZON]: Vungle plugin in not functioning

### ISSUE THREAD

**Issue by mark-sgs** [coronalabs/corona#354]
Often ads simply do not play or they do play and then this is displayed 

![image](https://user-images.githubusercontent.com/61833594/157639368-657ecba5-9cfc-4ae7-87e4-2c2deb3cf384.png)

Can the plugin be fixed please?  This started months ago but ads not loading is a more recent problem.

**Comment by scottrules44** [comment]
Technically the plugin was made and updated by Vungle themselves. Hence the “ com.vungle” publisherId.

I will have double check with Vlad but I am fairly certain we don’t have the source code for this plugin.

**Comment by scottrules44** [comment]
There is now a new version of Vungle (v6) see docs here
https://docs.coronalabs.com/plugin/vungle-v6/index.html
