### ISSUE TITLE
[PLATFORM]: runtime bug

### ISSUE THREAD

**Issue by usmandotmughal** [coronalabs/corona#355]
When testing app on iOS 14.7 or above, [media.playVideo()](https://docs.coronalabs.com/api/library/media/playVideo.html) and [media.selectVideo()](https://docs.coronalabs.com/api/library/media/selectVideo.html) are not playing video.

**To Reproduce**
1. Build the attached sample project.

2. Run the app on iOS 14.7 or above iOS devices.

**Target platform and where the build was made:**
 - OS: [e.g. iOS14.7 or above]

**whole test project or build.settings**
A test project is attached.
[VideoSelectionTest.zip](https://github.com/coronalabs/corona/files/8230923/VideoSelectionTest.zip)

**Comment by scottrules44** [comment]
Replacing 
media.playVideo(event.url)
with
media.playVideo(event.url, media.RemoteSource, true)
makes your demo work.


See demo in docs 
https://docs.coronalabs.com/api/library/media/selectVideo.html#ipad

**Comment by usmandotmughal** [comment]
Hi @scottrules44, thanks for looking into the issue.

Can you please check the Sample Project attached? When you will pass event.url to network.upload(), it's not working.

**Comment by scottrules44** [comment]
For a networking side, your demo should not work. 
https://firebasestorage.googleapis.com/v0/b/janah-musa-signs.appspot.com/o/sample_video.mp4?alt=media
is not an upload-able url.

If you are trying to upload a video file to firebase, I recommend you check out the firebase storage plugin
https://solar2dmarketplace.com/plugins?FirebaseStorage_tech-scotth

**Comment by usmandotmughal** [comment]
@scottrules44 Thanks for the quick response.

Yes. It's upload-able url. I'm uploading videos with same code with Android and iOS 14.x below. If you test sample project on iOS 14.0 or below, it will work fine.

For reference, here is one example uploaded with same code:
https://firebasestorage.googleapis.com/v0/b/janah-musa-signs.appspot.com/o/coronaIcon.png?alt=media

I have tried storage plugin as well, but in my case I have to select video from gallery and then upload to firebase.

If you want check the storage plugin with same case, I have attached a demo project with firebase storage plugin in which I am trying to upload video with url which is returned by  @media.selectVideo(). Storage plugins is not working either.

Please have a look on attached project.
[firebaseStorage-demo-master.zip](https://github.com/coronalabs/corona/files/8242167/firebaseStorage-demo-master.zip)

**Comment by usmandotmughal** [comment]
Hello @scottrules44, Did you get the time to check above comment? Thanks.
