### ISSUE TITLE
[Request] Add a flatpak option for Solar2D. 

### ISSUE THREAD

**Issue by MetalMaxMX** [coronalabs/corona#357]
I like the team has been able to provide updated snaps to this project, which is great. Though if possible, I'd like it if there was an option for flatpak users as well, who may prefer or could only work with them due to a variety of reasons (be it due to snap requiring systemd and those users running alternative init systems, or people who fundamentally disagree with snaps due to having its server-side proprietary, etc.) 

Cheers!
MetalMaxMX

**Comment by airtonix** [comment]
further motivation: https://www.phoronix.com/scan.php?page=news_item&px=GNOME-Software-Dropping-Snap
