### ISSUE TITLE
Timer.resumeAll() not working.

### ISSUE THREAD

**Issue by Kan-Kzeit** [coronalabs/corona#359]
I have a issue with Timer.pauseAll() and Timer.resumeAll().
Specifically, I create 2 timers that print to the screen 'A' and 'B' every 500 milliseconds. When I touch the screen they both pause and when I touch the next time they both resume. But only timer 'B' is resumed.
This problem can be easily solved using a tag or id, but new users can stumble upon it without knowing.

[timer_issue.zip](https://github.com/coronalabs/corona/files/8259622/timer_issue.zip)

**Comment by scottrules44** [comment]
Added this info to Gotchas
https://docs.coronalabs.com/api/library/timer/pauseAll.html
