### ISSUE TITLE
Kidoz Plugin out of date

### ISSUE THREAD

**Issue by taptaptales** [coronalabs/corona#362]
Effective April 1, 2022, Google is implementing a policy where apps that target children must ensure that Android Advertising ID (AAID) is transmitted only when it's known that the user is not a child.

Kidoz plugin is outdated and it will start causing app rejections from Google Play unless it's updated with the new Kidoz SDK 8.9.5.

**Comment by scottrules44** [comment]
Kidoz has been updated to 8.9.5
