### ISSUE TITLE
Support multiple app icons in the binary 

### ISSUE THREAD

**Issue by elpida-v** [coronalabs/corona#363]
We want to include multiple icons in our binary in order to use Product Page Optimization on the App Store. We followed Vlad's instructions on this thread https://github.com/coronalabs/corona/issues/321 but we are getting this warning message on the Solar2D console:

```
WARNING: issue found in build.settings: 
WARNING: unrecognized key: settings.iphone.xcassets.filename (string)
WARNING: unrecognized key: settings.iphone.xcassets.icon2[] (string)
```

The steps we've done:
1. Our alternative icon (with size variations) has been added in a folder named "AppIcon2.appiconset" inside Images.xcassets. 
2. We've selected the “**Include all app icon assets**” option in Xcode 13.3.  
3. We've added AppIcon2 to the "**Alternate App Icon Sets**" in Xcode 13.3
4. We've edited our build.settings as shown below:
```
iphone =
{
       xcassets = { 
           filename = "Images.xcassets",
            icon2 = { "alternate-app-icon", "AppIcon2"},
       },
}
```

Why do we get this warning message? Has anyone implemented multiple icons successfully?

**Comment by Shchvova** [comment]
This warning messages can be ignored. Does the alternative icon work?

**Comment by elpida-v** [comment]
I don't really know yet. This app version has been uploaded on App Store Connect but not submitted for review yet. I am just worried because on App Store Connect under "Prepare for Submission" --> "Build" --> "Included Assets" only the default icon shows. Maybe the alternative icon is not supposed to show there?

**Comment by solares** [comment]
@elpida-v Did you get this going?

**Comment by elpida-v** [comment]
> @elpida-v Did you get this going?

Yes, I did. It works perfectly.

**Comment by solares** [comment]
Good to hear! I have a few questions about it: 

1. When you add definitions to xcassets as in the example, which is the name of the alternate icon? Is it `icon2` or `AppIcon2` ?
2. Did you need to make any changes to the syntax in the example above to get it working? 
3. We build the app using CoronaBuilder from the command line. Do you know how to select `Include all app icon assets`?

**Comment by elpida-v** [comment]
I didn't make any changes in the syntax above. So, my build.settings looks like this:
```
iphone =
 {
         xcassets = { 
            filename = "Images.xcassets",
            icon2 = { "alternate-app-icon", "AppIcon2"},
      ...
}

**Comment by elpida-v** [comment]
![Screenshot 2023-01-22 at 7 56 54 PM](https://user-images.githubusercontent.com/59620078/213931922-55a99426-8b9b-4268-86fa-5844659690ad.png)

**Comment by elpida-v** [comment]
> ![Screenshot 2023-01-22 at 7 56 54 PM](https://user-images.githubusercontent.com/59620078/213931922-55a99426-8b9b-4268-86fa-5844659690ad.png)

This is how I include the alternative icon files.

**Comment by elpida-v** [comment]
> 

I don't know how to do it in the CoronaBuilder. In Xcode you will find `"Alternative App Icon Sets"` and `"Include All App Icon Assets"` in `"Build Settings" --> "Asset Catalog Compiler - Options"`.
