### ISSUE TITLE
ITMS-90424: Invalid Swift Support with Solar2D 3666

### ISSUE THREAD

**Issue by Shchvova** [coronalabs/corona#367]
After submitting the app verification fails with the following:

ITMS-90424: Invalid Swift Support - The SwiftSupport folder is empty. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

**Comment by Shchvova** [comment]
Issue seems to be with outdated Facebook frameworks in one of the plugins.

**Comment by tlyndon** [comment]
@vlad, are you updating the v4a FB plugin or is this part of the core Solar2D build?

**Comment by Shchvova** [comment]
@tlyndon I think Scott made an update not that long ago, probably ironsource plug-in has to be updated too
