### ISSUE TITLE
Add clear button to native text field

### ISSUE THREAD

**Issue by dethier1958** [coronalabs/corona#369]
Would it be possible to add a property to include the clear button (the x button on the right of an edit field that clears any text in the edit field when tapped) to the native text field? Thanks!

**Comment by scottrules44** [comment]
You could easily just use a display object next to a native text field to handle this.

**Comment by dethier1958** [comment]
That's a hack, not a solution. In iOS, the clear button is part of the edit field. Putting a button next to the edit field would be tacky. Please re-open this. It should not be hard to add.
