### ISSUE TITLE
[iOS]: Add property to include clear button in edit field

### ISSUE THREAD

**Issue by dethier1958** [coronalabs/corona#370]
In iOS, the edit field can include a button to clear the edit field of text (setting the clearbuttonmode for the edit field). Please add a property that will add this to the native edit field for iOS. While I could do my own button outside the edit field, this would not include the expected behavior under iOS. It would be better to support the built in iOS clear button. Thanks.

**Comment by dethier1958** [comment]
I figured out a way to do it, if textfield is my native text field:

    textfield:setNativeProperty('clearButtonMode', 3)

I would prefer to figure out what the name of the value is, instead of using 3, but I haven't found a name that worked.

It would be preferable to be able to do this with a property like:

    textfield.clearButtonMode = 'always'

Perhaps this can be added in a future version?

**Comment by scottrules44** [comment]
This is added in the newest build
