### ISSUE TITLE
[Android] Target SDK Version

### ISSUE THREAD

**Issue by dethier1958** [coronalabs/corona#376]
Google is now requiring that existing apps use a targetSDKVersion of 30 by November 1, 2022, and 31 by November 1, 2023. (see https://support.google.com/googleplay/android-developer/answer/11926878). There is a minSdkVersion property we can use in our build settings, but when I tried targetSdkVersion, it seemed to be ignored. Could this be added and used?

Failing that, could the next release set the target SDK to 31?

Thanks!

**Comment by Shchvova** [comment]
New build is up. If anyone up to it, I would love some help testing.

**Comment by TellmewowBilbao** [comment]
Does this version update Google Admob SDK to 20.6.0 or higher? This is needed to fulfill policy updates around children and transmitting identifiers recently announced by Google Play.

**Comment by appfamily** [comment]
Thanks Vlad. I'm back from holiday and have started testing, on my devices it behaves as usual and I'll now publish a build to Google and see if it resolves the issues with transmitting identifiers.

The app print out the AdMob plugin version when initialized, but the SDK version is 0. I assume that is supposed to show the AdMob SDK version (i.e. 20.6.0) which would be helpful to know.

`plugin.admob: 1.3.0 (SDK: 0)`

Note: If using mediation via AdMob you can now update to the latest plugin versions for ad networks (e.g. Unity: https://developers.google.com/admob/android/mediation/unity)

**Comment by appfamily** [comment]
Great, I'll check it out next week when back in the office
