### ISSUE TITLE
Plugins broken in snap version

### ISSUE THREAD

**Issue by zeed27** [coronalabs/corona#379]
Hi! For the moment the plugins do not work on the snap version (tested on ubuntu 22.04). Are there plans to fix this in the next build?

**Comment by zeed27** [comment]
Thank you for your work Vlad !

**Comment by zeed27** [comment]
Hi,
seems it doesn't work for me, no change with the new build. Did I miss something ?

`Copyright (C) 2009-2100  C o r o n a   L a b s   I n c .
	Version: 3.0.0
	Build: 2100.9999
WARNING: Cannot create path for resource file 'resource.car (/snap/solar2d/9/usr/local/bin/Solar2D/Resources/resource.car)'. File does not exist.

Loading project from: /home/me/Bureau/mySolarApp
Project sandbox folder: /home/me/snap/solar2d/9/.Solar2D/Sandbox/mySolarApp
ERROR: Runtime error
/root/parts/solar2d/src/platform/resources/init.lua:931: module 'plugin_utf8' not found:
	no field package.preload['plugin_utf8']
	no file '/home/me/snap/solar2d/9/.Solar2D/Plugins/plugin_utf8.lua'
	no file '/home/me/Bureau/mySolarApp/plugin_utf8.lua'
	no file '/home/me/Bureau/mySolarApp/plugin_utf8.lua'
	no file '/home/me/snap/solar2d/9/.Solar2D/Plugins/plugin_utf8.so'
	no file './plugin_utf8.so'
	no file '/home/me/Bureau/mySolarApp/plugin_utf8.so'
	no file '/home/me/snap/solar2d/9/.Solar2D/Plugins/plugin_utf8.so'
	no file './plugin_utf8.so'
	no file '/home/me/Bureau/mySolarApp/plugin_utf8.so'
stack traceback:
	[C]: in function 'require'
	/root/parts/solar2d/src/platform/resources/init.lua:931: in function 'require'
	/home/me/Bureau/mySolarApp/main.lua:20: in main chunk`

**Comment by Shchvova** [comment]
Try but plug-in please. I don’t think utf8 is built for Linux yet

**Comment by zeed27** [comment]
Ok (currently I got the same result with  openssl, imageCrop, qrscanner and zip plugins)

**Comment by bakeinflash** [comment]
For now only plugin.bit is built for linux. Hoping utf8 and some others
also will be ready soon.
