### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [coronalabs/corona#38]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [LogEntryCollection::Clear](https://github.com/coronalabs/corona/blob/83ef32d39e658af276daaa30bfcac4e04f324341/platform/windows/Corona.OutputViewer/LogEntryCollection.cpp#L71 "LogEntryCollection::Clear function")
- [SetSource](https://github.com/coronalabs/corona/blob/83ef32d39e658af276daaa30bfcac4e04f324341/librtt/Renderer/Rtt_Program.cpp#L42 "SetSource function")
- [WinGlobalProperties](https://github.com/coronalabs/corona/blob/83ef32d39e658af276daaa30bfcac4e04f324341/platform/windows/Corona.Simulator/WinGlobalProperties.cpp#L87 "Destructor for WinGlobalProperties")

**Comment by Shchvova** [comment]
Code needs some cleaning up for sure. You can fork the project and make a pull request if you want to.

This way one can suggest actual code change, then they will get reviewed and pushed to the code base.

Thanks a lot for participating!

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by Shchvova** [comment]
Currently I'm heavily focused on moving Corona to new license, and making Simulator offline and  various other things. If  you want to clean up some warnings like that, feel free to make a  pull request.
