### ISSUE TITLE
Google IAP does not support downgrade or upgrade subscriptions.

### ISSUE THREAD

**Issue by usmandotmughal** [coronalabs/corona#399]
Case: 
App has monthly and yearly subscriptions, User has purchased a monthly subscription. App has an offer(a yearly discounted subscription) for the monthly subscribed user.

I was checking the native code for google billing API. They have a method to upgrade and downgrade the subscription. Here is [Documentation](https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder#setSubscriptionUpdateParams(com.android.billingclient.api.BillingFlowParams.SubscriptionUpdateParams))

I did not find any method In the [latest google billing plugin](https://docs.coronalabs.com/plugin/google-iap-billing/index.html). I if do [store.purchase()](https://docs.coronalabs.com/plugin/google-iap-billing/purchase.html), it keeps all subscriptions

Can you have some methods on wrapper of setSubscriptionUpdateParams native method? Thanks.

**Comment by scottrules44** [comment]
Added in new plugin.google.iap.billing.v2

https://docs.coronalabs.com/plugin/google-iap-billing-v2/purchase.html#subscriptionupdate-reference
