### ISSUE TITLE
Google mapsKey generates a warning!

### ISSUE THREAD

**Issue by Antkmk** [coronalabs/corona#403]
I’m getting this error message when I build my app:
WARNING: unrecognized key: settings.application.license.google.mapsKey (string)
I’ve added my Google mapsKey to my build.settings as detailed on this Solar2d page:

https://docs.coronalabs.com/api/library/native/newMapView.html

Why does Solar2d not recognize this setting?
I’ve removed my map key from my settings listed below.
Thank you in advance. ~Keith

**Platforms involved**
Building on: macOS 12.4
Solar2d build: 2022.3673

**Attach your build.settings**
   application =
   {
    license =
    {
        google =
        {
            mapsKey = "xxxxxxxxxxxxxxxxxxxxxx",
        },
    },
   },

**Comment by scottrules44** [comment]
As stated in docs, the mapsKey goes in config.lua

**Comment by Antkmk** [comment]
It does! Thank you. That's embarrassing. That'll teach me to pay more attention while I'm reading the instructions. :O
