### ISSUE TITLE
FacebookClientToken not supported in iOS plist

### ISSUE THREAD

**Issue by punkdog** [coronalabs/corona#409]
We are using FacebookClientToken and getting this error in the simulator:-

**WARNING: issue found in build.settings:
WARNING: unrecognized key: settings.iphone.plist.FacebookClientToken (string)**

I tried updating build to 3673 but still seeing the same warning.

 Any thoughts?

**Comment by scottrules44** [comment]
Note the word "WARNING" which is not an error. The Plist contains lots of different type of data and we only validate some of the supported the field which is why you are getting this error. 

Fair point about not validating FB Client Token, but should be fixed in 3674+(Next Version) #410
