### ISSUE TITLE
native.setProperty( "androidSystemUiVisibility", "immersiveSticky" ) with “adaptive” config

### ISSUE THREAD

**Issue by JoaoPeixoto72** [coronalabs/corona#411]
native.setProperty( "androidSystemUiVisibility", "immersiveSticky" )
I had to put this line in my main file because wrong height calculation when android devices had software navigation buttons. A black bar apear in the botton of the screen exactly same size of the soft bar below it. (it doubles the area that android steals to put the soft keys).

With that line, I thought the problem was solved because now the area is well calculated and appear all app in full screen without the black bar. but appeared a new problem, the icons and the fonts are stretched.
with some experiences I notice that this problem only ocur If my scale in config.lua is “adaptive” it will stretch.
If my scale in config.lua is “zoomEven” it will not stretch the icons and fonts.

**Comment by sekodev** [comment]
Is this issue solved after any of those two releases?

[2022.3681](https://github.com/coronalabs/corona/releases/tag/3681) - Android: Fix for NavBar height with getSafeAreaInsets

[2023.3686](https://github.com/coronalabs/corona/releases/tag/3686) - Android: Add hasSoftwareKeys to getInfo

**Comment by scottrules44** [comment]
^I marking this as complete due the fact that NavBar height is calculated correctly
