### ISSUE TITLE
Implement presentCodeRedemptionSheet in IAP plugin

### ISSUE THREAD

**Issue by usmandotmughal** [coronalabs/corona#413]
- [ ] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**We would like to have 'presentCodeRedemptionSheet' functionality in the Apple IAP plugin.** 
I checked the current code of the Apple IAP plugin and it seems our current plugin did not support the 'presentCodeRedemptionSheet'. Can we have this method implemented in the Apple IAP plugin so we can use redemption offers functionality in our apps?

https://developer.apple.com/documentation/storekit/skpaymentqueue/3566726-presentcoderedemptionsheet

It would be a great boost for Solar 2d apps which uses subscriptions.

**Comment by solares** [comment]
I have been discussing this with @usmandotmughal and would be very keen to see it added to the IAP plugin.

**Comment by elpida-v** [comment]
That would be a great feature. We also want to use in-app offer code redemption.

**Comment by solares** [comment]
We're trying subscription codes. Will check on Testflight, thanks.

**Comment by AllenStudycat** [comment]
https://user-images.githubusercontent.com/64068561/178130742-fcf9ffdc-8d0e-47dc-b163-d52757dea7be.mov

![截圖 2022-07-10 上午11 54 53](https://user-images.githubusercontent.com/64068561/178130747-a7746ab4-0c49-40f8-94a6-ef04c8afd3a9.png)

**Comment by solares** [comment]
@Shchvova 
We have tried these, but they are not working correctly. 

1. We can show the redemption sheet with no problem. 
2. When we enter a code and submit it. The Redeem button becomes inactive. 
3. We expect another callback from Apple servers, but there is none. 
4. After a minute or so, the Redeem button becomes active again, but the redeem stays. 

I have found various threads online for other platforms (Swift, RevenueCat) that say they are unreliable, so it might not be a Solar2D problem:

https://stackoverflow.com/questions/69314134/apple-code-redemption-presentcoderedemptionsheet-doesnt-give-any-feedback
https://stackoverflow.com/questions/72091912/in-app-purchases-presentcoderedemption-get-response
