### ISSUE TITLE
MacOS Simulator: display.save always produces blank image on first call

### ISSUE THREAD

**Issue by personalnadir** [coronalabs/corona#423]
- [x ] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**Describe the bug**
In the MacOS simulator 3674 I have to introduce a junk display.save call as the first time I invoke it, it always produces a blank file.

**To Reproduce**
Steps to reproduce the behaviour:

1. run this code - requires a dot.png I am using a 200x200 white circle on a transparent background
```

function safeSave()
	local temp=display.newImage("dot.png")
	display.save(temp,{filename="junk.png",isFullResolution=true})
	display.save(temp,{filename="top_dot.png",isFullResolution=true})
	display.save(temp,{filename="bottom_dot.png",isFullResolution=true})
	
end
timer.performWithDelay(100,safeSave)
```
2. check the documents folder in the apps sandbox junk.png is blank

**Target platform and where build was made:**
 - Device: MacOS Simulaot 2022.3674
 - OS: MacOS 12.4

**Comment by personalnadir** [comment]
@ggcrunchy I have the simulator running and the example above is actually slightly worse (more image corruption on the 2nd and 3rd save calls) than the release simulator. Any changes you'd like me to try? 

Also it's not possible to build the simulator if any part of the absolute project path contains a space. I had cloned the repository to my `Open Source` folder and that broke the build (it was a lua related stage).

**Comment by personalnadir** [comment]
I had a quick look
1. fDefaultFBO was always 0 on my machine
2. I assume this is done by Viewing the the memory of fData? In that case the values were not zero, but were only identical on the 2nd and 3rd calls. 
Will have a look at 3 tomorrow

**Comment by personalnadir** [comment]
Actually I tried 3 and neither the glFlush() and / or glFinish() at the beginning or end of Execute seemed to make any difference.

**Comment by personalnadir** [comment]
Junk.png looks like a valid png (to my untrained eye) when I view the hex, but once it gets into the image data it's just the same hex pattern repeating endlessly. 

Viewing memory of fData I noticed some odd strings in it. Not sure how relevant it is 
![Screenshot 2022-07-15 at 10 52 33](https://user-images.githubusercontent.com/559503/179201082-ab7dc557-31f5-473b-8392-ca5aeee1c598.png)
![Screenshot 2022-07-15 at 10 50 55](https://user-images.githubusercontent.com/559503/179201102-7936100f-ac44-4829-99a6-606409b0c290.png)

Adding the #include "Renderer/Rtt_GL.h" line breaks all the Rtt namespace calls in the file, so haven't been able to test the GL_CHECK_ERROR calls. Anyway round that?

**Comment by personalnadir** [comment]
Ah that makes sense. How do I see the actual value of fData? If I select 'View Memory of "*fData"' the data remains largely full of zeros in all cases.

**Comment by personalnadir** [comment]
I'm not seeing any issues with the GL_CHECK_ERROR calls

**Comment by ggcrunchy** [comment]
Well, if it's a circle like that I'd jump down `fWidth * 4 * X` bytes (4 = RGBA, `X` = some guess for number of rows) from the value in `fData`. The lots of zero values makes sense just because of the empty space. Even though the second / third image is messed up, the idea is to see if the first one has anything at all. (If not, we can at least rule out a problem in the saving logic.)

Oh, also, those debug prints would show up in the Solar2D console, though they might get mirrored to Xcode output too, not sure.

Are there any changes if you switch skins and / or zoom levels?

**Comment by scottrules44** [comment]
This appears to be fixed with the newer versions of Corona/Solar2D Sim
