### ISSUE TITLE
Console window reports time-of-day incorrectly, mismash of AM/PM and military style

### ISSUE THREAD

**Issue by sieler** [coronalabs/corona#43]
When I run the Corona simulator on my Mac, the console window reports the time as 04:05:42 on Mar 23.
That's not my local time (which would be PDT, 16:05), nor GMT.

It appears that it's incorrectly putting a leading zero on AM/PM time *AND* omitting the AM/PM suffix (double bug :)

Suggested fix: use military time (16:05:42). ... this is preferred over deleting the "0" and appending an AM/PM as it saves screen space.

**Comment by Shchvova** [comment]
This will be fixed soon. I'm in the middle of bigger project, I'll merge this fix after that.

**Comment by sieler** [comment]
thanks!

BTW, what would it take, contribution wise, to move to the current version
of Lua?

(I really want to use "continue", "<<", and "&" in my code :)

thanks,

Stan Sieler
Cupertino, CA, USA

**Comment by coronarob** [comment]
Corona uses a customized version of Lua 5.1. We have not updated because of the changes that we made.  It would be a pretty major project to update it.  

This is not likely a task we can take on for the foreseeable future.

Rob

**Comment by sieler** [comment]
darn.  thanks.
