### ISSUE TITLE
Add getAppSetId to More Info plugin

### ISSUE THREAD

**Issue by solares** [coronalabs/corona#446]
"app set ID"  looks like the preferred id to use for privacy-friendly apps, now that Google are following Apple's lead on identifiers. 

https://developer.android.com/training/articles/app-set-id

Can we add this to the moreInfo plugin?

**Comment by scottrules44** [comment]
Sorry mistyped, More Info plugin has this now
https://scotth.tech/plugin-moreInfo

**Comment by solares** [comment]
Thanks, that's great.
