### ISSUE TITLE
After Upgrading coronacards.framework iOS app is not building

### ISSUE THREAD

**Issue by antilakash** [coronalabs/corona#447]
While Upgrading coronacards for ios i am facing this issue
Can anyone tell me where i messed up. I followed these 
I deleted the CoronaCards.framework from ios of my projec and pasted the new CoronaCards.framework(latest)
Got this error while building xcode project
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AppleKeyServices", referenced from:
      objc-class-ref in CoronaCards(CoronaViewPrivate.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1

**Comment by Shchvova** [comment]
This should be fixed in next build
