### ISSUE TITLE
[ANDROID]: display.newImage() returns nil

### ISSUE THREAD

**Issue by banningcalvin** [coronalabs/corona#449]
- [x] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**Describe the bug**
display.newImage returns nil on Android 13, but runs fine on simulator.

**To Reproduce**
1. Create a newImage: `testobj = display.newImage("/assets/images/heartfull.png"`
2. run an assert to prove that it is nil: `assert(testobj ~= nil,os.exit())`

**Target platform and where build was made:**
 - Device: [Pixel 6]
 - OS: [Android 13 Security Update September 5 2022 Google Play System Update July 1 2022]

**Additional context**
This runs fine on simulator on Windows, have not tested on iOS/macOS.
On the simulator, the function actually does return nil, but won't crash. On Android, it will crash. If we test as shown below, the project will exit, indicating that the returned value is, in fact, nil. According to the documentation: [here](https://docs.coronalabs.com/api/library/display/newImage.html) it should return a displayObject, even if the image is invalid for some reason.

I have not gotten time to look into the root cause of this issue but I plan to, and will try to submit a resolving change if possible but I wanted to bring this up as Android 13 was recently released and there seems to be no other reported instances of this.

**whole test project or build.settings**
Start a new project, create a live build with this in main.lua:
`testobj = display.newImage("Icon.png")`
`assert(testobj ~= nil,os.exit())`
If the assert is left out, the application will not exit on Simulator or Android, but it will crash Android.

**Comment by Shchvova** [comment]
Make sure case of your file and path matches.
MacOS and windows have case insensitive file systems. So HelloWorld.png and helloworld.PNG is same file. But it won't won't on device.

**Comment by banningcalvin** [comment]
Hi, I updated the initial post for Icon.png to reflect the correct case, and tested this, with the same results.

**Comment by scottrules44** [comment]
@banningcalvin  There is also a big issue with 

assert(testobj ~= nil,os.exit()) -- assert(boolean , string (optional))

You should look at the documentation

https://docs.coronalabs.com/api/library/global/assert.html


I am guessing you are use a default/template project. If you look in the building.settings "Icon.png" is automatically removed when build for any platform 
`
--
	-- Project section
	--
	excludeFiles =
	{
		-- Exclude unnecessary files for each platform
		all = { "Icon.png", "Icon-*dpi.png", "Images.xcassets", },
		android = { "LaunchScreen.storyboardc", },
	},
`

**Comment by banningcalvin** [comment]
Hi Scott,
Thanks for the quick follow ups. Although not urgent, I appreciate it. I also suppose the ~= nil is redundant in hindsight. Two follow up questions:

1) Is the issue with assert officially documented/open/being worked on? I don't see any notes about this on the docpage unless I'm missing it. I can open an issue and work on this if it isn't already being documented or worked on.
2) Ah I completely missed this! I originally noticed this on a project I had shelved for a few weeks, which previously worked. This was the only place I seemed to use this call. Everywhere else I was using widgets for images. I did make a slightly different test project and will post it tomorrow or asap, but it does seem to have the same broken behavior on Android, but not on Simulator. I have updated the title of this issue to reflect the platform correctly.

**Comment by scottrules44** [comment]
1. I was pointing out your syntax was wrong, assets second param should be a string not a function(ie you put os.exit())
2. It seems pretty clear to me in the documentation that excluding files(via build.settings) only applies when building app(not to sim)


I going to go head and close this issue because it’s seems configuration/syntax issue and not a core/engine issue. If you are still having problems with your project, I encourage you submit your topic/question to  forums.solar2d.com

**Comment by banningcalvin** [comment]
I apologize as I was premature in opening this and believe it to be related to an issue with absolute vs. relative path rules and will open a thread on the forums. Many thanks for the patience and help.
