### ISSUE TITLE
Android AAB error on Google Play if not using "usesExpansionFIle = true" in build settings

### ISSUE THREAD

**Issue by jajern** [coronalabs/corona#454]
I have had the declaration "usesExpansionFIle = true" in the build settings for my apps for ever since my apps are all graphics heavy, but looking at the documentation recently it looked like that was no longer needed and the simulator will build both APK and AAB files automatically. I removed that declaration from the build settings and built the app, tried to upload the AAB file but then received an error on Google Play:

"One or more of the auto-generated multi-APKs exceeds the maximum allowed size of 150 MB."

I then put the declaration back in and was able to upload the AAB with no problems.

This is a request to see if it makes sense to update the build system to no longer need that declaration and automatically reduce the APK file sizes within the AAB so there is no error uploading to Google Play. This seems like the best approach to me unless I am missing something from the developer's perspective.

Or update the documentation to state that "usesExpansionFIle = true" is still needed if the APK file size is over 150MB.

If the preference is to remain using the "usesExpansionFIle", we should consider renaming it so it makes more sense going forward.
Something like "fileSizeOver150MB = true".

**Comment by Shchvova** [comment]
Flag enables all asset to be packaged in Play Asset Delivery install time package. I believe it is limited to 1GB total.
