### ISSUE TITLE
Android: implement system.getInfo( "hasSoftwareKeys" )

### ISSUE THREAD

**Issue by XeduR** [coronalabs/corona#457]
I just saw @scottrules44's recent PR https://github.com/coronalabs/corona/pull/456 and after a bit of investigating, I found the `HasSoftwareKeys` function:

https://github.com/coronalabs/corona/blob/57e9d84d9bbb4472f869325e9d437fd570098365/platform/android/sdk/src/com/ansca/corona/CoronaActivity.java#L1246-L1274

This approach seems to have been taken directly from https://stackoverflow.com/questions/14853039/how-to-tell-whether-an-android-device-has-hard-keys/14871974#14871974 (and could be further improved by adopting the caching introduced in https://stackoverflow.com/a/28412856).

My new feature request would be to take that function and expose it to Solar2D's `system.getInfo()` so that developers could use it to obtain information on whether or not the current Android device has software keys or not, e.g. `system.getInfo( "hasSoftwareKeys" ) -- returns true or false`

**Comment by scottrules44** [comment]
This is added in 3686
