### ISSUE TITLE
Appodeal Update for Android

### ISSUE THREAD

**Issue by Sumtin** [coronalabs/corona#458]
Problem:
Receiving following from Google Play store:

`Your app includes SDK com.my.tracker:mytracker-sdk, X.X.X or an SDK that one of your libraries depends on, which by default requests device location without any programmatic method to verify that end user consent information has been obtained by the app. Apps with SDKs that collect any personal and sensitive data without disclosure and consent are in violation of Play policies.`

Fix:
Appodeal has provided a few ways to mitigate:  Upgrade their Android SDK to v2.11.0.2 or upgrade the mytracker-sdk target in build.gradle

See here: 
https://wiki.appodeal.com/en/faq-troubleshooting/troubleshooting/android-common-issues/mytracker-sdk-publication-issue

**Comment by scottrules44** [comment]
My Tracker adapter has been updated to address this issue
