### ISSUE TITLE
macOS/Windows: new windowState event doesn't work correctly when minimising the window

### ISSUE THREAD

**Issue by XeduR** [coronalabs/corona#461]
I tested the new feature from https://github.com/coronalabs/corona/pull/459, which is fantastic, but there's one issue with it that should be addressed.

Here's my main.lua:
```lua
Runtime:addEventListener( "windowState", function( event )
	print( event.phase )
end )
```

The issue is that the event phase is incorrectly identified when the window is minimised, either by pressing the minimise button on the window or by pressing the Windows key + down arrow. When the window is minimised, the listener will misidentify the state as "foreground" instead of "background".

**Comment by Shchvova** [comment]
Which OS are you testing on?

**Comment by XeduR** [comment]
The above was from Windows 10. I can give Mac a quick test as well.

**Comment by XeduR** [comment]
So, when minimising the window,

On Windows 10, I'm seeing phase is "foreground" both when minimising and restoring the window.

On Big Sur 11.5.2., there's no event phase change. Nothing seems to be logged if you minimise and then restore the window.

**Comment by XeduR** [comment]
One more thing that I found on Windows 10 is that when you restore the window, it will trigger the "foreground" phase twice.
