### ISSUE TITLE
Bug or, withdrawn support- No Option in Build menu to Build for Windows App any more?

### ISSUE THREAD

**Issue by VBLecturer** [coronalabs/corona#464]
Running  of Solar 2d Simulator Version: 3.0.0 Build: 2022.3681
on Mac OS Monterey 12.6
Test of app functions all ok under similar. 
Trying to create a new Windows only app is now not possible. 
Reason - There is no Windows Build option presented and more.

Build options provided on my set-up now are  as follows ...
-------
IOS
Android
HTML 5 (beta)
macOS
tvOS
----

The older Windows option is not presented anymore.
Last used here March 2022. No idea at what time this disappeared as I have not tried this option until today.

That run time version still functions,

 however the Apps  top and Botton image toolbars (menus buttons) are no longer shown. The run time Microsoft Windows 11 window size has shrunk and viewing/ touching top or bottom buttons no longer accessible.  sIn trying to debug and rebuild  to check why I discovered build for Windows is no longer presented.

At run time in Windows 11 there are no window buttons (red yellow green) option to show larger, smaller or even  no stretch window larger now on the runtime window...

Runtime Windows 11  Platform is running in a VM environment using Parallels Version 18.0.2 (53077)-latest version 

***Attach your build.settings**
settings =
{
    orientation =
    {
       
         default = "landscapeLeft",
       supported = { "portrait","landscapeLeft", "landscapeRight","portraitUpsideDown"}

    },
    osx=
    {
    	 plist =
        {
        	NSAppTransportSecurity =
            {
                NSAllowsArbitraryLoads = true,
            },
        },
  
    },
   
 
     iphone =
    {
   
        plist =
        {
        	NSAppTransportSecurity =
            {
                NSAllowsArbitraryLoads = true,
            },
            CFBundleIconFiles =
             {
                "Icon-40.png",--
                "Icon-58.png",--
                "Icon-76.png",--
                "Icon-80.png",--
                "Icon-87.png",
                "Icon-120.png",--
                "Icon-152.png",--
                "Icon-167.png",--
                "Icon-180.png"
                },--
            
            UILaunchStoryboardName = "LaunchScreen",  -- Required!
            UIStatusBarHidden = false,
            CFBundleDisplayName = "UKLoTis",
            CFBundleName = "UKLoTis",
        },
    },
          

**Full build log**
CANNOT BUILD FOR WINDOWS-NO OPTION
Enable full build log:
On macOS:
```
defaults write com.coronalabs.Corona_Simulator debugBuildProcess  -int 5
```
On Windows:
```
reg ADD "HKEY_CURRENT_USER\Software\Ansca Corona\Corona Simulator\Preferences" /f /v debugBuildProcess /d 5
```

Before the build clean console and then copy log between backticks below
```
```

**Comment by Shchvova** [comment]
To build for windows you must run Corona Simulator on Windows

**Comment by VBLecturer** [comment]
Obviously... Thanks. I must have done it that way before, but overlooked it . Apologies but thanks.
