### ISSUE TITLE
[iOS iPhone]: Load local web files & resources in Webview for iPhones

### ISSUE THREAD

**Issue by usmandotmughal** [coronalabs/corona#466]
I am trying to load a local HTML file with **webview**(**WKWebView**) and it's not loading my local resources assets which I used in the HTML file. I am simply trying to play a video in **webview**. Strangely video is playing alright in simulators, Android, and iPad but not on the iPhones.

**Steps to reproduce the behavior:**
1. Make and Install a build of a sample project on any **iPhone**.

**Target platform and where build was made:**
 - Device: [e.g. All iPhone]
 - OS: [e.g. All iOS]

**Additional context**
The problem occurs only on iPhones.

[LocalHtmlLoad.zip](https://github.com/coronalabs/corona/files/9843797/LocalHtmlLoad.zip)

**Comment by solares** [comment]
Usman has filed an issue with Solar2D: 

https://github.com/coronalabs/corona/issues/466

**Comment by Shchvova** [comment]
Hello!
I changec code and everything seems to work now.
```lua
local webView = native.newWebView( _w, _h, _W, _H )
webView:setNativeProperty("allowsInlineMediaPlayback", true)
webView:setNativeProperty("mediaPlaybackRequiresUserAction", false)
webView:request( "video-sample/index.html", system.ResourceDirectory )
```

Setting native properties before the `:request`, since those are "configuration" properties, not properties of webview itself.
