### ISSUE TITLE
[android]: Action required for future builds - Google Play Message

### ISSUE THREAD

**Issue by AleCGames** [coronalabs/corona#468]
- Today I received an email from Google with the subject:
[Action Required] Remove the addApi(Drive.API) code from your apps that initialize the Google Drive Android API

I will show below the body of the email, but before I want to point that Google indicated that 3 of my games uses Google Drive API, nevertheless the three games that Google indica does not make any call to Drive API, just the common calls: to logged in to gpgs, submit score to leaderboards and show leaderboards.

After I read the email, I logged in to Google Cloud and disabled the Google Drive API from those 3 game projects, and after that I tested one of those games and none of the calls to gpgs worked. I mean, the user can not logged in to gpgs, leaderboards does not submit and you can not show leaderboards. So, I enabled the Google Drive API and bingo, all ok again. So, it seems that Solar2d calls to that API internally.

_Email from Google:_
Hello Google Developer,

We’re writing to let you know that we’ve found one or more of your apps continue to initialize the Google Drive Android API, which will be fully turned off on February 1, 2023. Impacted apps are listed at the end of this email.

**What does this mean for my organization?**
On December 6, 2018, we announced that we’re simplifying options for developers by [retiring the Google Drive Android API](https://notifications.google.com/g/p/AKWoLQjD8dqKd0Os5ydvCMhkFScaAbE5F7Ul-xrg5kEw53fxtS1KLAvK4JlCe8btwOqcpD2qZQkn6hqm1mrlkJgqhyOe3EJpxV0VLceUpsV5L3CyJtK-FqOrDFT51Q2JaZmJFxvWNvhF8ZD2NzwkH6ZdXXTl6ZdvYr_dZTOchcUFwNUf30k8SQHyb8iGif71Oq4eWczM2VrWINh7Jf5v4Ku8KBtgFBMqUjd8wj0QFXksbYJ6uovMu__62lD9YsZ2Qi3jUTrhwaRp9w4WrnBEa6NmaC4). Since the beginning of 2022, none of the Google Drive Android API calls are functional anymore. You might have unintentionally integrated with it in the past.

On February 1, 2023, the Google Drive Android API will be fully turned off. Any app that continues to initialize the Google Drive Android API will start to break.

**What do I need to do?**
Please remove the following code from the apps before February 1, 2023.

addApi(Drive.API)

Note: Even if your app doesn’t rely on Google Drive, your app’s functionality might be impacted if you connect to the Google Drive Android API.

**Impacted applications**

Your impacted projects are below:

1055772489579 (links-puzzle)
1096746989156 (true-or-false-biblical-2827741)
936254433935 (fill-multicolor-dots-puzzl-184)

Thanks for choosing Google Workspace.

**– The Google Workspace Team**

**Comment by scottrules44** [comment]
I just want to confirm, you are getting this warning with `plugin.gpgs.v2`?

**Comment by AleCGames** [comment]
With V2 and V1 too. I posted this issue on Solar2D forum and another developer (zutgames) is getting the same issue, also for V2 and V1

**Comment by scottrules44** [comment]
I working on updating the v2 plugin to the newest version and will try to work a param into the plugin to remove Google Drive Api but Google's "current" GPGS documentation mentions that drive scope(which is used currently in v2 and v1) is required for Snapshots/Saved games to work.

https://developers.google.com/games/services/android/savedgames#specifying_the_drive_scope

**Comment by scottrules44** [comment]
The changes were too much to try to update the v2 plugin to the newest version of the GPGS. The newest plugin(v3) makes using Drive api/scope optional. 

See https://docs.coronalabs.com/plugin/gpgs3/index.html

**Comment by AleCGames** [comment]
Hi @scottrules44 
Thank you for your job, but I really don't understand something. I was reading the Google documentation [here](https://cloud.google.com/blog/products/application-development/sync-google-drive-files-to-apps-using-the-drive-rest-api-bidding-farewell-to-the-drive-android-api) (please, take a look at this for a moment) and they said that starting febrary 2023 they will be retiring **Google Drive Android API**, and they add that **Drive REST API** will offer all of the same functionality as the **Drive Android API**. 

So, my question is: Why you implemented that the option of inserting _Drive API_ be optional? When you refer to _Drive API_ you mean **Google Drive Android API**? Because the last one will be unfuntional since febrary of this year.

**Comment by scottrules44** [comment]
@AleCGames Because with the according to the “current” Googles docs of GPGS they still require the Drive Scope for Snapshots 
https://developers.google.com/games/services/android/savedgames#specifying_the_drive_scope
