### ISSUE TITLE
[Android]  The low memory warning feature implemented on the Android platform  

### ISSUE THREAD

**Issue by zhiyangyou** [coronalabs/corona#471]
![lQLPJxbV7OPwVxjNAwfNBdKwxjxwxdcFsW0DX4_Et4CkAA_1490_775](https://user-images.githubusercontent.com/70576712/199461458-fae02295-23bd-4e19-a4b2-3bd7b2a39cb2.png)
Hi！
Android 12
[XiaoMi K50Pro ](https://zh.wikipedia.org/zh-hk/Redmi_K50)

**activityManager.getMemoryInfo(memoryInfo)**   This API seems to consume a lot of time. On some low-end machines, it may slow down the frame rate and increase power consumption?
https://github.com/coronalabs/corona/blob/78bbe702fcd7c8d2bf619ab64519d92a3ae9fc40/platform/android/sdk/src/com/ansca/corona/SystemMonitor.java#L169

**Comment by scottrules44** [comment]
I just tried removing this function and did notice little (if any) changes in power or memory. 

With method
<img width="1204" alt="Screenshot 2022-11-02 at 3 57 03 PM" src="https://user-images.githubusercontent.com/7820808/199591768-f7157827-b116-449b-8147-eabef6f7a499.png">

Without method
<img width="611" alt="Screenshot 2022-11-02 at 4 00 52 PM" src="https://user-images.githubusercontent.com/7820808/199591854-c611ea0b-478b-4f4c-852c-57ba5d712820.png">

**Comment by zhiyangyou** [comment]
https://docs.coronalabs.com/api/event/memoryWarning/index.html
 Runtime:addEventListener( "memoryWarning", listener ) 
 The description of this API may be outdated, this feature is available on Android. :)

**Comment by scottrules44** [comment]
@zhiyangyou even with that piece of code, I get the same result little to no change in power and memory. Will get this added to docs though.

**Comment by IlSui** [comment]
Hi, the doc is still outdated

**Comment by scottrules44** [comment]
> Hi, the doc is still outdated

Updated docs
