### ISSUE TITLE
[ios]:A valid provisioning profile for this executable was not found.

### ISSUE THREAD

**Issue by jalalimehdi** [coronalabs/corona#472]
Hi every one
When I want to Build for ios and copy to device 
Show this error

**Platforms involved**
Building on: macOS 13.0 (22A380)
Building for: iOS 

**Attach your build.settings**
[build.settings.txt](https://github.com/coronalabs/corona/files/9926239/build.settings.txt)
**Full build log**
ideviceinstaller encountered an error installing the app:

Installing 'pashmak.app' on Mehdi's_iphone ...
ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008015: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.qWjLY5/extracted/pashmak.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)
Uploading pashmak.app package contents... DONE.
Installing 'ir.programmingco.pashmak'
Install: CreatingStagingDirectory (5%)
Install: ExtractingPackage (15%)
Install: InspectingPackage (20%)
Install: TakingInstallLock (20%)
Install: PreflightingApplication (30%)
Install: InstallingEmbeddedProfile (30%)

Install: VerifyingApplication (40%)

**Comment by scottrules44** [comment]
Hi @jalalimehdi, you need a provisioning profile to get your app from Corona Sim -> iOS, this is an Apple Limitation not a Solar2D one. 
Read more here: https://docs.coronalabs.com/guide/distribution/iOSBuild/index.html
