### ISSUE TITLE
[PLATFORM]: runtime bug

### ISSUE THREAD

**Issue by mustafamsy** [coronalabs/corona#497]
- [YES] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

There is an issue with WebView in Device & Simulator.

The exact same issue is same as found here:
https://stackoverflow.com/questions/11155849/partially-colored-arabic-word-in-html

The issue with parsing in Chrome seems to have been resolved with Chrome’s new layout implementation LayoutNG
(https://www.chromium.org/blink/layoutng).

But when loading the local HTML in the device or simulator, the parsing issue remains unsolved.
And when loading the same HTML file in Chrome Desktop, the issue is not there.

**whole test project or build.settings**
Try loading this HTML in simulator and try in your desktop browser
https://jsfiddle.net/mustafamsy/6xk2bsnq/

**Comment by scottrules44** [comment]
Which devices are having this issue, Android, iOS, or Windows?
I tried on Mac sim, and it appears normal
<img width="942" alt="Screenshot 2023-04-23 at 1 04 32 AM" src="https://user-images.githubusercontent.com/7820808/233822736-69fb9c71-0ebf-477c-81ac-006e2acc0a4b.png">

[Test.zip](https://github.com/coronalabs/corona/files/11302941/Test.zip)

**Comment by mustafamsy** [comment]
This is still an issue on iPhone browser

**Comment by scottrules44** [comment]
> @scottrules44 This is still an issue on iPhone browser

I just tried this test project on my iPhone 14 pro running 16.3, this issue appears to be fixed it seems
![IMG_93AEA420516C-1](https://user-images.githubusercontent.com/7820808/233854572-01cd824d-5e0c-4e03-a9a1-ced1fa1e49c5.jpeg)
[Test.zip](https://github.com/coronalabs/corona/files/11304351/Test.zip)

**Comment by mustafamsy** [comment]
Scott, let me just correct one thing. The image you posted has an error.

The solution should be like this:
عربي

With all Arabic letter not separated as showed in in the last word in the image. 

The issue still not fixed as I just tried on my iPhone 14 pro.

**Comment by scottrules44** [comment]
![image](https://user-images.githubusercontent.com/7820808/233864836-a2668fb4-cb68-464a-ab4d-1978aa572077.png)

Well this looks like an Apple WebKit issue, not a Solar issue. It look the same in iOS Safari. Solar just uses Apple Webview.

**Comment by mustafamsy** [comment]
@scottrules44 Yes, only in Apple WebKit. I thought this is a Solar2D issue but it seems not as you highlighted.
