### ISSUE TITLE
Unity ads plugin not working on Android

### ISSUE THREAD

**Issue by mark-sgs** [coronalabs/corona#498]
With the latest unity ads plugin there is a bug. First load of app, init fires and there is a response so I load the waterfall. 

This is reported in console ` plugin.unityads.v4: 1.0.0 (SDK: 4.5.0)`

Restart the app and ads do not work at all.

This is reported in console `ERROR: unityads.setPersonalizedAds( bool ), init() should only be called once`

This is repeatable and exists on all devices with different versions of Android.  So far this problem is on 9, 10, 12 and 13 (I don't have an Android 11 device)

**Comment by scottrules44** [comment]
This is fixed with new update

**Comment by mark-sgs** [comment]
So what was the problem and why is it such a battle to get you to understand the bug?

**Comment by scottrules44** [comment]
I am not that familiar native.systemExit(). But it’s not the same force closing the app/putting it into a cold state or suspending the app. For the record I don’t regularly use an android phone, and mostly deep in the Apple iOS Ecosystem. So would never and million years thought to test native.systemExit. I don’t want to battle and I don’t think of that way but you should never assume people just know what your talking about especially without posting code and/or being “clear” about how to reproduce the issue

**Comment by mark-sgs** [comment]
You got a very clear use case with videos... just because you don't read what I put that is not my fault.

You have got to get a bit more professional with your testing/updates.

**Comment by Shchvova** [comment]
Please be constructive and respectful. This is neither.

**Comment by mark-sgs** [comment]
You have no idea how frustrating it is trying to explain to players why something doesn't work.  Try to see the other side of things.

If I say there is a bug, I mean there is a bug.... I don't expect to have to battle this.  We are all on the same side surely?
