### ISSUE TITLE
Admob crashing on Amazon

### ISSUE THREAD

**Issue by lmgualandi** [coronalabs/corona#506]
I'm making a build for Amazon after a long time and the Admob plugin is crashing upon calling admob.init
I'm setting target app store to Amazon and running on a Fire tablet.
 
Stack trace:

 ERROR: Runtime error
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/ads/RequestConfiguration$Builder;
 Java Stack Trace:
      plugin.admob.LuaLoader$Init.invoke(LuaLoader.java:563)
      com.ansca.corona.JavaToNativeShim.nativeRender(Native Method)
      com.ansca.corona.JavaToNativeShim.render(JavaToNativeShim.java:205)
      com.ansca.corona.Controller.updateRuntimeState(Controller.java:364)
      com.ansca.corona.graphics.opengl.CoronaGLSurfaceView$CoronaRenderer.onDrawFrame(CoronaGLSurfaceView.java:434)
      com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1625)
      com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1380)
 stack traceback:
      [C]: in function 'init'
      ?: in function 'initialize'
      ?: in function '?'
      ?: in function '_listener'
      ?: in function '?'
      ?: in function <?:189>
 
 
Stack trace on Crashlytics:

 Non-fatal Exception: java.lang.Exception: ?:0: attempt to index field '?' (a nil value)
       at plugin.firebaseCrashlytics.LuaLoader$init$1.invoke(LuaLoader.java:225)
       at com.ansca.corona.CoronaEnvironment.invokeLuaErrorHandler(CoronaEnvironment.java:434)
       at com.ansca.corona.NativeToJavaBridge.callInvokeLuaErrorHandler(NativeToJavaBridge.java:306)
       at com.ansca.corona.JavaToNativeShim.nativeRender(JavaToNativeShim.java)
       at com.ansca.corona.JavaToNativeShim.render(JavaToNativeShim.java:205)
       at com.ansca.corona.Controller.updateRuntimeState(Controller.java:364)
       at com.ansca.corona.graphics.opengl.CoronaGLSurfaceView$CoronaRenderer.onDrawFrame(CoronaGLSurfaceView.java:434)
       at com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1625)
       at com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1380)

**Comment by scottrules44** [comment]
Admob is not supported on Amazon due to Google Mobile Services not part of Fire OS.

**Comment by lmgualandi** [comment]
Do you know exactly since when? Because I have a working version of my app on the Amazon store currently downloadable displaying Admob ads. Last updated in 2019.
Apparently it works if you include Google Play Services bundled into the app as a dependency.
Do you have any idea of how Google Services was included back then or if I use a very old version of the Admob plugin it would work?
I tried force including plugin.gpgs.v2 or plugin.gpgs on the buildsettings but it doesn't help.

**Comment by Shchvova** [comment]
If you have a device to try it on I can suggest a fix. Download [this](https://github.com/coronalabs/com.coronalabs-shared.google.play.services.ads/blob/master/plugins/2022.3672/android/corona.gradle) file into your AndroidResources. See how it goes.

**Comment by lmgualandi** [comment]
Hi Vlad, yes it worked! Not crashing and ads being displayed. Thanks

**Comment by scottrules44** [comment]
Going to go ahead and close this since support is added in the newest verison of admob plugin
