### ISSUE TITLE
[Simulator]: Screenshots for some resolutions don't have exact size of the simulator resolution

### ISSUE THREAD

**Issue by OutlineDev** [coronalabs/corona#515]
**Describe the bug**
Screenshots for some resolutions don't have exact size of the simulator resolution.

**To Reproduce**
- Run simulator (in different resolutions)
- Save screenshot with: display.save(screen, {filename=screenshotName, baseDir=system.TemporaryDirectory, captureOffscreenArea=true})

** Samples **
* iPad 12,9“ - 2732 x 2048 Pixel - Standard Device --> width of screenshot is 1px plus (2733 x 2048)
* iPhone Plus 5,5“ - 2208 x 1242 Pixel - Custom Device --> width of screenshot is 1px minus (2207 x 1242)
* iPhone XS Max 6,5“ - 2688 x 1242 Pixel - Custom Device --> width of screenshot is 1px plus (2689 x 1242)

**Comment by ggcrunchy** [comment]
This seems to agree with the theory I mention [here](https://forums.solar2d.com/t/display-capture-adds-a-1-pixel-white-line-on-right-and-bottom-edge/354584/11) about overrounding.

I can add some further commentary about the white line he describes, as well as some additional issues, but probably not immediately relevant. (Written in another issue on a private repository.)

**Comment by mark-sgs** [comment]
This has been a bug for years.  just up each dimension by 4px and trim in PS.
