### ISSUE TITLE
ERROR: Builder failed: ld: warning: object file (/Users/xxx/Desktop/xxx.app/.build/plugin.notifications.v2.firebase/FBLPromises.framework/FBLPromises(FBLPromises_vers.o)) was built for newer iOS version (9.0) than being linked (8.0)

### ISSUE THREAD

**Issue by wwwbetyar** [coronalabs/corona#516]
Hello

I got an exception on 2023.3686 version when I wanted to build : ERROR: Builder failed: ld: warning: object file (/Users/xxx/Desktop/xxx.app/.build/plugin.notifications.v2.firebase/FBLPromises.framework/FBLPromises(FBLPromises_vers.o)) was built for newer iOS version (9.0) than being linked (8.0)
iOS sdk : 16.2 Metal
Mac mini M1

thank you

**Comment by scottrules44** [comment]
Is there any more to the output and can you list any plugin you are using?

**Comment by wwwbetyar** [comment]
Hi.

This is all plugins, but if I comment out the plugin.notifications.v2.firebase then I can build it :
`["plugin.androidPreview"] = { 
               publisherId = "tech.scotth",
               marketplaceId = "ax5s9u"
          },
		["plugin.qrscanner"] = spiralcodestudio_plugin('qrscanner'),
		["CoronaProvider.native.popup.quickLook"] =
          {
            publisherId = "com.coronalabs",
            supportedPlatforms = { iphone=true }
          },
          ["plugin.notifications.v2.firebase"] =
          {
            publisherId = "com.coronalabs"
          },
		["shared.google.play.services.gcm"] =
          {
            publisherId = "com.coronalabs",
            supportedPlatforms = { android=true }
          },
          ["plugin.zip"] =
          {
            publisherId = "com.coronalabs"
          },

attached build info
[solar2derror.txt](https://github.com/coronalabs/corona/files/10688194/solar2derror.txt)

**Comment by Shchvova** [comment]
Seems like a bunch of undefined symbols

swift_Concurrency'â€¨Undefined symbols for architecture arm64:â€¨  "_$s7ElementSTTl", referenced from:â€¨      l_got.$s7ElementSTTl in FirebaseCoreInternal(RingBuffer.o)â€¨  "_$s8AllCasess12CaseIterablePTl", referenced from:â€¨      l_got.$s8AllCasess12CaseIterablePTl in FirebaseCoreInternal(Heartbeat.o)â€¨  "_$s8Dispatch0A13WorkItemFlagsVMa", referenced from:â€¨      _$s20FirebaseCoreInternal16HeartbeatStorageC17readAndWriteAsync5usingyAA16HeartbeatsBundleVSgAHc_tF in FirebaseCoreInternal(HeartbeatStorage.o)â€¨      _$s8Dispatch0A13WorkItemFlagsVACs10SetAlgebraAAWl in FirebaseCoreInternal(HeartbeatStorage.o)â€¨      _$sSay8Dispatch0A13WorkItemFlagsVGSayxGSTsWl in FirebaseCoreInternal(HeartbeatStorage.o)â€¨

**Comment by scottrules44** [comment]
My mistake I forgot to include swift libs with notification v2, this should be fixed with [v16](https://github.com/coronalabs/com.coronalabs-plugin.notifications.v2.firebase/releases/tag/v16)

**Comment by wwwbetyar** [comment]
Good job ! thanks it works
