### ISSUE TITLE
[HTML5]: Text rendering causes "Total canvas memory use exceeds the maximum limit" on Safari.

### ISSUE THREAD

**Issue by bmrpeal** [coronalabs/corona#521]
- [x] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**Describe the bug**
A simple app with a not very large list of text options is able to exhaust Safari's Canvas memory, because every "display.newText" call draws a full size 2D canvas on memory (in my test case, for an iPhone 6 plus, one 980x1470 canvas that consumes 5,83MB of memory for each display.newText call).

**To Reproduce**

1. Create a simple app with a list of separated text elements (15 or 20 text elements, a typical scrollView list, although every display.newText will cause this, no matter if inserted into a scrollView, a group or anything else), each one with a tap listener that will create a new list of elements with text.
2. Build and run the app from **index-debug.html** from any iPhone (this will show the bug quickly, because index-debug scales at "retina" sizes).
3. Connect the iPhone by wire to a mac, open Safari, Developer Menu, and show the inspector of the device connected. (If it doesn't appear, make sure you've activated the inspector in the device setting from the Safari's advanced options).
4. From the Mac's Safari inspector, go to the "Graphics" tab, start using the web app in the iDevice, and see how every text is rendered in a 2D canvas, quickly fulfilling the canvas memory of the device (a quarter of the total device's RAM).
5. If your running an iPhone with 1GB of Ram, by just tapping an element from the first list, and while the app tries to create the second list, it will fire the "total canvas memory use exceeds the maximum limit". 20 text elements * 5,83Mb each = 116MB. A second list will be 232... which with the rest of elements (LUA code, the WebGL canvas, etc), will exhaust the canvas memory. And dead end for the app.

**Target platform and where build was made:**
 - Device: [iPhone6Plus, iPhone 6, iPhone 7, etc]
 - OS: [since iOS12 to iOS 16.3 (until i know)]

**Additional context**
If you open the app from the normal "index.html", due to the viewport, it will cost a bit more to stress the canvas memory (due to the lower resolution of rendering), but problem still exists and is a matter of little time to appear.

**whole test project or build.settings**
You can see a better explanation of the bug and screenshots in the following discord message: https://discord.com/channels/721785436195782677/724637134115438714/1077321698908590160

**Comment by bakeinflash** [comment]
Is the issue Safari specific?
Can you please share a simple test app which demonstrates the issue?

**Comment by bmrpeal** [comment]
Seems to be Safari specific, yes, anyway I need to test in on Android to be 100% sure. In the following days I'll prepare a simple demo project to demonstrate and reproduce the issue.

**Comment by bmrpeal** [comment]
Here you can check the real project running (on debug mode): 

https://www.telecarta.app/index-debug.html

**Comment by bakeinflash** [comment]
I have faced Safari Error "A problem repeatedly occurred with ..." trying to open https://www.telecarta.app/index-debug.html and many other web sites. Safari opens some web pages and does not many others. Strangely.

**Comment by bakeinflash** [comment]
Downgraded to OSX Catalina. Safari works now as expected.

I did not see any issues. "The problem comes from the very canvas dev-tool. It is the one culprit that will keep references to these canvas elements and prevent the Garbage-Collector to do its work correctly." 
Look at: https://stackoverflow.com/questions/58438276/cannot-remove-canvas-elements-from-memory-that-are-created-but-never-appended-to
