### ISSUE TITLE
Google SSO plugin crash

### ISSUE THREAD

**Issue by mark-sgs** [coronalabs/corona#524]
Sometimes there is a crash immediately after selecting an account on the SSO overlay.

<img width="659" alt="image" src="https://user-images.githubusercontent.com/61833594/221854551-3d4cee5d-2ee0-4973-98e7-f236d7a83545.png">

<img width="556" alt="image" src="https://user-images.githubusercontent.com/61833594/221854857-0b8e1715-f989-42bb-9879-c9c588ed5e3b.png">

This was repeatable even after a device restart (P30 pro with 8GB RAM).  The only thing that fixed it was clearing data for Google Services app.

There is also (still) the problem with the plugin generating an ANR.  It seems focus is not completely passed back to the app leaving it in an unresponsive state causing an ANR like this.

![WhatsApp Image 2023-02-28 at 12 39 48](https://user-images.githubusercontent.com/61833594/221859354-65d60df4-9580-42cf-9abe-b3b75a5459ff.jpg)

Can the plugin be made more robust to handle error states as opposed to crashing/causing ANRs - such as trapping NullPointers?

**Comment by scottrules44** [comment]
I will add more traps for null pointers, but at first, glace looking at your logged line number vs the source code tells me the plugin being used might be an older version. Regardless will look into it

Also, Google SSO is a personal plugin of mine(hence the `tech.scotth` publisherId) and not a Corona/Solar2D plugin(the Solar2D team does not have access to the source code and the ability to update the plugin). So this is not the appropriate outlet to file a bug report. 

Please file a bug report here: https://goo.gl/forms/QjOJsFGghSEQqkJW2

**Comment by mark-sgs** [comment]
I only built the app today so why would the plugin be out of date?  How can I check?

**Comment by scottrules44** [comment]
I just pushed out an update, and you should get a message in the logs saying, "Init Google Sign In Plugin Verison: 2.6" when you .init

**Comment by mark-sgs** [comment]
Just did a new build but there is nothing in the log.

```
03-01 11:15:35.056  8408  8595 V Corona  : > Class.forName: plugin.googleSignIn.LuaLoader
03-01 11:15:35.057  8408  8595 V Corona  : < Class.forName: plugin.googleSignIn.LuaLoader
03-01 11:15:35.057  8408  8595 V Corona  : Loading via reflection: plugin.googleSignIn.LuaLoader
03-01 11:15:35.060  8408  8595 V Corona  : > Class.forName: plugin.unityads.v4.LuaLoader
03-01 11:15:35.060  8408  8595 V Corona  : < Class.forName: plugin.unityads.v4.LuaLoader
03-01 11:15:35.060  8408  8595 V Corona  : Loading via reflection: plugin.unityads.v4.LuaLoader
```

**Comment by scottrules44** [comment]
What does your build.settings look like for including the Google Sign In Plugin?

**Comment by mark-sgs** [comment]
Just the normal...

```      ["plugin.googleSignIn"] =
        {
          publisherId="tech.scotth",
          marketplaceId = "ydlbgq",         
          supportedPlatforms = { android = true, iphone = true }
        },

**Comment by scottrules44** [comment]
You may try rebuilding now; I was not printing to the "Corona" flag

**Comment by scottrules44** [comment]
With 2.8 (just pushed out a few minutes ago) I added NullPointers traps
