### ISSUE TITLE
Apple Distribution certs are not working

### ISSUE THREAD

**Issue by arkadi** [coronalabs/corona#53]
when i try build with "Apple Distribution" certificate  and upload in Appstore get error.

> ITMS-90426: Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.
Corona SDK build version 2020.3582 (2020.4.19) / Xcode Version 11.4.1 / iOS SDK 11.4
when build with "iOS App Distribution" everything fine.

**Comment by joehinkle11** [comment]
I'm having this issue with a native app (without Corona) right now...
