### ISSUE TITLE
windows installer lincence from main site needs to be updated

### ISSUE THREAD

**Issue by acnologia000** [coronalabs/corona#54]
licence of windows installer of corona does not shows MIT licence and poses usage restrictions that should not actually exist

**Comment by Shchvova** [comment]
Sorry. Binary distributions are licensed differently for now. We'll fix it soon.

**Comment by acnologia000** [comment]
Is it safe to use it @Shchvova ?

**Comment by Shchvova** [comment]
Yes. Company Corona Labs will close May 1st. Project would move to be completely OpenSource after that, and MIT licensed builds would be built.
However existing built binaries are free to use as you want for making & distributing games.
