### ISSUE TITLE
MacOS: crash with display.capture()

### ISSUE THREAD

**Issue by Shchvova** [coronalabs/corona#545]
`display.capture` causes the simulator to crash on Corona version 3683 and newer. I am on a MacOS Ventura 13.3. I have a simple project with just the following code in main.lua
```lua
display.setDefault( "background", 1 )
local staticImageBack = display.newRect(400,400,400,400)
staticImageBack:setFillColor(1,0,0)
display.capture(staticImageBack, {captureOffscreenArea=true, saveToPhotoLibrary=false})
```

When run on version 3683 the simulator crashes instantly (90% of times...which is weird) while on older Corona versions it runs fine.

https://user-images.githubusercontent.com/130387/231262190-0f066365-a2b3-4462-8aae-767dcd4ee381.mov

[Display_Capture_Crash_on_v3683.zip](https://github.com/coronalabs/corona/files/11203935/Display_Capture_Crash_on_v3683.zip)

Created bug report from: [discord message](https://discord.com/channels/721785436195782677/724637134115438714/1094311572823887894).

**Comment by scottrules44** [comment]
I going to reopen this because I was still able to reproduce this error with new version, I under the issue a little better now, this issue most times but not always

**Comment by scottrules44** [comment]
^See Video for proof of fix (lol)
<iframe width="560" height="315" src="https://www.youtube.com/embed/05I7WQbWozk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
