### ISSUE TITLE
system.activate("multitouch") crashes apps built with Solar2D 2023.3689 

### ISSUE THREAD

**Issue by elpida-v** [coronalabs/corona#568]
system.activate("multitouch") causes apps to crash when the screen is touched. No button is required. As soon as you touch anywhere on screen the apps crash. If you remove system.activate("multitouch"), issue is gone.

This bug was introduced in **Solar2D 2023.3689** (in previous versions there is no problem). It happens on iOS devices but not on the simulator. I haven't tested on Android.

1. Create a simple project with only this code in main.lua -> `system.activate("multitouch")`
2. Build for iOS with Solar2D 2023.3689
3. Run on the iOS device and touch anywhere on the screen
4. App crashes

 - I built on macOS Ventura 13.3
 - My iPhone is iOS 16.3
 - Solar2D 2023.3689 
 - Xcode 14.3 (@scottrules44 tested on 14.2 and there was no issue there)

Sample project attached.

[Crash on touch.zip](https://github.com/coronalabs/corona/files/11376509/Crash.on.touch.zip)

**Comment by scottrules44** [comment]
^ Note this also only occurs with Xcode 14.3 (no issue with Xcode 14.2)

**Comment by Shchvova** [comment]
This should be fixed in next build (coming soon)
