### ISSUE TITLE
Update  XmlRpc4Win to a more recent version

### ISSUE THREAD

**Issue by ZhilkinSerg** [coronalabs/corona#58]
Currently merged XmlRpc4Win version contains some bugs which were fixed in upstream repo. For example, compare 

https://github.com/coronalabs/corona/blob/a77b30fd92b712aeb8f11bce6d6b35683aa51cfe/external/winxmlrpc/TimXmlRpc.cpp#L694-L699

and

https://github.com/drtimcooper/XmlRpc4Win/blob/72564d4c3e98dd1b01610e81974237944211d528/TimXmlRpc.cpp#L677-L682 (fixed in https://github.com/drtimcooper/XmlRpc4Win/commit/0d42da505c83bfacad0e9ab2619e2ce0a825c126).

**Comment by Shchvova** [comment]
Thanks. Does this cause some issue in runtime? We are planning removing XmlRpc completely, since we won't be needing communicating with developer.coronalabs.com anymore, because it is going away.
