### ISSUE TITLE
App Store must be built with the iOS 16.1 SDK or later

### ISSUE THREAD

**Issue by Andrey5045** [coronalabs/corona#582]
While building for iOS on github Action there was a message:

Error Messages:
		ERROR ITMS-90725: SDK version issue. This app was built with the iOS 15.0 SDK. All iOS and iPadOS apps submitted to the App Store must be built with the **iOS 16.1 SDK** or later, included in Xcode 14.1 or later.

**Comment by Shchvova** [comment]
Oh.. For some reason I thought you're using [app store build automation](https://github.com/solar2d/demo-app-store-automation). Sorry, my bad. To fix your problem update to latest Xcode. You can have several Xcode side-by-side but then you have to switch between them with something like `sudo xcode-select -s /Applications/Xcode_14.3.app` (I renamed [downloaded](https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_14.3.1/Xcode_14.3.1.xip) latest xcode to Xcode_14.3 after unpacking).
Useful site with download links for Xcode: https://xcodereleases.com/
