### ISSUE TITLE
[iOS]: Scott's Firebase Analytics and Crashlytics plugins crashing on iOS 12

### ISSUE THREAD

**Issue by lmgualandi** [coronalabs/corona#596]
I just released an update and started receiving lots of iOS 12 crashes.
I then paused the phased release and managed to find a device with iOS 12 to test.
Its crashing right on startup and only when I remove both the Crashlytics and Analytics plugins the app launches fine.
Tested with Solar2d 3692 (also tested with older versions 3681 and 3685 and same behaviour).
Those plugins were working before but the app wasn't updated for a long time.

On the documentation it's saying it's compatible with iOS 10+
https://scotth.tech/plugin/firebaseAnalytics
https://solar2dmarketplace.com/plugins?FirebaseCrashlytics_tech-scotth

**Comment by scottrules44** [comment]
Should be fixed now, thanks Scott

**Comment by lmgualandi** [comment]
It's failing to build now:

ERROR: Builder failed: ld: framework not found FirebaseCoreDiagnostics

**Comment by scottrules44** [comment]
> It's failing to build now:
> 
> ERROR: Builder failed: ld: framework not found FirebaseCoreDiagnostics

Should be fixed now, sorry about that

**Comment by lmgualandi** [comment]
Seems to be working now. Building fine. No longer crashing on iOS 12. Thanks!
