### ISSUE TITLE
about lua version

### ISSUE THREAD

**Issue by yybbwc** [coronalabs/corona#598]
It is indeed surprising that Solar2D is still using Lua 5.1 in the year 2023. Is there really no hope for upgrading Solar2D to a newer version of Lua?

Lua 5.3 has been available for 8 years already, and Lua 5.4 has been out for 3 years. As of this year, Lua 5.4.6 is already available, which offers significantly improved performance over Lua 5.1. It also features generational garbage collection and even supports Unicode variable names.

**Comment by labolado** [comment]
Hope it can be included in the plan
