### ISSUE TITLE
Quit after Deauthorize on macOS Catalina

### ISSUE THREAD

**Issue by MrNeoNOS** [coronalabs/corona#60]
It's say.
An Internet connection is required to authorize first time use.

When reopenning Corona Simulator.

**Comment by imwenkang** [comment]
same issues here

**Comment by micheg** [comment]
The same problem on OSX 10.15.4.
Authorization, but each reboot only gets the window:
And there is no possibility to go back to the login window.

**Comment by coronarob** [comment]
What version of Corona are. you running?

**Comment by Shchvova** [comment]
This is intended. Deauthorize & corona authorization would go away when offline builds are stable.

**Comment by MrNeoNOS** [comment]
> What version of Corona are. you running?

Corona 2020.3590

**Comment by daveyang** [comment]
Having the same issue here and it quits after the dialog box saying it needs internet connection. So 3590 won't run if local building is enabled. Also on macOS 10.15.4.

**Comment by arkadi** [comment]
when i Deauthorize and then restart simulator. i press cancel in login page and  get this error 
"Could not authorize this computer to use Corona Simulator
An Internet connection is required to authorize first time use."  this message i got in every times when i start Corona simulator

**Comment by jdsmedeiros** [comment]
Here also happens the same error, but I downloaded build 3582, I log in to build 3582, I remove it, then I open build 3590 and the simulator works normally logged in again! I just haven't tested the creation of the apk or ipa.

**Comment by kwiksher** [comment]
I added "allowOfflineMode" in com.coronalabs.Corona_Simulator.plist. It is placed in ~/Library/Preferences. The boolean value is "YES". Then deauthorized and restarted Corona simulator. Then canceled the login enabled <offline user>

**Comment by arkadi** [comment]
> I added "allowOfflineMode" in com.coronalabs.Corona_Simulator.plist. It is placed in ~/Library/Preferences. The boolean value is "YES". Then deauthorized and restarted Corona simulator. Then canceled the login enabled the offline mode.

this  is good solution. this is works for me.

**Comment by Shchvova** [comment]
Thanks! This is a leftover from the testing I did. Will be gone in next build.
```
defaults write com.coronalabs.Corona_Simulator  allowOfflineMode -bool YES
```

**Comment by MrNeoNOS** [comment]
> Thanks! This is a leftover from the testing I did. Will be gone in next build.
> 
> ```
> defaults write com.coronalabs.Corona_Simulator  allowOfflineMode -bool YES
> ```

It's work!!
