### ISSUE TITLE
jpg files not shown on ios 17

### ISSUE THREAD

**Issue by PaoUNetWork** [coronalabs/corona#604]
The Player run the game on ios system which is below ios 17 is normal , when the player upgrade to ios 17, the jpg file are not shown on  game .

**Comment by scottrules44** [comment]
I just installed iOS 17 beta and I can see jpg files no problem (on metal and OpenGL). Are you able to sent a sample project which this can be reproduced?

**Comment by scottrules44** [comment]
Closing due no response
