### ISSUE TITLE
[IOS]: Run CoronaCards with Metal

### ISSUE THREAD

**Issue by ArkeshGKalathiya** [coronalabs/corona#612]
- [x ] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**Describe the bug**
I have integrated CoronaCards with Flutter SDK, and there is weird bug whenever app is brought into foreground, it shows black flash.

I searched forum, and there is one bug regarding this and the solution is to use Metal backend. 

So is there any way to use CoronaCards with Metal? ( I checked and it uses GLKView )

**Comment by ArkeshGKalathiya** [comment]
@Shchvova

**Comment by Shchvova** [comment]
Why spam?

**Comment by Shchvova** [comment]
[CoronaCards-angle.framework.zip](https://github.com/coronalabs/corona/files/12444706/CoronaCards-angle.framework.zip)
Hello. Please see if this works for you at all. You can rename framework and file in it to be a drop-in replacement.

**Comment by ArkeshGKalathiya** [comment]
@Shchvova  Thanks for getting back so quickly.

I have following errors when integrating the file.

<img width="1039" alt="Screenshot 2023-08-26 at 8 31 36 AM" src="https://github.com/coronalabs/corona/assets/28758546/db219a64-7408-474d-baaa-6ac343f1048d">

And here is my podspec configuration

<img width="857" alt="Screenshot 2023-08-26 at 8 33 24 AM" src="https://github.com/coronalabs/corona/assets/28758546/86435643-d4ea-4b54-be39-164c54575cb8">

**Comment by ArkeshGKalathiya** [comment]
@Shchvova 

It's been resolved now. I had to do extra step regarding renaming. For anyone else stumbling into this in future, here it is.


Just rename shortcut inside framework to CoronaCards as well. ( If you are renaming from CoronaCards-angle to CoronaCards )

<img width="534" alt="Screenshot 2023-08-26 at 8 40 05 AM" src="https://github.com/coronalabs/corona/assets/28758546/526e8d54-e71e-4c5f-83d1-27b99cbe312d">

**Comment by Shchvova** [comment]
That is what I meant by renaming file inside ;)

**Comment by Shchvova** [comment]
I will add it to the next build. For now use the file I attached.
