### ISSUE TITLE
2020.3590 Corona Simulator - Build for Windows Desktop

### ISSUE THREAD

**Issue by kwiksher** [coronalabs/corona#62]
Offline build did not show Build dialog after selecting Build > Windows

It needs the same if-condition change as OnBuildForAndroid to build for Windows Desktop app. 

Applied the same change to CSimulatorView::OnBuildForWin32() and the offline build is succeeded. The build dialog appears now. 

VS2017 there are some caveats to build through 
* external/ALmixer/Isolated/DirectX.cpp  added  #include <mfidl.h>
* Rtt_PlatformAppPackager.cpp saved as UTF-8 with BOM
* Rtt_winPlatformServices.cpp saved as UTF-8 with BOM
    * #include <dpapi.h>

P.S.
I use tinyfiledialogs plugin. I put it data.tgz in the following folder and the simulator works fine but the build does not copy it to myApp.Win32 folder, so I manually copied the dll to the folder.    

* ~\AppData\Roaming\CoronaPlugins\com.xibalbastudios\plugin.tinyfiledialogs\win32-sim\data.tgz

**Comment by Shchvova** [comment]
thanks. I'll figure it our over the week.

**Comment by Shchvova** [comment]
This should be fixed in latest build 3591. Thanks for report
