### ISSUE TITLE
[PLATFORM]: runtime bug

### ISSUE THREAD

**Issue by SliderApp** [coronalabs/corona#626]
- [x ] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**Describe the bug**
CoronaCards crashes in iOS app when building with Xcode15 for iOS17.

We wanted to see if there’s something specific we’re doing in our project that’s causing the crash or if CC is just broken with the iOS17. The simple sample project is cashing when launching Corona so it appears CC needs some kind of update.

In our sample CoronaCards will crash right after launching, it draws one frame.

When building with Xcode14 with device support files, it installs and works on iOS17 without the crash

Here is a screenshot of the crash:
![Screenshot 2023-09-29 at 11 21 31 AM](https://github.com/coronalabs/corona/assets/29762135/a00dfbc5-6357-4422-b7ca-69e6a8881408)

**To Reproduce**
Install iOS17 and xCode15
Run the app and it will crash

Here is a link to the sample project (you’ll need a valid license to run it, we removed ours for security reasons). Run the app and it will crash immediately.

https://www.dropbox.com/scl/fi/3patf1p94udh67q973iug/sample-ios-ChildView-master-few-small-changes.zip?rlkey=7yomgvhmoweyxogxoa0hewmz8&dl=0

**Target platform and where build was made:**
 - Device: [iPhone13]
 - OS: [iOS17]

**Additional context**
We were able to get our app running from Xcode 15 (but, we had to add the linker flag "-ld64" to fix an initial build error)

If you would like to install using Xcode14 with an iOS17 device for comparison: run defaults write com.apple.dt.Xcode DVTEnableCoreDevice enabled. TIP:  you have to run it from time to time in terminal because it appears it disables at some point 

**whole test project or build.settings**
[Please attach project your issue can be reproduced on to speed up debugging](https://www.dropbox.com/scl/fi/3patf1p94udh67q973iug/sample-ios-ChildView-master-few-small-changes.zip?rlkey=7yomgvhmoweyxogxoa0hewmz8&dl=0)

**Comment by Shchvova** [comment]
please try again with latest release.

**Comment by SliderApp** [comment]
@Shchvova confirming that this fixed the issue for us. Thank you.
