### ISSUE TITLE
2020.3590 Corona Simulator - Windows fails zip uncompress 

### ISSUE THREAD

**Issue by kwiksher** [coronalabs/corona#63]
A simple unit test to uncompress a zip failed in Corona simulator of Windows 2020.3590. Mac is OK.

[test_zip.zip](https://github.com/coronalabs/corona/files/4578258/test_zip.zip)

P.S. 
I tried to build plugin-source-zip with VS 2017 but failed and I don't see how to solve it yet.
* lua_wremove is redefined in corecrt_io.h
* lua_wrename is redefined  in corecrt_io.h

When I put the  lua.dll and plugin_zip.dll of 2018.3326 into my win32 app built with 2020.3590, it seems working but the combination of lua.dll of 2020 + plugin_zip.dll of 2018.3326 is not working.

**Comment by Shchvova** [comment]
Thanks. Zip plugin needs updating. Also there is a problem because currently it's linked with old visual studio version. Fix is coming soon.

**Comment by HYbutterfly** [comment]
I have this problem, too

**Comment by Shchvova** [comment]
Hello. I just built new zip plugin. May I ask you to re-test this?

**Comment by Shchvova** [comment]
This should be fixed now.
