### ISSUE TITLE
2020.3590 Corona Simulator - Missing Console.

### ISSUE THREAD

**Issue by micheg** [coronalabs/corona#64]
On Mac OSX Catalina since I activated offline builds, the console seems to have disappeared. Clicking on "console" from the menu displays has no affection.
Starting the app from the terminal I get:
"2020-05-05 14: 39: 27.817 Corona Simulator [1582: 120051] CoronaConsole seems to have vanished ... switching to syslog"

**Comment by Shchvova** [comment]
Hm. Could you try to log out or reboot your Mac? It seems that sometimes coronaConsole keeps dangling and new one isn’t opening up. M

**Comment by micheg** [comment]
Nothing even after the restart...

**Comment by daveyang** [comment]
Having the same issue with the Console not showing when the external monitor is connected. It showed up once after I deleted com.coronalabs.CoronaConsole.plist in ~/Library/Preferences/ but the problem comes back after launching the simulator a second time.

**Comment by arkadi** [comment]
i have same situation. i am using build 3591

**Comment by arkadi** [comment]
same problem in 3595 build

**Comment by arkadi** [comment]
in last build after restart everything working fine.

**Comment by Shchvova** [comment]
This should be fixed in #e257d4aeada59fd209a3f1cd4ccb1361004ee450
