### ISSUE TITLE
Build for Amazon - plugin.applovinMax.Chartboost causes Fail

### ISSUE THREAD

**Issue by sbullock** [coronalabs/corona#651]
Building on MacOS 13.0.1
Building for Android -- Amazon Store
Building with either Solar2D Build #3696 or #3699 (both can reproduce this)

Steps to reproduce on 11/26/26:

A) Build with "plugin.applovinMax" and "plugin.applovinMax.Chartboost".

B) Build fails with this error:

       **FAILURE: Build failed with an exception.**
                    
                    * What went wrong:
                    Execution failed for task ':App:checkReleaseAarMetadata'.
                    > Could not resolve all files for configuration ':App:releaseRuntimeClasspath'.
                       > Could not find com.chartboost:chartboost-sdk:9.4.1.
                         Searched in the following locations:
                           - https://dl.google.com/dl/android/maven2/com/chartboost/chartboost-sdk/9.4.1/chartboost-sdk-9.4.1.pom
                           - https://jcenter.bintray.com/com/chartboost/chartboost-sdk/9.4.1/chartboost-sdk-9.4.1.pom
                           - file:/Users/steve/Library/Application Support/Corona/Native/Corona/android/lib/gradle/chartboost-sdk-9.4.1.jar
                           - file:/Users/steve/Library/Application Support/Corona/Native/Corona/android/lib/gradle/chartboost-sdk.jar
                           - file:/Users/steve/Library/Application Support/Corona/Native/Corona/android/lib/Corona/libs/chartboost-sdk-9.4.1.jar
                           - file:/Users/steve/Library/Application Support/Corona/Native/Corona/android/lib/Corona/libs/chartboost-sdk.jar
                           - https://repo.maven.apache.org/maven2/com/chartboost/chartboost-sdk/9.4.1/chartboost-sdk-9.4.1.pom
                         Required by:
                             project :App > com.applovin.mediation:chartboost-adapter:9.4.1.0

C) If I remove the "plugin.applovinMax.Chartboost" from my build (simply comment it out), the app will build successfully with no error.

D) In experimenting, I took both of the plugins back one version to versions v14 and v4. Snippet of build.settings below 

			["plugin.applovinMax"] =
			        {
			            publisherId = "com.solar2d",
				    supportedPlatforms = { ["android-kindle"] = true },
				    version = "v14",
			        },
			["plugin.applovinMax.Chartboost"] = 
				{
				    publisherId = "com.solar2d",
				    version = "v4",
				},

E) The app built and ran without errors when I dropped each of these plugins back by one version.

My conclusion is that the newer "plugin.applovinMax.Chartboost" is calling for something it is not finding.

Steve Bullock

**Comment by scottrules44** [comment]
This has been patched
