### ISSUE TITLE
media.playVideo crashes when video closes (95% of times)

### ISSUE THREAD

**Issue by elpida-v** [coronalabs/corona#653]
**Describe the bug**
media.playVideo crashes on iOS most of the times when you close the video. Behavior also present in Solar 2D sample project Media/VideoPlayer.

**Steps to reproduce the behavior**
1. Build and install the sample project found in "Corona-3700/SampleCode/Media/VideoPlayer" on an iPhone 
2. Click on 'Play Video'
3. Wait for the video to start playing
4. Tap on the x button to close the video
5. The app crashes 95% of times

**Target platform and where build was made**
 - Device 1: iPhone 11 Pro Max, iOS 17.1.1
 - Device 2: iPhoneXs Max, iOS 16.3

**Solar2D versions**
Built with Solar2D 2023.3770 and 2023.3691

**Sample project**
Applications/Corona-3700/SampleCode/Media/VideoPlayer
Applications/Corona-3700/SampleCode/Media/VideoPlayer

**Screen recording of crash**
https://github.com/coronalabs/corona/assets/59620078/3754a8ff-68c3-4c23-918c-4b70bd5f137d

**Comment by elpida-v** [comment]
@Shchvova Can you please check the bug with media.playVideo?

**Comment by Shchvova** [comment]
Oh. Somehow flew off the radar. Thanks for pinging me
