### ISSUE TITLE
[ANDROID]: runtime bug - Google Play Console reporting unsupported ABI (armeabi) - Deadline Jan 2, 2024

### ISSUE THREAD

**Issue by Sumtin** [coronalabs/corona#662]
- [ X] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**Describe the bug**
Recently pushed a new version of my app to production on Google Play built with Solar2D v2023.3699. Play Console reporting the following warning:

```
Stop targeting unsupported ABIs by January 2, 2024

Your app currently targets additional unsupported ABIs: armeabi. These unsupported ABIs do not currently represent active devices and are safe to remove them from your targeting.

Your app is using automatic integrity protection, which supports the following ABIs: x86, x86_64, armeabi-v7a and arm64-v8a. These ABIs represent the majority of active Android devices.

You should stop targeting unsupported ABIs in your next release to continue using automatic integrity protection. From January 2, 2024 onwards, you will see an error message if you upload an app bundle that targets unsupported ABIs. To resolve the error and continue using automatic integrity protection, stop targeting unsupported ABIs as soon as possible.
```

Plugins section of `build.settings`:
```
plugins={
["CoronaProvider.native.popup.social"]={
publisherId="com.coronalabs",
},
["plugin.zip"]={
publisherId="com.coronalabs"
},
["plugin.CoronaSplashControl"]={
publisherId="com.coronalabs"
},
['plugin.appodeal.base']={ publisherId='com.coronalabs' },
['plugin.appodeal.A4G']={ publisherId='com.coronalabs' },
['plugin.appodeal.AdColony']={ publisherId='com.coronalabs' },
['plugin.appodeal.AmazonAds']={ publisherId='com.coronalabs' },
['plugin.appodeal.AppLovin']={ publisherId='com.coronalabs' },
['plugin.appodeal.Bidmachine']={ publisherId='com.coronalabs' },
['plugin.appodeal.FacebookAudience']={ publisherId='com.coronalabs' },
['plugin.appodeal.GoogleAdMob']={ publisherId='com.coronalabs' },
['plugin.appodeal.IronSource']={ publisherId='com.coronalabs' },
['plugin.appodeal.Smaato']={ publisherId='com.coronalabs' },
['plugin.appodeal.StartApp']={ publisherId='com.coronalabs' },
['plugin.appodeal.Unity']={ publisherId='com.coronalabs' },
['plugin.appodeal.Vungle']={ publisherId='com.coronalabs' },
['plugin.appodeal.Appnext']={ publisherId='com.coronalabs' },
['plugin.appodeal.Chartboost']={ publisherId='com.coronalabs' },
['plugin.appodeal.Flurry']={ publisherId='com.coronalabs' },
['plugin.appodeal.InMobi']={ publisherId='com.coronalabs' },
['plugin.appodeal.InnerActive']={ publisherId='com.coronalabs' },
['plugin.appodeal.MillenialMedia']={ publisherId='com.coronalabs' },
['plugin.appodeal.Mobvista']={ publisherId='com.coronalabs' },
['plugin.appodeal.OpenX']={ publisherId='com.coronalabs' },
['plugin.appodeal.Pubnative']={ publisherId='com.coronalabs' },
['plugin.appodeal.Tapjoy']={ publisherId='com.coronalabs' },
['plugin.appodeal.TwitterMoPub']={ publisherId='com.coronalabs' },
['plugin.appodeal.Ogury']={ publisherId='com.coronalabs' },
["plugin.gpgs.v3"]={
publisherId="com.solar2d", 
},
["plugin.iap_badger"]={
publisherId="uk.co.happymongoose", 
},
["plugin.google.iap.billing.v2"]={
publisherId="com.solar2d", 
},
["plugin.firebaseAnalytics"]={
publisherId="tech.scotth", 
marketplaceId="xxxxx", 
},
["plugin.utf8"]={
publisherId="com.coronalabs", 
},
["plugin.openssl"]={
publisherId="com.coronalabs", 
},
},
```

**Comment by clang-clang-clang** [comment]
[Android ABI](https://developer.android.com/ndk/guides/abis) `armeabi-v7a` and `armeabi` are different.
According to the above warning, `armeabi` does not currently represent active devices, but there are still 1-10% of devices that support at most `armeabi-v7a` and earlier instruction sets.
imo, the warning means to stop support for devices that only support the `armeabi` instruction set, not the `armeabi-v7a` ABI, which is also compatible with `armeabi`. @Shchvova 

@Sumtin Can you upload the contents of your `build.settings` file to see which plugins are used and if some of the older plugins still have the `lib*.so` for the `armeabi` ABI?
Or can you just check if there is a `lib/armeabi` folder in your apk (open it as a zip) and the number of `lib/armeabi/lib*.so` is different from the number of other `lib/*` folders? If it's an AAB subpackage, check the `jni` folder instead of the `lib` folder.

Thanks.

**Comment by Shchvova** [comment]
Wow. Good spot

**Comment by Sumtin** [comment]
There is a `/lib/armeabi/lib*.so` in my APK, but there's only a single file in it:
![image](https://github.com/coronalabs/corona/assets/6676557/30c8eebe-f003-4282-9805-e55c04e9a690)

Compared to total # of folders in `/lib/`:
![image](https://github.com/coronalabs/corona/assets/6676557/9526290a-3046-4c79-b1ad-6dea3c8e7c56)

`lib.EncryptorP.so` is in all other folders.

Plugins section of `build.settings`:
```
plugins={
["CoronaProvider.native.popup.social"]={
publisherId="com.coronalabs",
},
["plugin.zip"]={
publisherId="com.coronalabs"
},
["plugin.CoronaSplashControl"]={
publisherId="com.coronalabs"
},
['plugin.appodeal.base']={ publisherId='com.coronalabs' },
['plugin.appodeal.A4G']={ publisherId='com.coronalabs' },
['plugin.appodeal.AdColony']={ publisherId='com.coronalabs' },
['plugin.appodeal.AmazonAds']={ publisherId='com.coronalabs' },
['plugin.appodeal.AppLovin']={ publisherId='com.coronalabs' },
['plugin.appodeal.Bidmachine']={ publisherId='com.coronalabs' },
['plugin.appodeal.FacebookAudience']={ publisherId='com.coronalabs' },
['plugin.appodeal.GoogleAdMob']={ publisherId='com.coronalabs' },
['plugin.appodeal.IronSource']={ publisherId='com.coronalabs' },
['plugin.appodeal.Smaato']={ publisherId='com.coronalabs' },
['plugin.appodeal.StartApp']={ publisherId='com.coronalabs' },
['plugin.appodeal.Unity']={ publisherId='com.coronalabs' },
['plugin.appodeal.Vungle']={ publisherId='com.coronalabs' },
['plugin.appodeal.Appnext']={ publisherId='com.coronalabs' },
['plugin.appodeal.Chartboost']={ publisherId='com.coronalabs' },
['plugin.appodeal.Flurry']={ publisherId='com.coronalabs' },
['plugin.appodeal.InMobi']={ publisherId='com.coronalabs' },
['plugin.appodeal.InnerActive']={ publisherId='com.coronalabs' },
['plugin.appodeal.MillenialMedia']={ publisherId='com.coronalabs' },
['plugin.appodeal.Mobvista']={ publisherId='com.coronalabs' },
['plugin.appodeal.OpenX']={ publisherId='com.coronalabs' },
['plugin.appodeal.Pubnative']={ publisherId='com.coronalabs' },
['plugin.appodeal.Tapjoy']={ publisherId='com.coronalabs' },
['plugin.appodeal.TwitterMoPub']={ publisherId='com.coronalabs' },
['plugin.appodeal.Ogury']={ publisherId='com.coronalabs' },
["plugin.gpgs.v3"]={
publisherId="com.solar2d", 
},
["plugin.iap_badger"]={
publisherId="uk.co.happymongoose", 
},
["plugin.google.iap.billing.v2"]={
publisherId="com.solar2d", 
},
["plugin.firebaseAnalytics"]={
publisherId="tech.scotth", 
marketplaceId="xxxxx", 
},
["plugin.utf8"]={
publisherId="com.coronalabs", 
},
["plugin.openssl"]={
publisherId="com.coronalabs", 
},
},
```

**Comment by clang-clang-clang** [comment]
Oh, that's it. Where did `libEncryptorP.so` come from? Is there an upgraded version that does not contain the `armeabi` .so file?
Maybe we can add a config to `build.settings` to control [NDK abiFilters](https://developer.android.com/ndk/guides/abis#gc).

**Comment by Sumtin** [comment]
Great question.  I wouldn't know how to answer that though. @Shchvova?

**Comment by clang-clang-clang** [comment]
@Sumtin Temperary solution:

Please create a new file named `AndroidResources/corona.gradle` in your project and fill it with the following content:

```groovy
android.defaultConfig.ndk.abiFilters = ["arm64-v8a", "armeabi-v7a", "x86_64", "x86"]
```

This is an explicit declaration for ABIs. Try a Android build and see if the `lib/armeabi` directory in the APK is gone. If so, you can attempt a push to Play Console.

Thanks.

**Comment by Sumtin** [comment]
That seemed to work (see below), but without knowing exactly where this dependency comes from I can't properly test.  Can someone (show me how to) dig for the answer?

![image](https://github.com/coronalabs/corona/assets/6676557/5d449688-83f4-45d8-bda7-8a0cc6c016a9)

**Comment by clang-clang-clang** [comment]
The `libEncryptorP.so` library should be quite old, or it has a specific target audience, otherwise it should be compiled with newer tools, and the `armeabi` ABI should be removed by default. If it hasn't been updated for a long time, it may also cause some other problems.

imo, in the future, it may be required that only 64-bit `arm64-v8a`, `x86_64`, and new architectures such as `armv9`, `RISC-V` may be added in the near future.
Therefore, I generally recommend using the default values provided by G's Android packaging tool, rather than hard-coding these values by Solar2D. You only need to modify and override these default values when necessary.

The `corona.gradle` script can do this^ by telling the G's Android packaging tool to specify the required ABI. However, I believe there will be a better way to do this in the future, such as adding a configuration in `build.settings`. However, this requires @Shchvova to see what kind of method would be better.

**Comment by Sumtin** [comment]
@Shchvova  Possible to tell me which plugin is using the outdated ABI?

**Comment by Sumtin** [comment]
Just rebuilt using 3701 and the problem and now there's an extra .so file in the `armeabi` folder:
![image](https://github.com/coronalabs/corona/assets/6676557/4fda18f6-8e80-4950-bdbf-5b52d40d1835)

**Comment by Shchvova** [comment]
This command should say which of your plugins have the armeabi
```
find ~/Solar2DPlugins -path '*/android/data.tgz' -exec bash -c '(tar tf "$0" |  grep -q armeabi/) && echo "$0" ' {}  \;
```

**Comment by Shchvova** [comment]
Or even better:
```
find ~/Solar2DPlugins -path '*/android/data.tgz' -exec bash -c '(tar tf "$0" |  grep -q libEncryptorP.so) && echo "$0" ' {}  \;
```
If this does not work, I suggest commenting half of the plugins, until you find the culprit. It is possible it is in one of the dependency.

**Comment by Shchvova** [comment]
Oh... Also, plugin.appodeal is really outdated. Please use plugin.appodea.beta in build.settings.

**Comment by Sumtin** [comment]
Ah, ok. I upgraded to the Appodeal beta and I no longer have the `armeabi` ABI.  

I noticed the list of ad providers in the Beta is much smaller than non-beta.  Is this expected, or is the list of providers in the sample `build.settings` just an example?
