### ISSUE TITLE
[ANDROID]: app always crashes when pressing back button and opening again

### ISSUE THREAD

**Issue by zebi24** [coronalabs/corona#663]
**Describe the bug**
On the latest build [2023.3701] on Android devices, when I close the app with back button (default back button behavior or via native.requestExit() ), and open the app again, the app crashes on startup. This doesn't happen using older Solar versions.

**To Reproduce**
1. Run the app 
2. Close the app with back button (default back button behavior or via native.requestExit() ),
3. Open the app again

**Target platform and where build was made:**
 - All Android devices

**Solar version**
2023.3701

**Comment by ggcrunchy** [comment]
Thanks. I have a couple things ([this PR](https://discord.com/channels/721785436195782677/721785804988612701/1182564562168459284) and so far the latest two commits [here](https://github.com/ggcrunchy/corona/commits/AtomicScheduler/)) that were meant to address some issues found in 3701. I'll add the Back button issue to my tests. 😄

**Comment by ggcrunchy** [comment]
Seems to work with the test.

**Comment by ggcrunchy** [comment]
Worked in the emulator for me, like I said. But I've added a test build in #664, if you want to try it.

**Comment by zebi24** [comment]
Hi, great news, I've tested the test build and crashes are gone.
