### ISSUE TITLE
[IOS]: runtime bug

### ISSUE THREAD

**Issue by PenguenUmut** [coronalabs/corona#671]
- [x] I tried searching [Solar2D forums](https://forums.solar2d.com/) for the solution.

**Describe the bug**
I tried to build for IOS and open in Xcode IOS Simulator for “HelloWorld” project.
Build succeeded but app crashes on start.
What am I missing?

Logs:
iOS build succeeded in 17 seconds
Running '/Users/penguen/Desktop/HelloWorld.app' on Xcode iOS Simulator - iPhone 15 Pro / iOS 17.0
Error running /Applications/Corona-3701/Corona Simulator.app/Contents/Resources/xcodesim_sendapp.sh (
                        "/Users/penguen/Desktop/HelloWorld.app",
                        "xxxxxxxxxxxx"
                    )
Restarting Xcode Simulator ...
        No matching processes belonging to you were found
        An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
        Simulator device returned an error for the requested operation.
        The request was denied by service delegate (SBMainWorkspace).
        Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=1):
           The request to open "HelloWorld" failed.
           The request was denied by service delegate (SBMainWorkspace).

**Target platform and where build was made:**
I make a clean install all.
Corona Simulator : Version 2023.3701 (2023.12.5)
MacOS : Sonoma Version 12.2.1
Xcode : Version 15.0.1 (15A507)
IOS SDK: 17.0

**Comment by clang-clang-clang** [comment]
Do you run iOS Simulator on Apple Silicon? 
Currently Solar2D lack support for directly running Apps on arm64 iOS Simulator, so you can consider debug on iPhone/iPad or try using [arch](https://www.unix.com/man-page/osx/1/arch/) command to launch the x86_64 iOS Simulator on Apple Silicon.

**Comment by Shchvova** [comment]
Yes... I think problem is we don't support apple silicon simulator yet

**Comment by sekodev** [comment]
> Yes... I think problem is we don't support apple silicon simulator yet

Any plans for the future?

**Comment by Shchvova** [comment]
Yes. There is a plan to rewrite the apple targeted build system to be less platform dependent

**Comment by maucel89** [comment]
Good morning @Shchvova,
I still have something like the mentioned issue:

Xcode iOS Simulator installation:
                    An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=4):
                    App installation failed: È necessario aggiornare “MyAppName”
                    Per funzionare con questa versione di iOS, l’app deve essere aggiornata dall’azienda di sviluppo.
                    Failed to find matching arch for input file: /Users/username/Library/Developer/CoreSimulator/Devices/AA44B21C-B7E8-425B-B760-C5269394D052/data/Library/Caches/com.apple.mobile.installd.staging/temp.6cT8H9/extracted/MyAppName.app/MyAppName
                    Underlying error (domain=IXUserPresentableErrorDomain, code=4):
                    	È necessario aggiornare “MyAppName”
                    	Per funzionare con questa versione di iOS, l’app deve essere aggiornata dall’azienda di sviluppo.
                    An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
                    Simulator device failed to launch com.myapp.name.
                    The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "com.myapp.name" is unknown to FrontBoard").
                    Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=1):
                    	The request to open "com.myapp.name" failed.
                    	The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "com.myapp.name" is unknown to FrontBoard").

I'm using Solar2D Version 2026.3728 (2026.2.8).
Could you please help me to fix it?

Thanks
