### ISSUE TITLE
iOS: Invalid toolchain when shipping app with 3703 and Xcode 15.2

### ISSUE THREAD

**Issue by Shchvova** [coronalabs/corona#677]
App builds but then fails to upload with Transporter showing an error:
<img width="556" alt="image" src="https://github.com/coronalabs/corona/assets/130387/2cdcbde5-a8c7-408e-9ead-1c37c60e7409">

Asset validation failed (90534)
Invalid Toolchain. Your app was built with an unsupported SDK or version of Xcode. If you plan to submit this build to the App Store, make sure you are using the versions listed in https://help.apple.com/xcode/mac/current/#/devf16aefe3b or later. (ID: f5e92031-204b-4889-84d6-187628bc1b9a)

**Comment by clang-clang-clang** [comment]
I think this is the Action Runner's issue, a rebuild should fix it.

Note:
- 3703 built on 15 Jan
- https://github.com/actions/runner-images/pull/9169 shows Xcode 15.2 was updated from beta on 16 Jan
- 3703 uses Xcode `15.2 (beta) 15C5500c`: https://github.com/coronalabs/corona/actions/runs/7521939234/job/20474407076#step:21:211

**Comment by Shchvova** [comment]
@clang-clang-clang 🏅
yup, that did it. I rebuilt 3703
