### ISSUE TITLE
Apple: Xcode 15.3

### ISSUE THREAD

**Issue by clang-clang-clang** [coronalabs/corona#684]
As stated in the [forum](https://forums.solar2d.com/t/solar2d-3704-and-xcode-17-4/356375), an upgrade is required to compile using Xcode 15.3.

It is necessary to wait for the runner update https://github.com/actions/runner-images/issues/9459 to complete.
And [Xcode 15.3 required macos 14](https://developer.apple.com/support/xcode/).

**Comment by Shchvova** [comment]
Of course. It doesn't seem that we have it available yet :( 
https://github.com/actions/runner-images?tab=readme-ov-file#available-images

**Comment by clang-clang-clang** [comment]
bump up this.

Hi, @Shchvova, I don't know if the template is 17.2 but will there be any problems if you ignore the warning and use the 17.4 SDK to compile iOS apps?
Or is there usually no problem?
If so, can you tell people that they can use 17.4 and 3706 to compile iOS apps when not experiencing problems?

I understand that some people are focused on using the latest SDKs, but Solar2D has other critical priorities to address right now.
