### ISSUE TITLE
Code sign problem

### ISSUE THREAD

**Issue by bobyeh1390** [coronalabs/corona#69]
I found an issue

ERROR: code signing embedded frameworks failed: /Applications/Corona-3592/Corona Simulator.app/Contents/Resources/codesign-framework.sh: line 47: echo: write error: Bad file descriptor

Corona Version: 2020.3592
for MAC & iOS SDK: 13.4

I try to use the old official Corona to build it. It will ask me to give the permission to use keychain.app After that the 3592 works fine. So I think 3592 maybe missing this part?

**Comment by Shchvova** [comment]
weirdly enough, `echo`, print to console command failed. It can happen when output (stdout) is somehow closed, but I don't see us doing it anywhere.
I added code to ignore echo failure in this particular instance.
