### ISSUE TITLE
File either missing or mislabelled

### ISSUE THREAD

**Issue by HBL001** [coronalabs/corona#691]
@Shchvova Hi,  there is a script file missing and I can't fathom it out.  

Linux: improving support and adding flatpak
 [master](https://github.com/coronalabs/corona) ([#360](https://github.com/coronalabs/corona/pull/360))
 [3706](https://github.com/coronalabs/corona/releases/tag/3706) 

@[bakeinflash](https://github.com/coronalabs/corona/commits?author=bakeinflash)

From:

**COMMAND ${CMAKE_COMMAND} -E env BUILD_CONFIG="${BUILD_CONFIG}" "${CORONA_ROOT}/platform/linux/lua_to_native.sh"**

to: 

**COMMAND ${CMAKE_COMMAND} -E env BUILD_CONFIG="${BUILD_CONFIG}" "${CORONA_ROOT}/platform/linux/lua_to_native_unixeol.sh"**

This got committed so I assumed, that the script file "lua_to_native.sh" called was uprevved and renamed to "lua_to_native_unixeol.sh", but when I look for "lua_to_native_unixeol.sh", it just doesn't seem to exist.

I've searched for this file, no luck.  Its a long shot, but I thought I would ask if you knew if this script was on a private repo, that me, the general public cannot access ?

Kind regards

Richard

**Comment by clang-clang-clang** [comment]
AFAIK, `lua_to_native_unixeol.sh` was created by changing the End-of-Line in the file `lua_to_native.sh`.

https://github.com/coronalabs/corona/blob/4c7f6db3f51503a9957215e152f04eef260b2496/platform/linux/CMakeList.txt#L966-L967

**Comment by HBL001** [comment]
Thank you !   I am still getting into this codebase and its still all new to me!
