### ISSUE TITLE
attempt to index global 'coronabaselib' (a nil value)

### ISSUE THREAD

**Issue by crackulator** [coronalabs/corona#70]
Build 2020.3593
My app simulates fine, but when I attempt an Android build, I get the following:

FAILURE: Build failed with an exception.
15:54:31.084  
15:54:31.084  * Where:
15:54:31.084  Build file 'C:\Users\Fritz\AppData\Local\Temp\Corona Labs\CLtmpa14892\template\app\build.gradle.kts' line: 515
15:54:31.084  
15:54:31.084  * What went wrong:
15:54:31.084  Error while fetching plugins: PANIC: unprotected error in call to Lua API (d:\a\corona\corona\platform\resources\CoronaBuilderPluginCollector.lua:9: attempt to index global 'coronabaselib' (a nil value))
15:54:31.084  PANIC: fatal Lua error: d:\a\corona\corona\platform\resources\CoronaBuilderPluginCollector.lua:9: attempt to index global 'coronabaselib' (a nil value)

(I've been trying to divine the current state of the project, but so far been unable to tell if it should be able to do an Android build... so apologies if I'm getting ahead here...)

**Comment by Shchvova** [comment]
Thanks! Can't believe I missed that.

**Comment by MartingK-u** [comment]
What is the coronabaselib and why would it be nil ?

**Comment by Shchvova** [comment]
This issue is fixed now. You can get a new version to get the fix. It’s a library replacing print so it gets sent to the CoronaConsole.

**Comment by crackulator** [comment]
Verified, thanks!
