### ISSUE TITLE
Microsoft Defender SmartScreen prevents installation of Solar2D

### ISSUE THREAD

**Issue by yuriistest** [coronalabs/corona#704]
Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

App: Solar2D-Windows-2024.3706.msi

Publisher: Unknown publisher

**Comment by sekodev** [comment]
This is the same issue as #565 . @Shchvova any updates on that?

**Comment by Shchvova** [comment]
Yes. It is same. And no progress. Signing keys process is really unclear on integrating to CI and those which are clear cost ridiculous money.
