### ISSUE TITLE
Android: API Level 34

### ISSUE THREAD

**Issue by Colin-Morgan** [coronalabs/corona#710]
Starting August 31, 2024, Google will no longer allow apps to be submitted to the Play Store (both new apps and updates to existing apps) if they do not target API Level 34. Furthermore, after this date, apps targeting older API levels will not be visible to devices running the most-current version of Android.
According to a Google policy announcement, August 31 will now be the annual deadline for apps to update to the latest API level.

**Comment by edibudimilic** [comment]
How hard is to update the build version, can we do it manually? I'm asking if it's similar to e.g. PHP or Python where you just overwrite the files.

**Comment by Shchvova** [comment]
Bumping target version is the easy part. Getting it to work is harder.

**Comment by dethier1958** [comment]
With the deadline of August 31st (when our apps will be delisted) fast approaching, is someone at least working on this? It doesn't even show that anyone has been assigned.

**Comment by ricaragao** [comment]
@Shchvova , sorry bother you, but do you have any deadline for this solution?

**Comment by Colin-Morgan** [comment]
I can't speak to an ETA, but you can get an extension very easily:
https://forums.solar2d.com/t/how-to-request-an-extension-for-android-api-level-34/356671
