### ISSUE TITLE
Update to Unity Ads Plugin is needed for Google Play User Data policy

### ISSUE THREAD

**Issue by superqix** [coronalabs/corona#719]
For apps to be submitted to Google Play with Unity Ads support the underling library for the plugin needs to be 4.0.1 or greater.

> Issue found: Violation of User Data policy
> We reviewed SDKs used by your app and found noncompliant version(s) of SDK(s) which collects persistent device identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers.
> 
> Issue details
> 
> We found an issue in the following area(s):
> 
> Version code 99:
> SDK: Unity com.unity3d.ads:unity-ads (consider upgrading to version 4.0.1)

[Current version is 4.12.2](https://github.com/Unity-Technologies/unity-ads-android/releases)

**Comment by scottrules44** [comment]
Are you using V4
http://docs.coronalabs.com/plugin/unityads-v4/index.html

**Comment by superqix** [comment]
Yep, I am. The build compiles but when I upload it to the Google Console, I get this rejection

![Screenshot 2024-08-14 at 10 29 26 AM](https://github.com/user-attachments/assets/9d36561d-3392-4c46-95c4-3cc5c4ba126c)

I'm assuming the underlying JAR for the plugin needs to be updated

**Comment by Shchvova** [comment]
Please provide your build.settings

**Comment by superqix** [comment]
Yep, here it is

`plugins =
{
    ["plugin.unityads.v4"] =
		{
			publisherId = "com.solar2d",
		},
`

[build.settings.txt](https://github.com/user-attachments/files/16638406/build.settings.txt)

**Comment by superqix** [comment]
And then in code...

```
local unityads = {}

if device.isMobile then
  unityads = require "plugin.unityads.v4"
end

```

**Comment by scottrules44** [comment]
I just updated Unity for Android to 4.12.2

**Comment by superqix** [comment]
I rebuilt this morning and resubmitted. Hopefully this will do it.

Thanks so much for the update!

**Comment by superqix** [comment]
I still get the same rejection :( 

I'll reach out to Google and see what they say. It appears to be an automated SDK scan, so maybe it's catching something else.

**Comment by superqix** [comment]
Uninstalled and re-installed everything, removed all prior uploaded builds and now Google isn't throwing that rejection and recognizes the latest Unity Ad core.

Thanks for your help!
