### ISSUE TITLE
Android build errantly requires internet permissions

### ISSUE THREAD

**Issue by crackulator** [coronalabs/corona#74]
My app does not require the internet and uses no plugins. Internet permission is not requested in build.settings. Yet in the apk, internet permission is requested. Why?

This is inherited from Corona, experienced the same over there.

**Comment by Shchvova** [comment]
Are you using any plugins? They often require additional permissions.
I just tried building, without any plugins I don't get any permissions in manifest at all. Please, provide project which I can reproduce the issue. Until then, closing it.

**Comment by crackulator** [comment]
Found it... my fault. I was accidentally bringing in the advertising library. Sorry for the misdirection.
