### ISSUE TITLE
[Android]: Runtime Bug - Version does not update when using Live Build

### ISSUE THREAD

**Issue by acidrainstudios** [coronalabs/corona#744]
I have live build setup and working, I'm testing on an android device. 
Everything works fine, except when I try to print out the version number of the app on the screen. 
I get the version by using system.getInfo("appVersionString")

I update my app(new code, or functionality, etc), I update the version number in the Android Build Setup window in the simulator, build...
![image](https://github.com/user-attachments/assets/55d9a213-61c5-497a-b311-7737f9bd779a)

I see my android device update to the new app after I do a build, but when I run it, I still see the old version. I've tried rebooting the live server, tried all kinds of tests, the only thing that updates the version is if I copy the .apk file to my device and reinstall the app from scratch. 

**To Reproduce**
1. Create an app, and give it a version number
2. Use system.getInfo("appVersionString") to print the version on a screen through text
3. Use live build to cast the compiled app to android device
4. Change something in code, update version number, and rebuild. 
5. When android device gets the live build update, the version will not change, while the code update will be pushed. 

**Target platform and where build was made:**
 - OS: [Android]

**Comment by Shchvova** [comment]
You would have to deploy new APK to get new version.

**Comment by acidrainstudios** [comment]
@Shchvova THat is what I have been doing, but is there any way, or is it possible to add the version autoupdate with the live build?
