### ISSUE TITLE
Google Play App Integrity

### ISSUE THREAD

**Issue by SimpGameDev** [coronalabs/corona#749]
Google Play App Integrity [https://developer.android.com/google/play/integrity/setup](url) requires to include `implementation 'com.google.android.play:integrity:1.4.0'` . How could you do that?
Currently, turning on _Automatic protection_ in the Google Play Console causes the app to not work but only presenting a link to Google Play at startup.

**Comment by Shchvova** [comment]
You can just add that line to AndroidResources/corona.gradle
Inside dependencies block

**Comment by SimpGameDev** [comment]
> You can just add that line to AndroidResources/corona.gradle Inside dependencies block

Many thanks for your reply. 
So I created a new file `corona.gradle` inside my projects `AndroidResources` folder and added this:
`dependencies {
    implementation 'com.google.android.play:integrity:1.4.0'
}`
The installer check with the automatic protection still failed, I assume due to other incomplete settings.
I turned the check off, life is too short to deal with that.

**Comment by SimpGameDev** [comment]
Many thanks for your reply.
So I created a new file corona.gradle inside my projects AndroidResources folder and added this:
dependencies { implementation 'com.google.android.play:integrity:1.4.0' }
The installer check with the automatic protection still failed, I assume due to other incomplete settings.
I turned the check off, life is too short to deal with that.

**Comment by SimpGameDev** [comment]
Many thanks for your reply.
So I created a new file corona.gradle inside my projects AndroidResources folder and added this:
dependencies { implementation 'com.google.android.play:integrity:1.4.0' }
The installer check with the automatic protection still failed, I assume due to other incomplete settings.
I turned the check off, life is too short to deal with that.

**Comment by SimpGameDev** [comment]
Many thanks for your reply.
So I created a new file corona.gradle inside my projects AndroidResources folder and added this:
dependencies { implementation 'com.google.android.play:integrity:1.4.0' }
The installer check with the automatic protection still failed, I assume due to other incomplete settings.
I turned the check off, life is too short to deal with that.
