### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by DoogSiAnoroc** [coronalabs/corona#77]
lack dll file
vcruntime140.dll
msvcp140.dll

Show after making up
(0xc000007b)

**Comment by Shchvova** [comment]
Are you using bit or zip plugins?

**Comment by DoogSiAnoroc** [comment]
I was doing SD card encryption app before

I used the BIT plugin

**Comment by DoogSiAnoroc** [comment]
Sorry to see the mail now


plugins = {
["plugin.bit"] =
     {
         publisherId = "com.coronalabs",
         supportedPlatforms = { iphone=true, android=true, osx=true,
win32=true }
     },
}

Vlad Svoka <notifications@github.com> 於 2020年5月26日 週二 下午3:50寫道：

**Comment by sekodev** [comment]
It may still be a good idea to bundle required files to the setup but have you tried manually installing those files? This should fix the missing dll issue.

**Comment by DoogSiAnoroc** [comment]
Manual installation
Did I find the dll file on the Internet and install it myself?


Ask you a question

This child policy has troubled me for a long time
I don’t even know where there is a violation in the appodeal setting
Or gamesparks setting violation

I have followed the list on this URL
https://support.google.com/googleplay/android-developer/answer/9283445
Delete ads that are not on the list
But it's still illegal

If you are free, please help me to get me on the shelves smoothly. Thanks




Serkan Aksit <notifications@github.com> 於 2020年10月6日 週二 下午5:55寫道：

**Comment by sekodev** [comment]
Yes, you can find those dlls on the internet and install them. I believe most of them are related to C++ distributables.

For the other question, please take it to the forums since it's not related with engine source. There will be more people there that can help you with that issue.

**Comment by DoogSiAnoroc** [comment]
thank you

Serkan Aksit <notifications@github.com> 於 2020年10月9日 週五 下午6:30寫道：

**Comment by Shchvova** [comment]
They most probably from VS 2015 redistributable: https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by DoogSiAnoroc** [comment]
Thank you

Is it possible for the game engine to package the previous file plugins
when constructing?

Because I uploaded an ad-free children’s app, Google Play still shows that
I violated the children’s advertising policy

If you will package the previous plug-in
How can I delete it?

Thank you



Vlad Svoka <notifications@github.com> 於 2020年10月9日 週五 下午6:40 寫道：

**Comment by sekodev** [comment]
I'd highly suggest taking this to the forums. There would be far more people that can help you solve this.

**Comment by DoogSiAnoroc** [comment]
thank you

Serkan Aksit <notifications@github.com> 於 2020年10月10日 週六 下午11:00寫道：

**Comment by DoogSiAnoroc** [comment]
Hi
excuse me
did not receive the forum registration email

Nai Alex <fruitcharmhealth@gmail.com> 於 2020年10月11日 週日 下午12:58寫道：
