### ISSUE TITLE
Dependency issues on Debian 10 (buster)

### ISSUE THREAD

**Issue by Akapa97** [coronalabs/corona#78]
After running the install-dependencies.sh script, there are still some missing dependencies. When trying to run, the following error occurs:
```
error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
```

**Comment by sekodev** [comment]
You may have found this in the past weeks but still, wanted to point out. Solar2D Tux is the way to go for a more actively developed Linux Solar. Here: http://solar2dtux.com/

**Comment by Shchvova** [comment]
Please, use Solar2DTux.
