### ISSUE TITLE
Launching from command line does not open project

### ISSUE THREAD

**Issue by personalnadir** [coronalabs/corona#79]
When launching from the command line the simulator window does not open specified project. There do not seem to be any appropriate error message. This used to work until recently. 

I saw the following in Console: ```LSExceptions shared instance invalidated for timeout.```. However I am not seeing any specific errors or warning pop up.

I am using the following command:
```/Applications/CoronaSDK/Corona\ Simulator.app/Contents/MacOS/Corona\ Simulator /project/path/main.lua -no-console YES```

**Comment by Shchvova** [comment]
Please specify your command line and build you’re getting error on.

**Comment by personalnadir** [comment]
I'm using iTerm2 Build 3.3.9, bash and Solar build 2020.3596 (2020.5.26) on MacOS 10.14.6

**Comment by MichaelCorona** [comment]
Sorry. Can you write down command line example which is failing.
-- 
Vlad Shcherban
The Engineer @ Corona Labs

-- 
 <https://explorestack.com/>
 <https://www.facebook.com/explorestack>  
<https://twitter.com/explorestack>  
<https://www.linkedin.com/company/explorestack> Explore Stack 
<https://explorestack.com/> | Blog <https://explorestack.com/blog/>

**Comment by joehinkle11** [comment]
I've had this problem too. The command line will open Corona, but it won't open the project path you give it

**Comment by personalnadir** [comment]
@MichaelCorona it's ```/Applications/CoronaSDK/Corona\ Simulator.app/Contents/MacOS/Corona\ Simulator /project/path/main.lua -no-console YES```

**Comment by solares** [comment]
I'm getting the same thing. I alias 

```
alias corona="\"/Applications/Corona/Corona Simulator.app/Contents/MacOS/Corona Simulator\""
```
then 
```
cd ~/my-corona-project
corona .
```

This used to work, not working on Corona 2020.3598.
