### ISSUE TITLE
VSCode doesn't show lua's output,in Windows.

### ISSUE THREAD

**Issue by yu66433** [coronalabs/corona#81]
i create a task to launch corona with no-console.but vs code doesn't show lua output？

**Comment by Shchvova** [comment]
Did it work before? Could you attach something which was working so I can fix this.

**Comment by yu66433** [comment]
i doesn't output any log when i use `json.encode` in my project ;

VSCode Launch Config

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Corona-Run",
            "type": "lua-local",
            "request": "launch",
            "program": {
                "command": "%CORONA_PATH%/Corona Simulator.exe"
            },
            "args": [
                "-no-console",
                "main.lua"
            ]
        }
    ]
}`

main.lua
`
json = require("json")

print("====== before encode")
local sRet = json.encode({a = 1})
print("====== encode result:", sRet)
print("====== after encode")

local iCount = 1
timer.performWithDelay(1000, function()
    print(iCount)
    iCount = iCount + 1
end, -1)
`

![image](https://user-images.githubusercontent.com/5615986/88473047-4298dd80-cf4c-11ea-9f66-e740c20b7485.png)

**Comment by yu66433** [comment]
> Did it work before? Could you attach something which was working so I can fix this.

**Comment by sekodev** [comment]
Seeing that your print statements are working(see "before encode" and "encode result"), this seems like an issue on your side rather than the engine. I'd suggest taking this to the Discord channel(https://discord.gg/Abf5V9G) or the forums(https://forums.solar2d.com/).

**Comment by scottrules44** [comment]
I tested printing json.encode via the new Solar2D code extention and seems to work fine :)

https://github.com/solar2d/Solar2D-VSAutocomplete/blob/2bb3128076b69822d56fb0f652a7e1477e8b23fb/extension.js#L58
