### ISSUE TITLE
XCode 11.5 contains tvOS SDK 13.4 not 13.5 - Can't build?

### ISSUE THREAD

**Issue by yousaf-shah** [coronalabs/corona#86]
It looks like 2020.3598 won't build for Apple TV as it is looking for tvOS 13.5 (which does not exists yet?) Although XCode 11.5 upgraded to iOS13.5 tvOS is 13.4

Won't load the Apple simulator or build as it is looking for 13.5 templates for everything.

**Comment by Shchvova** [comment]
This should be fixed by one of recent commits and next build.

**Comment by yousaf-shah** [comment]
Amazing - thank you!

**Comment by Shchvova** [comment]
Unfortunatelly there is some [issues](https://github.com/coronalabs/corona/actions/runs/128903189) with building windows sim. But you can download macOS there no problems. (Click on `Simulator-macOS`)
