### ISSUE TITLE
Plugins not downloaded

### ISSUE THREAD

**Issue by yejcob** [coronalabs/corona#88]
There is an issue where plugins are not downloaded, if the plugin is not from publisher com.coronalabs like ["plugin.ui_framework"] = 
		{
			publisherId = "com.skyjoy"
		}

**Comment by joehinkle11** [comment]
I think Vlad is working on getting plugins to work offline, and it’s not yet finished

**Comment by yejcob** [comment]
Offline you say, is there a way to login to get plugins to download with version 2020.3598?

**Comment by sekodev** [comment]
As far as I know, a plugin needs to be available here(https://plugins.solar2d.com/) to be installed like this. If they are not available at the open directory, then it's treated as a third party plugin and you need to download it from an external source like this(https://forums.solar2d.com/t/plugins-for-new-offline-builds-3595/351576/2)

**Comment by yejcob** [comment]
So plugins on marketplace dont work?

https://marketplace.coronalabs.com/

**Comment by sekodev** [comment]
As far as I know, they don't work with Solar2D builds. We have https://plugins.solar2d.com/ and https://solar2dmarketplace.com/ that works with Solar2D or like Troy does on the forum, you need to specify a URL to download the plugin.

**Comment by yejcob** [comment]
Okey thanks will try that out

**Comment by Shchvova** [comment]
https://marketplace.coronalabs.com/ Will be closed soon. I reached out to some developers if they want their plugins on the plugins.solar2d.com
Some agreed and I added them.

**Comment by V4NDER** [comment]
> As far as I know, they don't work with Solar2D builds. We have https://plugins.solar2d.com/ and https://solar2dmarketplace.com/ that works with Solar2D or like Troy does on the forum, you need to specify a URL to download the plugin.

Where to enter the URL? how are they solving this issue?

**Comment by sekodev** [comment]
@V4NDER the problem you are facing that you mentioned in #110 can be solved by using an older Solar2D builds such as 3599.

@Shchvova it may be a good idea to close this issue since first post is related to a third-party and it's irrelevant now.

**Comment by V4NDER** [comment]
@sekodev the version 3599 has the same problem

**Comment by scottrules44** [comment]
A lot has happened since this post, essentially all plugin repos from marketplace.coronalabs.com not longer exist and people should use plugins.solar2d.com, or third party sites like https://plugins.solar2d.com/ and https://solar2dmarketplace.com/
