### ISSUE TITLE
"Slack" link in Community section of website broken

### ISSUE THREAD

**Issue by appfamily** [coronalabs/corona#90]
This is the URL target for Slack: " https://solar2d.com/# " . I assume it is supposed to lead to the Slack workspace?

![image](https://user-images.githubusercontent.com/9742676/84637447-fe023700-aef5-11ea-8caa-e7539fb36763.png)

Apologies if this is the wrong project to post this in.

**Comment by Shchvova** [comment]
Should be fixed with a1190d1537d06e61103fae7028d803a8c9ced119
