### ISSUE TITLE
If "high contrast" is enabled in accessibility fonts get really bold/blurry - Android

### ISSUE THREAD

**Issue by mark-sgs** [coronalabs/corona#91]
Bug report here as requested
![Screenshot_20200618-105302](https://user-images.githubusercontent.com/61833594/85027367-bee01a00-b171-11ea-96d6-c418cb8f00b5.jpg)
![Screenshot_20200618-105210](https://user-images.githubusercontent.com/61833594/85027374-c1db0a80-b171-11ea-89b0-0cbcd2c9b30c.jpg)

**Comment by mark-sgs** [comment]
@Shchvova this was posted 5 months ago and I imagine the fix is real simple.  Any chance this can be actioned as it makes certain fonts almost unreadable.  Thanks.

**Comment by IlSui** [comment]
I don't have anything else to say. I'm here just to increase the number of people asking for this fix.

**Comment by sekodev** [comment]
I just released a game so haven't seen this behavior reported yet but since my game relies heavily on text, I'd like this to be fixed.

So, +1.
