### ISSUE TITLE
zip plugin not working on Windows

### ISSUE THREAD

**Issue by clockwk** [coronalabs/corona#92]
On one Windows installation, calls to the zip plugin crash the simulator with the message “The stdin connection has closed” (yes, fresh install). 

The code is identical to the example in the docs. The zip file itself is trivial. The plugin opens and reads the zip file with no difficulty on a Mac installation.

On another Windows installation, Instead of a simulator crash, I see a Runtime error:
“error loading module 'plugin_zip” from file ‘[path…]\plugin_zip.dll’:
The specified module could not be found."
This error occurs immediately on launch. The trace says that this occurs in […]\init.lua:931: in function ‘require’

I tried a few variants including installing today’s solar2D build (3600) just in case. No luck. 

Thanks.

**Comment by ipforums** [comment]
Downgrading an older Corona SDK release solves the problem.  So this bug was introduced after the Github migration...

**Comment by Shchvova** [comment]
@ipforums hey, may I ask to try again? I rebuilt the plugin with newest visual studio, this should help.

**Comment by clockwk** [comment]
@Shchvova Vlad, yes, that resolved it. Thank you!

**Comment by ipforums** [comment]
Confirmed fixed.  Thank you Vlad!.
