### ISSUE TITLE
Android: Can't build when offline

### ISSUE THREAD

**Issue by sekodev** [coronalabs/corona#96]
Can't build for Android when there is no internet connection. I'm guessing this is related to keystore validation.

How to reproduce:
1- Start simulator with a project.
2- Select Build -> Android.
3- Select your keystore. It could both be debug or production keystore, doesn't matter.
4- Press Build.
5- After some time, warning message will be displayed. ("The password for the alias was not valid or the Java JDK was not found.")
6- Press "OK".
7- Simulator will ask for keystore password, enter that.
8- Even though it's correct, simulator rejects the password and goes to step 5.

Only way to get out of this loop is to connect to Internet.

Source and more details here:
https://forums.solar2d.com/t/why-does-corona-sdk-use-build-servers-for-android/351664

**Comment by Shchvova** [comment]
Sorry. Android build system (as one of the Google, not ours), require internet connection. It downloads various parts of the build pipeline, like android plugin for gradle all the time.

**Comment by sekodev** [comment]
Thank you for the quick answer. Posted your statement to the forums as well.
