### ISSUE TITLE
Simulator Crash - Firebase analytics

### ISSUE THREAD

**Issue by SimeonAronK** [coronalabs/corona#97]
Hi,

Simulator crash when build for iOS, I have added the following Plugins in the build settings.

-- Admob plugin
		["plugin.admob"] =
        {
            publisherId = "com.coronalabs"
        },

		-- In Mobi
		["plugin.inMobi"] =
        {
            publisherId = "com.coronalabs"
        },

		-- IAP Google
		["plugin.google.iap.v3"] =
        {
            publisherId = "com.coronalabs"
        },

		-- Notifications
		["plugin.notifications.v2"] =
		{
			publisherId = "com.coronalabs"
		},

		-- Amazon IAP
		["plugin.amazon.iap"] =
        {
            publisherId = "com.coronalabs"
        },

		-- Firebase Analytics
		["plugin.firebaseAnalytics"] =
		{
			publisherId = "scotth.tech",
			supportedPlatforms = {
				android = { url = "https://solar2dmarketplace.com/marketplacePlugins?ID=62baro&plugin=FirebaseAnalytics_scotth-tech&type=Android" },
				iphone = { url = "https://solar2dmarketplace.com/marketplacePlugins?ID=62baro&plugin=FirebaseAnalytics_scotth-tech&type=iOS" },
				macos = { url = "https://solar2dmarketplace.com/marketplacePlugins?ID=62baro&plugin=FirebaseAnalytics_scotth-tech&type=MacOS" }, --Only works with Corona Simulator 3592+
			}
		},

**Comment by Shchvova** [comment]
Are you using latest build 3601?

**Comment by SimeonAronK** [comment]
Yes

**Comment by SimeonAronK** [comment]
Sorry it is fixed after 3601

**Comment by SimeonAronK** [comment]
Fixed
