### ISSUE TITLE
malware detected on windows

### ISSUE THREAD

**Issue by ekawas** [coronalabs/corona#99]
![image](https://user-images.githubusercontent.com/7060279/85934111-22b1c380-b893-11ea-8482-4ed5d5f802b1.png)

I have tried installing a couple of older versions and the latest version. It seems that there malware being detected by Bitdefender on Windows 10.

I couldn't seem to find version 5.1.3 of lua which i think is what you use ... is this just a me problem?

**Comment by Shchvova** [comment]
Hey. Can you provide some kind of detailed antivirus report for this, so I can report a false negative?

**Comment by ekawas** [comment]
Sure, what are you looking for?

**Comment by ekawas** [comment]
I downloaded the last version again and was unable to reproduce it. I bet it was a false positive unless the downloads came from a different mirror.
